### District-level GDP estimates for Interwar Poland
This notebook uses interwar Poland administrative history and economic datasets to compute the GDP of Interwar Poland on the district level and present an overview of the Polish economic geography in the Interwar Period.

It is a showcase of the use of the whole toolkit.

In [1]:
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
# Necessary imports
import pandas as pd
import numpy as np
import copy
import re

from typing import Dict, List

In [3]:
import os
import sys
from pathlib import Path

os.chdir("../../..")
sys.path.append(str(Path.cwd() / "examples" / "interwar_poland"))
plots_output_path = "E:/OneDrive/Studia/Studia magisterskie/Masterarbeit - Wirtschaftwissenschaft/szacunki_powiatowe_II_RP_from_final_gdp"
# Path for files used for downstream estimates (e.g. inequality estimates)
downstream_csv_path = "E:/OneDrive/Studia/Studia magisterskie/Masterarbeit - Wirtschaftwissenschaft/szacunki_powiatowe_II_RP_corrected/csv_estimates_for_downstream_computations"

In [4]:
from administrative_history.core.core import AdministrativeHistory
from administrative_history.utils.helper_functions import extract_date_parts, read_economic_csv_input

In [5]:
adm_history_processor.harmonize_to_date

NameError: name 'adm_history_processor' is not defined

In [ ]:
export_dist_plot_path = r"E:\OneDrive\Studia\Studia magisterskie\Masterarbeit - Wirtschaftwissenschaft\Additional computations for the article\voivodship_plots\voivodships_1934_10_1.geojson"
administrative_history.export_geojson(adm_history_processor.harmonize_to_date, export_dist_plot_path, "Region", warsaw_region_grouping)

In [19]:
no_of_buildings, no_of_buildings_data_table_metadata, no_of_buildings_adm_state_date = adm_history_api.load_data_table(data_table_id = '1921-number_of_buildings_ready', version='harmonized', custom_grouping=d_city_mapping, custom_grouping_method = 'sum')

In [23]:
no_of_buildings.to_csv(r"E:\OneDrive\Studia\Studia magisterskie\Masterarbeit - Wirtschaftwissenschaft\Additional computations for the article\no_of_buildings.csv", sep=";", encoding = "utf-8")

In [16]:
building_counts, building_counts_data_table_metadata, building_counts_adm_state_date = adm_history_api.load_data_table(data_table_id = '1921-building_counts_ready', version='harmonized', custom_grouping=d_city_mapping, custom_grouping_method = 'sum')

In [18]:
building_counts.to_csv(r"E:\OneDrive\Studia\Studia magisterskie\Masterarbeit - Wirtschaftwissenschaft\Additional computations for the article\building_types.csv", sep=";", encoding="utf-8")

In [12]:
war_destruction, war_destruction_data_table_metadata, war_destruction_adm_state_date = adm_history_api.load_data_table(data_table_id = 'destroyed_buildings', version='harmonized', custom_grouping=d_city_mapping, custom_grouping_method = 'sum')

In [15]:
war_destruction.to_csv(r"E:\OneDrive\Studia\Studia magisterskie\Masterarbeit - Wirtschaftwissenschaft\Additional computations for the article\war_destruction.csv", sep=";", encoding="utf-8")

In [5]:
from global_definitions import (
    administrative_history,
    adm_history_processor,
    adm_history_api,
    adm_history_plotter
)

Loading changes list...
✅ Loaded 309 validated changes in 0.05 seconds.
Loading initial state...
✅ Loaded initial state.
Loading initial district registry...
✅ Loaded 292 validated districts in 0.03 seconds. Set their initial state timespans to (1921-02-19, 1939-09-01).
Loading initial region registry...
✅ Loaded 19 validated regions in 0.00 seconds. Set their initial state timespans to (1921-02-19, 1939-09-01)
Creating administrative history (sequentially applying changes)...
✅ Successfully applied all changes in 11.82 seconds. Administrative history database created.
Loading territories...
Loaded: districts_1922_generalized_dp_800m.shp (271 rows)
Loaded: districts_1929_generalized_dp_800m.shp (281 rows)
Loaded: districts_1931_generalized_dp_800m.shp (283 rows)
Loaded: districts_1934_generalized_dp_800m.shp (264 rows)
Loaded: districts_1939_generalized_dp_800m.shp (265 rows)
✅ Successfully loaded all territories in 2.00 seconds.
Deducing all possible dist territories on the basis of the loaded ones.
Iteration 0 of territory deduction.
✅ All possible information on territories deduced 0.09 seconds.
Defining fallback territories for states with missing state information (where possible).
[Warning] The district 'BARDIOWSKI' has no defined territory in any state. All district states' territories left as undefined (None).
[Warning] The district 'BYTOM MIASTO' has no defined territory in any state. All district states' territories left as undefined (None).
[Warning] The district 'BYTOM WIEŚ' has no defined territory in any state. All district states' territories left as undefined (None).
[Warning] The district 'CZADECKI' has no defined territory in any state. All district states' territories left as undefined (None).
[Warning] The district 'CZESKOCIESZYŃSKI' has no defined territory in any state. All district states' territories left as undefined (None).
[Warning] The district 'FRYDECKI' has no defined territory in any state. All district states' territories left as undefined (None).
[Warning] The district 'GLIWICKI' has no defined territory in any state. All district states' territories left as undefined (None).
[Warning] The district 'KIEŻMARSKI' has no defined territory in any state. All district states' territories left as undefined (None).
[Warning] The district 'NAMIESTOWSKI' has no defined territory in any state. All district states' territories left as undefined (None).
[Warning] The district 'RACIBORSKI' has no defined territory in any state. All district states' territories left as undefined (None).
[Warning] The district 'RUDZKI' has no defined territory in any state. All district states' territories left as undefined (None).
[Warning] The district 'RYBNICKI (ŚLĄSK NIEMIECKI)' has no defined territory in any state. All district states' territories left as undefined (None).
[Warning] The district 'SNIŃSKI' has no defined territory in any state. All district states' territories left as undefined (None).
[Warning] The district 'STAROLUBOWELSKI' has no defined territory in any state. All district states' territories left as undefined (None).
[Warning] The district 'STAROWIEJSKI' has no defined territory in any state. All district states' territories left as undefined (None).
[Warning] The district 'TARNOGÓRSKI (ŚLĄSK NIEMIECKI)' has no defined territory in any state. All district states' territories left as undefined (None).
[Warning] The district 'TROCKI' has no defined territory in any state. All district states' territories left as undefined (None).
[Warning] The district 'TRZCIAŃSKI' has no defined territory in any state. All district states' territories left as undefined (None).
[Warning] The district 'WILEŃSKI' has no defined territory in any state. All district states' territories left as undefined (None).
[Warning] The district 'ZABRSKI' has no defined territory in any state. All district states' territories left as undefined (None).
✅ Successfully created fallback territories in 0.00 seconds.
✅ Successfully loaded 659 cities from data/adm_histories/interwar_poland/cities_coords/cities_coords.geojson
Loading metadata of the data tables that will be harmonized...
✅ Successfully loaded metadata of raw data tables in 0.19 seconds.
Loading processed data metadata...
✅ Successfully loaded harmonized data metadata in 0.07 seconds.

In [6]:
# Use administrative history to process all the input data tables to one administrative state
# adm_history_processor.build_db(metadata_format=["json", "parquet"])

In [7]:
# # English category tree
# adm_history_processor.build_database_tree(filename="database_tree", format="csv")
# adm_history_processor.build_database_tree(filename="database_tree", format="markdown")
# adm_history_processor.build_database_tree(filename="database_tree", format="ascii")

# # Polish category tree
# adm_history_processor.build_database_tree(filename="database_tree_pl", format="csv", lang="pol")
# adm_history_processor.build_database_tree(filename="database_tree_pl", format="markdown", lang="pol")
# adm_history_processor.build_database_tree(filename="database_tree_pl", format="ascii", lang="pol")

# Initial definitions

### Paths Definitions

In [8]:
# Define paths to csvs with regional data
region_agro_production_costs_path = "data/datasets/interwar_poland_database/adm_units_raw_data/data/regions_production_cost_per_ha_ready.csv"
region_total_crops_production_path = "data/datasets/interwar_poland_database/adm_units_raw_data/data/regions_total_crops_production_value_ready.csv"
region_animal_production_va_path = "data/datasets/interwar_poland_database/adm_units_raw_data/data/regions_animal_production_va.csv"
region_forestry_production_va_path = "data/datasets/interwar_poland_database/adm_units_raw_data/data/regions_forestry_production_va.csv"
region_total_sown_area_path = "data/datasets/interwar_poland_database/adm_units_raw_data/data/regions_total_sown_area_ha_ready.csv"
regions_remaining_crops_production_path = "data/datasets/interwar_poland_database/adm_units_raw_data/data/regions_remaining_crops_production.csv"
hourly_wage_by_industry_path = "data/datasets/interwar_poland_database/adm_units_raw_data/data/hourly_wage_by_industry_sector.csv"
hours_per_employee_path = "data/datasets/interwar_poland_database/adm_units_raw_data/data/hours_per_employee.csv"
regional_industry_va_path = "data/datasets/interwar_poland_database/adm_units_raw_data/data/regions_industry_value_added.csv"
regional_public_services_va_path = "data/datasets/interwar_poland_database/adm_units_raw_data/data/regions_public_services_va.csv"
regional_public_services_employment_path = "data/datasets/interwar_poland_database/adm_units_raw_data/data/regions_public_services_employment.csv"
regional_population_path = "data/datasets/interwar_poland_database/adm_units_raw_data/data/regions_population.csv"

# Private services
regional_private_paths = {}
regional_private_paths['domestic_service'] = "data/datasets/interwar_poland_database/adm_units_raw_data/data/regions_private_domestic_service.csv"
regional_private_paths['education'] = "data/datasets/interwar_poland_database/adm_units_raw_data/data/regions_private_education.csv"
regional_private_paths['finance'] = "data/datasets/interwar_poland_database/adm_units_raw_data/data/regions_private_finance.csv"
regional_private_paths['health'] = "data/datasets/interwar_poland_database/adm_units_raw_data/data/regions_private_health.csv"
regional_private_paths['hygiene'] = "data/datasets/interwar_poland_database/adm_units_raw_data/data/regions_private_hygiene.csv"
regional_private_paths['immobility'] = "data/datasets/interwar_poland_database/adm_units_raw_data/data/regions_private_immobility.csv"
regional_private_paths['justice'] = "data/datasets/interwar_poland_database/adm_units_raw_data/data/regions_private_justice.csv"
regional_private_paths['lit_sci_culture'] = "data/datasets/interwar_poland_database/adm_units_raw_data/data/regions_private_lit_sci_culture.csv"
regional_private_paths['religion'] = "data/datasets/interwar_poland_database/adm_units_raw_data/data/regions_private_religion.csv"
regional_private_paths['trans_com'] = "data/datasets/interwar_poland_database/adm_units_raw_data/data/regions_private_trans_com.csv"
regional_private_paths['trade'] = "data/datasets/interwar_poland_database/adm_units_raw_data/data/regions_trade.csv"

### Constants Definitions

In [9]:
from global_definitions import (
    reference_date,
    reference_adm_state,
    all_districts_raw,
    all_regions_raw
)

In [10]:
from global_definitions import (
    r_to_r_group,
    r_group_to_color,
    r_to_example_r,
    example_r_to_color
)

In [11]:
from global_definitions import (
    warsaw_region_grouping,
    d_city_mapping,
    big_cities,
    big_cities_to_color,
    sector_colors
)

In [12]:
from global_definitions import (
    all_districts,
    all_regions,
    d_to_r,
    d_to_r_group,
    d_to_example_r,
    is_big_city
)

In [13]:
from global_definitions import (
    empty_dist_df,
    empty_region_df,
    all_years,
    empty_year_df_dict,
    production_by_year
)

### Load utils

In [14]:
from gdp_computation_utils.general import (
    distribute_r_values_to_d,
    interpolate_missing_years,
    fill_zero_values_by_proportional_scaling,
    sum_up_regions,
    collect_variable_over_years
)
from gdp_computation_utils.plots import (
    plot_administrative_borders,
    plot_convergence,
    plot_year_df_columns,
    plot_df_columns_and_export_excel,
    plot_va_growth_scatter,
    plot_theil_decompositions,
    spatial_autocorrelation_over_time,
    plot_cumulative_variance_decomposition,
    plot_cv_over_time,
    plot_many_cvs_over_time,
    plot_morans_I_over_time,
    plot_theil_decomposition_sequence
)
from gdp_computation_utils.estimates import (
    theil_index, # Computes Theil-index
    decompose_theil_regionally,
    compute_shapley_contributions,
    compute_shapley_contributions,
    analyze_all_years_theil,
    create_distance_matrix,
    distance_matrix_to_weights,
    compute_morans_I, # Computes Moran's I
    compute_gearys_C, # Computes Geary's C
    compute_lisa, # Computes LISA,
    variance_decomposition, # Within-region vs between-region variance
    estimate_multilevel_convergence
)

In [15]:
def save_dict_col_to_csv(df_dict, col_name, filename, custom_years = None):
    """
    Save one column from all dfs in a dict to a csv file.

    Parameters:
        df_dict (dict[int, pd.DataFrame]): Dictionary of DataFrames.
        col_name (str): Name of column to be exported from all dfs in the df_dict.
        filename (str): Output csv filename, e.g. 'output.csv'.
    """
    if custom_years is None:
        custom_years = all_years

    df = empty_dist_df.copy(deep=True)
    for year in custom_years:
        if col_name in df_dict[year]:
            df[year] = df_dict[year][col_name]
            print(f"Column {col_name} from the dict_df added to the DataFrame {year}.")
        else:
            print(f"Column {col_name} absent in the dict_df df for year {year}.")
    print(df)
    df.to_csv(filename, encoding='utf-8', sep=";")
    print(f"DataFrame successfully saved to '{filename}'.")

def save_dict_of_dfs_to_excel(df_dict, filename):
    """
    Save a dictionary of DataFrames to an Excel file, 
    where each key corresponds to a separate sheet.

    Parameters:
        df_dict (dict[int, pd.DataFrame]): Dictionary of DataFrames.
        filename (str): Output Excel filename, e.g. 'output.xlsx'.
    """
    with pd.ExcelWriter(filename, engine='openpyxl') as writer:
        for key, df in df_dict.items():
            # Ensure the sheet name is a string (Excel sheet names must be strings and ≤31 chars)
            sheet_name = str(key)[:31]
            df.to_excel(writer, sheet_name=sheet_name)
    print(f"✅ Saved {len(df_dict)} DataFrames to '{filename}'")

### Create Distance and Proximity Weights Matrix

In [16]:
def prepare_dist_geoms(administrative_history: AdministrativeHistory):
    """
    Prepares an empty geodataframe with 'District' index and geometries
    """
    # Assign new group names using the mapping
    dist_geoms = administrative_history.dist_registry._plot_layer(date=reference_date)[['name_id', 'geometry']]
    dist_geoms = dist_geoms.rename(columns={'name_id': 'District'}).set_index('District')

    # Map each district to its city/group
    dist_geoms['Group'] = dist_geoms.index.map(d_city_mapping)

    # Dissolve (i.e., merge) geometries by group
    dist_geoms = dist_geoms.dissolve(by='Group')

    # Rename index to 'District'
    dist_geoms.index.name = 'District'
    return dist_geoms

dist_geoms = prepare_dist_geoms(administrative_history)

In [17]:
# Generate a distance matrix
distance_matrix = create_distance_matrix(dist_geoms)

e:\git_projects\border_harmonization_toolkit\examples\interwar_poland\district_gdp\gdp_computation_utils\estimates.py:161: UserWarning: Geometry is in a geographic CRS. Results from 'centroid' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.

  centroids = dist_geoms.geometry.centroid

In [18]:
# Build the weights matrix
weights = distance_matrix_to_weights(distance_matrix, threshold=120000, binary=False)  # threshold 120000 means 120km radius

### Plot administrative borders

In [19]:
# plot_administrative_borders(
#     dist_geoms,
#     d_to_r_group,
#     r_group_to_color,
#     show_labels=False,
#     save_to_path=plots_output_path + "/Administrative_Maps/region_groups.png"
# )

# for region_group in ['CENTRAL','EASTERN', 'SOUTHERN', 'WESTERN']:
#     plot_administrative_borders(
#         dist_geoms,
#         d_to_r_group,
#         r_group_to_color,
#         focus_group=region_group,
#         save_to_path=plots_output_path + f"/Administrative_Maps/{region_group}_districts.png"
#     )

# Population and district area

### Load population

1931 population is loaded directly from census data.

In [20]:
population_1931, population_1931_data_table_metadata, population_1931_adm_state_date = adm_history_api.load_data_table(data_table_id = '1931-total_population', version='harmonized', custom_grouping=d_city_mapping, custom_grouping_method = 'sum')
population_1931.rename(columns = {"Census 1931/Population/Total": "Population"}, inplace = True)

1921 population is loaded directly from census data and corrected where needed.

In [21]:
population_1921_raw, population_1921_data_table_metadata, population_1921_adm_state_date = adm_history_api.load_data_table(data_table_id = '1921-total_population_from_1931_census_publications', version='harmonized', custom_grouping=d_city_mapping, custom_grouping_method = 'sum')
population_1921_raw.rename(columns = {"Census 1921/Population/Total (Data from 1931 Census Publications)": "Population"}, inplace = True)
population_1921 = population_1921_raw.copy()

Regional population estimates are taken from Bukowski et al. (2025) paper.

In [22]:
region_population = read_economic_csv_input(adm_level='Region', input_csv_path=regional_population_path)

E:\git_projects\border_harmonization_toolkit\src\administrative_history\utils\helper_functions.py:308: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df = df.applymap(lambda x: x.strip() if isinstance(x, str) else x)

Load city population

In [23]:
city_population_1921, city_population_1921_data_table_metadata, city_population_1921_adm_state_date = adm_history_api.load_data_table(data_table_id = 'city-1921-population', version='harmonized')
city_population_1931, city_population_1931_data_table_metadata, city_population_1931_adm_state_date = adm_history_api.load_data_table(data_table_id = 'city-1931-population', version='harmonized')
city_population_1939, city_population_1939_data_table_metadata, city_population_1939_adm_state_date = adm_history_api.load_data_table(data_table_id = 'city-1939-population', version='harmonized')

city_population = pd.concat([
    city_population_1921.rename(columns={city_population_1921.columns[0]: "1921"}),
    city_population_1931.rename(columns={city_population_1931.columns[0]: "1931"}),
    city_population_1939.rename(columns={city_population_1939.columns[0]: "1939"})
], axis=1)

Map city population data to districts

In [24]:
# Map city data to districts
dist_urban_population = adm_history_processor.map_city_data_to_dists(city_population, reference_date, custom_grouping=d_city_mapping, custom_grouping_method = 'sum')
dist_urban_population.index.name = "District"

⚠️ Dropped 55 rows due to NaN values: ['Bnin (Kórnik)', 'Boćki', 'Brzostek', 'Budzyń', 'Busk', 'Chodorów', 'Ciężkowice', 'Czarny Dunajec', 'Dobromil', 'Gąsawa', 'Gębice', 'Jagielnica (dziś Ukraina)', 'Jaraczew (Jaraczewo)', 'Jazłowiec', 'Kopanica', 'Kopyczyńce', 'Lanckorona', 'Mielnik (nad Bugiem)', 'Mieścisko', 'Narew', 'Niżankowice (dziś Ukraina)', 'Nowe Miasto nad Wartą', 'Nowy Dwór (nad Biebrzą)', 'Obrzycko', 'Odelsk', 'Ostrzeszów', 'Piaski', 'Powidz', 'Raków (Mołodecki)', 'Rogowo (nad jez. Rogowskim)', 'Rostarzewo', 'Rychtal', 'Ryczywół', 'Rynarzewo', 'Stara Sól', 'Szereszów', 'Ulanów', 'Uście Solne', 'Wiśnicz Nowy', 'Wojnicz', 'Władysławów', 'Włodzimierz (dziś Ukraina)', 'Zaniemyśl', 'Łohiszyn', 'Bogumin', 'Bogumin Nowy', 'Chorostków', 'Frysztat', 'Gwoździec', 'Karwina', 'Mielnica Podolska', 'Orłowa', 'Skórcz', 'Trzyniec', 'Tłuste']

Impute data for Wileński region (in 1921 census didn't cover its territory)

In [25]:
# Districts with data from 1919 census
# Extrapolate the data to 1921 to be (1921-1919/1931-1919)*population_1931+population_1919
for dist in ["MOŁODECZAŃSKI", "OSZMIAŃSKI", "POSTAWSKI", "ŚWIĘCIAŃSKI", "WILEJSKI", "WILEŃSKO-TROCKI"]:
    population_1921.loc[dist, "Population"] = (10/12)*population_1921_raw.loc[dist, "Population"] + (2/12)*population_1931.loc[dist, "Population"]

# The data for district 'Wileńsko-Trocki' doesn't incorporate the city 'Nowa Wilejka', so we add it
population_1921.loc["WILEŃSKO-TROCKI", "Population"] = population_1921_raw.loc["WILEŃSKO-TROCKI", "Population"] + city_population.loc["Nowa Wilejka", "1921"]

Compute population weights for distribution of the regional data in 1921 in Silesia and 1939 for all districts

In [26]:
# For districts with plain data problems, use extrapolated dist trends from 1921-1931 to estimate the city population
dist_urban_population.loc["HORODEŃSKI", "1939"] = dist_urban_population.loc["HORODEŃSKI", "1931"] + (8/10)*(dist_urban_population.loc["HORODEŃSKI", "1931"]-dist_urban_population.loc["HORODEŃSKI", "1921"])

In [27]:
dist_urban_population.loc["HORODEŃSKI", "1939"]

14102.2

In [28]:
production_by_year[1921] = empty_dist_df.copy()
production_by_year[1922] = empty_dist_df.copy()
production_by_year[1923] = empty_dist_df.copy()
production_by_year[1939] = empty_dist_df.copy()

In [29]:
dist_urban_population[dist_urban_population["1921"].isna()]

Empty DataFrame
Columns: [1921, 1931, 1939, Cities in district]
Index: []

In [30]:
production_by_year[1921]['Urban_Population'] = dist_urban_population['1921']
production_by_year[1931]['Urban_Population'] = dist_urban_population['1931']
production_by_year[1939]['Urban_Population'] = dist_urban_population['1939']

In [31]:
production_by_year[1921]['Population_Weights'] = (production_by_year[1921]['Urban_Population']/production_by_year[1931]['Urban_Population'])*population_1931["Population"]

In [32]:
# Distribute the Śląskie data
region_population["1921_silesia"] = 0
region_population.loc["ŚLĄSKIE", "1921_silesia"] = 1125334

# Distribute the Śląskie region estimates for 1921
dist_population_df = distribute_r_values_to_d(region_df=region_population, region_value_col="1921_silesia", dist_df=production_by_year[1921], dist_value_col = 'Population_Weights', new_col_name='Population', d_to_r=d_to_r)
production_by_year[1921]['Population'] = dist_population_df['Population']

# Fill in all other slots with 1921 census data
production_by_year[1921].loc[production_by_year[1921]['Population']==0, 'Population'] = population_1921.loc[production_by_year[1921]['Population']==0,"Population"]

# Add 1931 population
production_by_year[1931]["Population"] = population_1931["Population"]

In [33]:
production_by_year[1931].loc['PSZCZYŃSKI', 'Urban_Population']

21762.0

In [34]:
population_1921

variable_name                 Population
District
AUGUSTOWSKI                 62384.000000
BARANOWICKI                119518.000000
BIALSKI (BIAŁA KRAKOWSKA)  114666.000000
BIALSKI (BIAŁA PODLASKA)    84427.569244
BIAŁOSTOCKI                187710.000000
...                                  ...
ŚWIĘTOCHŁOWICKI                 0.000000
ŻNIŃSKI                     41063.000000
ŻYDACZOWSKI                 74018.000000
ŻYWIECKI                   109847.000000
ŻÓŁKIEWSKI                  84574.000000

[247 rows x 1 columns]

In [35]:
population_1921.loc[production_by_year[1921]['Population']==0,"Population"]

Series([], Name: Population, dtype: float64)

In [36]:
production_by_year[1921]['Rural_Population'] = production_by_year[1921]['Population'] - production_by_year[1921]['Urban_Population']
production_by_year[1931]['Rural_Population'] = production_by_year[1931]['Population'] - production_by_year[1931]['Urban_Population']

In [37]:
# Interpolation of Urban Population
production_by_year = interpolate_missing_years(year_to_df=production_by_year, col_name='Urban_Population',
                                all_years=all_years+[1921, 1922, 1923, 1939], empty_dist_df=empty_dist_df.copy(), extrapolate_trends = False)
# Interpolation of Rural Population
production_by_year = interpolate_missing_years(year_to_df=production_by_year, col_name='Rural_Population',
                                all_years=all_years+[1921, 1922, 1923, 1939], empty_dist_df=empty_dist_df.copy(), extrapolate_trends = True)

In [38]:
for year in all_years + [1921, 1922, 1923, 1939]:
    production_by_year[year].loc['M. ST. WARSZAWA', 'Rural_Population'] = 1
    production_by_year[year].loc['POZNAŃ (MIASTO)', 'Rural_Population'] = 1
    production_by_year[year].loc['LWÓW (MIASTO)', 'Rural_Population'] = 1
    production_by_year[year].loc['ŁÓDŹ (MIASTO)', 'Rural_Population'] = 1
    production_by_year[year].loc['KRAKÓW (MIASTO)', 'Rural_Population'] = 1
    production_by_year[year].loc['WILNO (MIASTO)', 'Rural_Population'] = 1

In [39]:
# Sum up urban and rural population for all years
for year in all_years + [1921, 1922, 1923]:
    production_by_year[year]['Population'] = production_by_year[year]['Urban_Population']+production_by_year[year]['Rural_Population']
    # Distribute the regional estimates for each year
    if year not in [1921, 1931]:
        dist_population_df = distribute_r_values_to_d(region_df=region_population, region_value_col=str(year), dist_df=production_by_year[year], dist_value_col = 'Population', new_col_name='Population', d_to_r=d_to_r)
        production_by_year[year]['Population'] = dist_population_df['Population']

Compute Population Growth

In [40]:
population_growth=empty_dist_df.copy()
population_growth['Population Growth 1921-1931'] = 100*(production_by_year[1931]['Population']-production_by_year[1921]['Population'])/production_by_year[1921]['Population']
population_growth['Population Growth 1931-1938'] = 100*(production_by_year[1938]['Population']-production_by_year[1931]['Population'])/production_by_year[1931]['Population']
population_growth['Population Growth 1921-1938'] = 100*(production_by_year[1938]['Population']-production_by_year[1921]['Population'])/production_by_year[1921]['Population']

population_growth['Urban Population Growth 1921-1931 (%)'] = (
    100 * (production_by_year[1931]['Urban_Population'] - production_by_year[1921]['Urban_Population'])
    / production_by_year[1921]['Urban_Population']
).replace([np.inf, -np.inf], 0)

population_growth['Urban Population Growth 1931-1938 (%)'] = (
    100 * (production_by_year[1938]['Urban_Population'] - production_by_year[1931]['Urban_Population'])
    / production_by_year[1931]['Urban_Population']
).replace([np.inf, -np.inf], 0)

population_growth['Urban Population Growth 1921-1938 (%)'] = (
    100 * (production_by_year[1938]['Urban_Population'] - production_by_year[1921]['Urban_Population'])
    / production_by_year[1921]['Urban_Population']
).replace([np.inf, -np.inf], 0)


population_growth['Rural Population Growth 1921-1931 (%)'] = (
    100 * (production_by_year[1931]['Rural_Population'] - production_by_year[1921]['Rural_Population'])
    / production_by_year[1921]['Rural_Population']
).replace([np.inf, -np.inf], 0)

population_growth['Rural Population Growth 1931-1938 (%)'] = (
    100 * (production_by_year[1938]['Rural_Population'] - production_by_year[1931]['Rural_Population'])
    / production_by_year[1931]['Rural_Population']
).replace([np.inf, -np.inf], 0)

population_growth['Rural Population Growth 1921-1938 (%)'] = (
    100 * (production_by_year[1938]['Rural_Population'] - production_by_year[1921]['Rural_Population'])
    / production_by_year[1921]['Rural_Population']
).replace([np.inf, -np.inf], 0)

In [41]:
sum_up_regions(production_by_year[1922], d_to_r)

                 Urban_Population  Rural_Population    Population
Region
BIAŁOSTOCKIE             319330.6      1.010066e+06  1.350899e+06
KIELECKIE                625989.8      1.949888e+06  2.627800e+06
KRAKOWSKIE               489190.0      1.533022e+06  2.043872e+06
LUBELSKIE                360063.2      1.763029e+06  2.167502e+06
LWOWSKIE                 716521.9      2.165936e+06  2.869881e+06
NOWOGRÓDZKIE              72096.8      7.633478e+05  8.789450e+05
POLESKIE                 121900.5      6.645503e+05  8.444083e+05
POMORSKIE                250068.8      7.000237e+05  9.496518e+05
POZNAŃSKIE               667826.1      1.299451e+06  1.987337e+06
STANISŁAWOWSKIE          256357.5      1.027766e+06  1.296445e+06
TARNOPOLSKIE             202497.7      1.249371e+06  1.471553e+06
WARSZAWSKIE             1442000.3      1.675184e+06  3.165775e+06
WOŁYŃSKIE                178384.0      1.442776e+06  1.693090e+06
ZIEMIA WILEŃSKA          191152.0      8.651752e+05  1.079507e+06
ŁÓDZKIE                  896078.8      1.394699e+06  2.336074e+06
ŚLĄSKIE                  429840.2      7.124631e+05  1.140561e+06

In [42]:
for year in [1921, 1922, 1923] + all_years:
    region_population[str(year)+"dist_population_sum"] = sum_up_regions(production_by_year[year], d_to_r)["Population"]

Plot Population Growth

In [43]:
del production_by_year[1939]

In [44]:
# plot_df_columns_and_export_excel(
#     adm_history_plotter=adm_history_plotter,
#     adm_state_date=reference_date,
#     custom_dist_grouping=d_city_mapping,
#     plots_output_path=plots_output_path,
#     path_suffix = "/Population/Growth/",
#     df = population_growth,
#     col_title_prefix="",
#     cmap = 'Reds',
#     export_excel = True
# )

In [45]:
# # Plot population
# plot_year_df_columns(
#     adm_history_plotter=adm_history_plotter,
#     adm_state_date=reference_date,
#     custom_dist_grouping=d_city_mapping,
#     plots_output_path=plots_output_path,
#     path_suffix = "/Population/Total/",
#     year_df_dict = production_by_year,
#     col_name = 'Population',
#     title = 'Population',
#     export_excel = True
# )

In [46]:
# # Plot urban population
# plot_year_df_columns(
#     adm_history_plotter=adm_history_plotter,
#     adm_state_date=reference_date,
#     custom_dist_grouping=d_city_mapping,
#     plots_output_path=plots_output_path,
#     path_suffix = "/Population/Urban/",
#     year_df_dict = production_by_year,
#     col_name = 'Urban_Population',
#     title = 'Population',
#     export_excel = True
# )

In [47]:
# # Plot rural population
# plot_year_df_columns(
#     adm_history_plotter=adm_history_plotter,
#     adm_state_date=reference_date,
#     custom_dist_grouping=d_city_mapping,
#     plots_output_path=plots_output_path,
#     path_suffix = "/Population/Rural/",
#     year_df_dict = production_by_year,
#     col_name = 'Rural_Population',
#     title = 'Rural Population',
#     export_excel = True
# )

In [ ]:
save_dict_col_to_csv(production_by_year, 'Rural_Population', downstream_csv_path + '/rural_population.csv', custom_years = [1921, 1922, 1923] + all_years)

Remove years 1921-1923 from production_by_year dict for further processing

In [48]:
del production_by_year[1921]
del production_by_year[1922]
del production_by_year[1923]

In [49]:
production_by_year[1924]

                           Urban_Population  Rural_Population     Population
District
AUGUSTOWSKI                          9777.5      56316.600000   66934.790371
BARANOWICKI                         18641.7     113332.300000  141007.572161
BIALSKI (BIAŁA KRAKOWSKA)           38821.6      83182.700000  123598.018706
BIALSKI (BIAŁA PODLASKA)            19984.0      73895.519827   95421.668474
BIAŁOSTOCKI                        104185.3      96565.400000  203304.168170
...                                     ...               ...            ...
ŚWIĘTOCHŁOWICKI                     42995.3     143264.899120  183792.933214
ŻNIŃSKI                              7636.0      33564.400000   41172.831572
ŻYDACZOWSKI                         14978.6      61979.100000   78452.547341
ŻYWIECKI                            11420.3     104757.300000  117695.205645
ŻÓŁKIEWSKI                          15609.4      72244.500000   88727.268967

[247 rows x 3 columns]

### Load district area

In [50]:
dist_area_data_table, dist_area_metadata, dist_area_date = adm_history_api.load_data_table(data_table_id = 'dist_area_baseline_adm_state', version = 'harmonized', custom_grouping=d_city_mapping, custom_grouping_method = 'sum')

### Compute population density

In [51]:
# 1) Pull aligned Series (force same index and dtype)
pop = population_1931['Population'].astype('float64')
area = dist_area_data_table['District Area'].astype('float64')

# 2) Reindex one to the other so labels line up (introduces NaN where missing)
area_aligned = area.reindex(pop.index)

# 3) Compute density safely (optionally avoid divide-by-zero)
density = (pop / area_aligned) 

# 4) Convert from people/ha to people/km^2
density = density / 100
# If you want log defined only for positive densities:
density_pos = density.where(density > 0)

population_1931['Population Density: People per km2'] = density
population_1931['Log Population Density'] = np.log(density_pos)

In [52]:
# plot_df_columns_and_export_excel(
#     adm_history_plotter=adm_history_plotter,
#     adm_state_date=reference_date,
#     custom_dist_grouping=d_city_mapping,
#     plots_output_path=plots_output_path,
#     path_suffix = "/Population/",
#     df = population_1931,
#     col_title_prefix = "1931",
#     cmap = 'Reds',
#     export_excel = True
# )

# Agriculture

## Forests

### Load forests data

In [53]:
forests_data_table, forests_metadata, forests_date = adm_history_api.load_data_table(data_table_id = '1930-forests_area_ha_ready', version = 'harmonized', custom_grouping=d_city_mapping, custom_grouping_method = 'sum')
forests_data_table.rename(columns={'Forests/Area': 'Total Forest Area'}, inplace = True)
forests_data_table = forests_data_table.merge(dist_area_data_table, on='District', how='left')
forests_data_table['Forest as District Area Proportion'] = forests_data_table['Total Forest Area']/forests_data_table['District Area']

Generate and save plots with forest area and forest area in comparison to .

In [54]:
forests_data_table['Total Forest Area']

District
AUGUSTOWSKI                  80122.000000
BARANOWICKI                  80442.000000
BIALSKI (BIAŁA KRAKOWSKA)    13627.451708
BIALSKI (BIAŁA PODLASKA)     31925.212785
BIAŁOSTOCKI                  71471.000000
                                 ...
ŚWIĘTOCHŁOWICKI                226.403359
ŻNIŃSKI                       8592.474474
ŻYDACZOWSKI                  20888.069092
ŻYWIECKI                     41582.639518
ŻÓŁKIEWSKI                   25961.000000
Name: Total Forest Area, Length: 247, dtype: float64

In [55]:
# plot_df_columns_and_export_excel(
#     adm_history_plotter=adm_history_plotter,
#     adm_state_date=reference_date,
#     custom_dist_grouping=d_city_mapping,
#     plots_output_path=plots_output_path,
#     path_suffix = "/Agriculture/Forestry/",
#     df = forests_data_table,
#     col_title_prefix = "",
#     cmap = "YlOrBr",
#     export_excel = True,
#     columns_subset = ['Total Forest Area', 'Forest as District Area Proportion']
# )

I take the total value of the forest production from Wronski et al. (2025) and distribute it between districts according to forest area per district.

In [56]:
region_forestry_production_va = read_economic_csv_input(adm_level='Region', input_csv_path=region_forestry_production_va_path)

E:\git_projects\border_harmonization_toolkit\src\administrative_history\utils\helper_functions.py:308: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df = df.applymap(lambda x: x.strip() if isinstance(x, str) else x)

In [57]:
for year, dist_df in production_by_year.items():
    dist_production_df = distribute_r_values_to_d(region_df=region_forestry_production_va, region_value_col=str(year), dist_df=forests_data_table, dist_value_col = 'Total Forest Area', new_col_name='Forestry VA', d_to_r=d_to_r)
    production_by_year[year]['Forestry Value Added'] = dist_production_df['Forestry VA']

In [58]:
# plot_year_df_columns(
#     adm_history_plotter=adm_history_plotter,
#     adm_state_date=reference_date,
#     custom_dist_grouping=d_city_mapping,
#     plots_output_path=plots_output_path,
#     path_suffix = "/Agriculture/Forestry/VA/",
#     year_df_dict = production_by_year,
#     col_name = 'Forestry Value Added',
#     title = 'Forestry Crops VA',
#     export_excel = True
# )

## Crops

### Prepare prices and yields data for 5 main crops

Load crop prices for 5 main crops:
- 'Pszenica',
- 'Żyto',
- 'Jęczmień',
- 'Owies',
- 'Ziemniaki'.

In cases where prices of multiple crop subtypes are given, I choose:
- 'Ziemniaki: Jadalne', where 'Ziemniaki: Jadalne' and 'Ziemniaki: Fabryczne' are given,
- 'Jęczmień: Browarny', where 'Jęczmień: Browarny', and 'Jęczmień: Innych gatunków' or 'Jęczmień: Na kaszę' are given.

In [59]:
def fill_zeros_with_column(target_df, source_df, target_col, source_col):
    """
    Replace 0s in `target_col` of `target_df` with corresponding values from `source_col` in `source_df`.

    Parameters:
        source_df (pd.DataFrame): DataFrame with values used for filling.
        target_df (pd.DataFrame): DataFrame whose column will be filled.
        target_col (str): Name of the column to fill.
        source_col (str): Name of the column to pull values from.

    Returns:
        pd.DataFrame: Updated DataFrame with the target column filled.
    """
    if source_col not in source_df.columns:
        print(f"❌ Column '{source_col}' not present in source_df.")
    else:
        target_df = target_df.copy()
        zero_mask = target_df[target_col] == 0
        filled_indices = target_df.index[zero_mask]

        target_df.loc[zero_mask, target_col] = source_df.loc[zero_mask, source_col]

        print(f"✅ Filled '{target_col}' in {len(filled_indices)} rows using '{source_col}' from source_df.")
        if not filled_indices.empty:
            print("📍 Filled indices:")
            print(filled_indices.tolist())
    return target_df

In [60]:
columns_to_select = ['Wheat', 'Rye', 'Barley/All Types', 'Oats', 'Potatoes/All Types', 'Potatoes/Edible', 'Barley/Malting Barley']
columns_to_select = ['Prices/Local Paid to Producers/' + col for col in columns_to_select]
# Load the crops prices
crops_prices_data_table_ids = [
    data_table.data_table_id
    for data_table in adm_history_processor.processed_data_metadata.items
    if any(col.startswith("Prices/") for col in data_table.columns.keys())
]
crops_prices_dfs = [adm_history_api.load_data_table(data_table_id = crops_data_table_id, version = 'harmonized', custom_grouping=d_city_mapping, custom_grouping_method='average') for crops_data_table_id in crops_prices_data_table_ids]
crops_prices_year_df = {extract_date_parts(metadata.date)[0]: df for df, metadata, date in crops_prices_dfs if extract_date_parts(metadata.date)[1] == 8 or extract_date_parts(metadata.date)[0] is None}
crops_prices_year_df_clean = copy.deepcopy(empty_year_df_dict)
for year, df in crops_prices_year_df.items():
    print(f"Year: {year}.")
    print(f"df.columns: {df.columns}")
    existing_columns = [col for col in columns_to_select if col in df.columns]
    df = df[existing_columns]
    df.columns = [col.split('/')[2].strip() for col in df.columns]
    print(f"columns_to_select: {columns_to_select}")
    print(f"existing_columns: {existing_columns}")
    df_filled = fill_zeros_with_column(df, crops_prices_year_df[year], 'Barley', 'Prices/Local Paid to Producers/Barley/For Groats')
    df_filled = fill_zeros_with_column(df_filled, crops_prices_year_df[year], 'Barley', 'Prices/Local Paid to Producers/Barley/Other Varieties')
    crops_prices_year_df_clean[year] = df_filled

Year: 1926.
df.columns: Index(['Prices/Local Paid to Producers/Barley/All Types',
       'Prices/Local Paid to Producers/Buckwheat',
       'Prices/Local Paid to Producers/Hay/All Types',
       'Prices/Local Paid to Producers/Milking Cow (Maximum Price)',
       'Prices/Local Paid to Producers/Milking Cow (Minimum Price)',
       'Prices/Local Paid to Producers/Oats',
       'Prices/Local Paid to Producers/Pig (per kg)',
       'Prices/Local Paid to Producers/Potatoes/Edible',
       'Prices/Local Paid to Producers/Potatoes/For Processing',
       'Prices/Local Paid to Producers/Rye',
       'Prices/Local Paid to Producers/Straw',
       'Prices/Local Paid to Producers/Wheat',
       'Prices/Local Paid to Producers/Working Horse (Maximum Price)',
       'Prices/Local Paid to Producers/Working Horse (Minimum Price)'],
      dtype='object', name='variable_name')
columns_to_select: ['Prices/Local Paid to Producers/Wheat', 'Prices/Local Paid to Producers/Rye', 'Prices/Local Paid to Producers/Barley/All Types', 'Prices/Local Paid to Producers/Oats', 'Prices/Local Paid to Producers/Potatoes/All Types', 'Prices/Local Paid to Producers/Potatoes/Edible', 'Prices/Local Paid to Producers/Barley/Malting Barley']
existing_columns: ['Prices/Local Paid to Producers/Wheat', 'Prices/Local Paid to Producers/Rye', 'Prices/Local Paid to Producers/Barley/All Types', 'Prices/Local Paid to Producers/Oats', 'Prices/Local Paid to Producers/Potatoes/Edible']
❌ Column 'Prices/Local Paid to Producers/Barley/For Groats' not present in source_df.
❌ Column 'Prices/Local Paid to Producers/Barley/Other Varieties' not present in source_df.
Year: 1928.
df.columns: Index(['Prices/Local Paid to Producers/Barley/All Types',
       'Prices/Local Paid to Producers/Buckwheat',
       'Prices/Local Paid to Producers/Hay/Clover Hay',
       'Prices/Local Paid to Producers/Hay/Meadow Hay',
       'Prices/Local Paid to Producers/Milking Cow (Maximum Price)',
       'Prices/Local Paid to Producers/Milking Cow (Minimum Price)',
       'Prices/Local Paid to Producers/Oats',
       'Prices/Local Paid to Producers/Potatoes/Edible',
       'Prices/Local Paid to Producers/Rye',
       'Prices/Local Paid to Producers/Straw',
       'Prices/Local Paid to Producers/Wheat',
       'Prices/Local Paid to Producers/Working Horse (Maximum Price)',
       'Prices/Local Paid to Producers/Working Horse (Minimum Price)'],
      dtype='object', name='variable_name')
columns_to_select: ['Prices/Local Paid to Producers/Wheat', 'Prices/Local Paid to Producers/Rye', 'Prices/Local Paid to Producers/Barley/All Types', 'Prices/Local Paid to Producers/Oats', 'Prices/Local Paid to Producers/Potatoes/All Types', 'Prices/Local Paid to Producers/Potatoes/Edible', 'Prices/Local Paid to Producers/Barley/Malting Barley']
existing_columns: ['Prices/Local Paid to Producers/Wheat', 'Prices/Local Paid to Producers/Rye', 'Prices/Local Paid to Producers/Barley/All Types', 'Prices/Local Paid to Producers/Oats', 'Prices/Local Paid to Producers/Potatoes/Edible']
❌ Column 'Prices/Local Paid to Producers/Barley/For Groats' not present in source_df.
❌ Column 'Prices/Local Paid to Producers/Barley/Other Varieties' not present in source_df.
Year: 1930.
df.columns: Index(['Prices/Local Paid to Producers/Barley/Malting Barley',
       'Prices/Local Paid to Producers/Barley/Other Varieties',
       'Prices/Local Paid to Producers/Buckwheat',
       'Prices/Local Paid to Producers/Hay/Clover Hay',
       'Prices/Local Paid to Producers/Hay/Meadow Hay',
       'Prices/Local Paid to Producers/Oats',
       'Prices/Local Paid to Producers/Peas',
       'Prices/Local Paid to Producers/Potatoes/Edible',
       'Prices/Local Paid to Producers/Potatoes/For Processing',
       'Prices/Local Paid to Producers/Rye',
       'Prices/Local Paid to Producers/Straw',
       'Prices/Local Paid to Producers/Wheat'],
      dtype='object', name='variable_name')
columns_to_select: ['Prices/Local Paid to Producers/Wheat', 'Prices/Local Paid to Producers/Rye', 'Prices/Local Paid to Producers/Barley/All Types', 'Prices/Local Paid to Producers/Oats', 'Prices/Local Paid to Producers/Potatoes/All Types', 'Prices/Local Paid to Producers/Potatoes/Edible', 'Prices/Local Paid to Producers/Barley/Malting Barley']
existing_columns: ['Prices/Local Paid to Producers/Wheat', 'Prices/Local Paid to Producers/Rye', 'Prices/Local Paid to Producers/Oats', 'Prices/Local Paid to Producers/Potatoes/Edible', 'Prices/Local Paid to Producers/Barley/Malting Barley']
❌ Column 'Prices/Local Paid to Producers/Barley/For Groats' not present in source_df.
✅ Filled 'Barley' in 0 rows using 'Prices/Local Paid to Producers/Barley/Other Varieties' from source_df.
Year: 1931.
df.columns: Index(['Prices/Local Paid to Producers/Barley/Malting Barley',
       'Prices/Local Paid to Producers/Barley/Other Varieties',
       'Prices/Local Paid to Producers/Buckwheat',
       'Prices/Local Paid to Producers/Hay/Clover Hay',
       'Prices/Local Paid to Producers/Hay/Meadow Hay',
       'Prices/Local Paid to Producers/Oats',
       'Prices/Local Paid to Producers/Peas',
       'Prices/Local Paid to Producers/Potatoes/Edible',
       'Prices/Local Paid to Producers/Potatoes/For Processing',
       'Prices/Local Paid to Producers/Rye',
       'Prices/Local Paid to Producers/Straw',
       'Prices/Local Paid to Producers/Wheat'],
      dtype='object', name='variable_name')
columns_to_select: ['Prices/Local Paid to Producers/Wheat', 'Prices/Local Paid to Producers/Rye', 'Prices/Local Paid to Producers/Barley/All Types', 'Prices/Local Paid to Producers/Oats', 'Prices/Local Paid to Producers/Potatoes/All Types', 'Prices/Local Paid to Producers/Potatoes/Edible', 'Prices/Local Paid to Producers/Barley/Malting Barley']
existing_columns: ['Prices/Local Paid to Producers/Wheat', 'Prices/Local Paid to Producers/Rye', 'Prices/Local Paid to Producers/Oats', 'Prices/Local Paid to Producers/Potatoes/Edible', 'Prices/Local Paid to Producers/Barley/Malting Barley']
❌ Column 'Prices/Local Paid to Producers/Barley/For Groats' not present in source_df.
✅ Filled 'Barley' in 0 rows using 'Prices/Local Paid to Producers/Barley/Other Varieties' from source_df.
Year: 1932.
df.columns: Index(['Prices/Local Paid to Producers/Barley/Malting Barley',
       'Prices/Local Paid to Producers/Barley/Other Varieties',
       'Prices/Local Paid to Producers/Buckwheat',
       'Prices/Local Paid to Producers/Hay/Clover Hay',
       'Prices/Local Paid to Producers/Hay/Meadow Hay',
       'Prices/Local Paid to Producers/Oats',
       'Prices/Local Paid to Producers/Peas',
       'Prices/Local Paid to Producers/Potatoes/Edible',
       'Prices/Local Paid to Producers/Potatoes/For Processing',
       'Prices/Local Paid to Producers/Rye',
       'Prices/Local Paid to Producers/Straw',
       'Prices/Local Paid to Producers/Wheat'],
      dtype='object', name='variable_name')
columns_to_select: ['Prices/Local Paid to Producers/Wheat', 'Prices/Local Paid to Producers/Rye', 'Prices/Local Paid to Producers/Barley/All Types', 'Prices/Local Paid to Producers/Oats', 'Prices/Local Paid to Producers/Potatoes/All Types', 'Prices/Local Paid to Producers/Potatoes/Edible', 'Prices/Local Paid to Producers/Barley/Malting Barley']
existing_columns: ['Prices/Local Paid to Producers/Wheat', 'Prices/Local Paid to Producers/Rye', 'Prices/Local Paid to Producers/Oats', 'Prices/Local Paid to Producers/Potatoes/Edible', 'Prices/Local Paid to Producers/Barley/Malting Barley']
❌ Column 'Prices/Local Paid to Producers/Barley/For Groats' not present in source_df.
✅ Filled 'Barley' in 0 rows using 'Prices/Local Paid to Producers/Barley/Other Varieties' from source_df.
Year: 1934.
df.columns: Index(['Prices/Local Paid to Producers/Barley/Malting Barley',
       'Prices/Local Paid to Producers/Barley/Other Varieties',
       'Prices/Local Paid to Producers/Buckwheat',
       'Prices/Local Paid to Producers/Hay/Clover Hay',
       'Prices/Local Paid to Producers/Hay/Meadow Hay',
       'Prices/Local Paid to Producers/Oats',
       'Prices/Local Paid to Producers/Peas',
       'Prices/Local Paid to Producers/Potatoes/Edible',
       'Prices/Local Paid to Producers/Potatoes/For Processing',
       'Prices/Local Paid to Producers/Rye',
       'Prices/Local Paid to Producers/Straw',
       'Prices/Local Paid to Producers/Wheat'],
      dtype='object', name='variable_name')
columns_to_select: ['Prices/Local Paid to Producers/Wheat', 'Prices/Local Paid to Producers/Rye', 'Prices/Local Paid to Producers/Barley/All Types', 'Prices/Local Paid to Producers/Oats', 'Prices/Local Paid to Producers/Potatoes/All Types', 'Prices/Local Paid to Producers/Potatoes/Edible', 'Prices/Local Paid to Producers/Barley/Malting Barley']
existing_columns: ['Prices/Local Paid to Producers/Wheat', 'Prices/Local Paid to Producers/Rye', 'Prices/Local Paid to Producers/Oats', 'Prices/Local Paid to Producers/Potatoes/Edible', 'Prices/Local Paid to Producers/Barley/Malting Barley']
❌ Column 'Prices/Local Paid to Producers/Barley/For Groats' not present in source_df.
✅ Filled 'Barley' in 41 rows using 'Prices/Local Paid to Producers/Barley/Other Varieties' from source_df.
📍 Filled indices:
['BIŁGORAJSKI', 'BRZOZOWSKI', 'CHORZÓW', 'CZARNKOWSKI', 'DOBROMILSKI', 'DOLIŃSKI', 'DROHOBYCKI', 'DZIŚNIEŃSKI', 'DĄBROWSKI', 'IWACEWICKI', 'JAWOROWSKI', 'KONECKI', 'KOSOWSKI (KOSÓW HUCULSKI)', 'KOSZYRSKI', 'KRAKÓW (MIASTO)', 'LESKI', 'LIDZKI', 'LUBOMELSKI', 'LWÓW (MIASTO)', 'M. ST. WARSZAWA', 'MOŁODECZAŃSKI', 'MYŚLENICKI', 'NIŻAŃSKI', 'NOWOGRÓDZKI', 'NOWOTARSKI', 'PIŃSKI', 'POZNAŃ (MIASTO)', 'ROHATYŃSKI', 'SAMBORSKI', 'SARNEŃSKI', 'STANISŁAWOWSKI', 'STOŁPECKI', 'TURCZAŃSKI', 'WADOWICKI', 'WILNO (MIASTO)', 'WOŁOŻYŃSKI', 'ŁUNINIECKI', 'ŁÓDŹ (MIASTO)', 'ŚWIĘCIAŃSKI', 'ŚWIĘTOCHŁOWICKI', 'ŻYWIECKI']
Year: 1935.
df.columns: Index(['Prices/Local Paid to Producers/Barley/For Groats',
       'Prices/Local Paid to Producers/Barley/Malting Barley',
       'Prices/Local Paid to Producers/Buckwheat',
       'Prices/Local Paid to Producers/Hay/Clover Hay',
       'Prices/Local Paid to Producers/Hay/Meadow Hay',
       'Prices/Local Paid to Producers/Oats',
       'Prices/Local Paid to Producers/Peas',
       'Prices/Local Paid to Producers/Potatoes/Edible',
       'Prices/Local Paid to Producers/Potatoes/For Processing',
       'Prices/Local Paid to Producers/Rye',
       'Prices/Local Paid to Producers/Straw',
       'Prices/Local Paid to Producers/Wheat'],
      dtype='object', name='variable_name')
columns_to_select: ['Prices/Local Paid to Producers/Wheat', 'Prices/Local Paid to Producers/Rye', 'Prices/Local Paid to Producers/Barley/All Types', 'Prices/Local Paid to Producers/Oats', 'Prices/Local Paid to Producers/Potatoes/All Types', 'Prices/Local Paid to Producers/Potatoes/Edible', 'Prices/Local Paid to Producers/Barley/Malting Barley']
existing_columns: ['Prices/Local Paid to Producers/Wheat', 'Prices/Local Paid to Producers/Rye', 'Prices/Local Paid to Producers/Oats', 'Prices/Local Paid to Producers/Potatoes/Edible', 'Prices/Local Paid to Producers/Barley/Malting Barley']
✅ Filled 'Barley' in 56 rows using 'Prices/Local Paid to Producers/Barley/For Groats' from source_df.
📍 Filled indices:
['BIAŁOSTOCKI', 'BIELSKO', 'BIŁGORAJSKI', 'BRZOZOWSKI', 'CHORZÓW', 'DOLIŃSKI', 'DROHICKI', 'DROHOBYCKI', 'GRÓDECKI', 'IWACEWICKI', 'KATOWICE', 'KOLBUSZOWSKI', 'KONECKI', 'KOSOWSKI (KOSÓW HUCULSKI)', 'KOSTOPOLSKI', 'KOSZYRSKI', 'KOZIENICKI', 'KOŁOMYJSKI', 'KRAKÓW (MIASTO)', 'LESKI', 'LUBOMELSKI', 'LWÓW (MIASTO)', 'M. ST. WARSZAWA', 'MIĘDZYCHODZKI', 'MIŃSKI', 'NIEŚWIESKI', 'NIŻAŃSKI', 'NOWOTARSKI', 'OPOCZYŃSKI', 'OSTROWSKI (OSTRÓW MAZOWIECKA)', 'OSZMIAŃSKI', 'PIŃSKI', 'POSTAWSKI', 'POZNAŃ (MIASTO)', 'PRZEMYŚLAŃSKI', 'RADZYMIŃSKI', 'ROHATYŃSKI', 'SANDOMIERSKI', 'SARNEŃSKI', 'SKIERNIEWICKI', 'STOLIŃSKI', 'STOŁPECKI', 'TURCZAŃSKI', 'WADOWICKI', 'WILNO (MIASTO)', 'WOŁOŻYŃSKI', 'WĘGROWSKI', 'ZBOROWSKI', 'ŁAŃCUCKI', 'ŁOMŻYŃSKI', 'ŁUNINIECKI', 'ŁÓDŹ (MIASTO)', 'ŚWIĘCIAŃSKI', 'ŚWIĘTOCHŁOWICKI', 'ŻYWIECKI', 'ŻÓŁKIEWSKI']
❌ Column 'Prices/Local Paid to Producers/Barley/Other Varieties' not present in source_df.
Year: 1936.
df.columns: Index(['Prices/Local Paid to Producers/Barley/For Groats',
       'Prices/Local Paid to Producers/Barley/Malting Barley',
       'Prices/Local Paid to Producers/Buckwheat',
       'Prices/Local Paid to Producers/Hay/Clover Hay',
       'Prices/Local Paid to Producers/Hay/Meadow Hay',
       'Prices/Local Paid to Producers/Oats',
       'Prices/Local Paid to Producers/Peas',
       'Prices/Local Paid to Producers/Potatoes/Edible',
       'Prices/Local Paid to Producers/Potatoes/For Processing',
       'Prices/Local Paid to Producers/Rye',
       'Prices/Local Paid to Producers/Straw',
       'Prices/Local Paid to Producers/Wheat'],
      dtype='object', name='variable_name')
columns_to_select: ['Prices/Local Paid to Producers/Wheat', 'Prices/Local Paid to Producers/Rye', 'Prices/Local Paid to Producers/Barley/All Types', 'Prices/Local Paid to Producers/Oats', 'Prices/Local Paid to Producers/Potatoes/All Types', 'Prices/Local Paid to Producers/Potatoes/Edible', 'Prices/Local Paid to Producers/Barley/Malting Barley']
existing_columns: ['Prices/Local Paid to Producers/Wheat', 'Prices/Local Paid to Producers/Rye', 'Prices/Local Paid to Producers/Oats', 'Prices/Local Paid to Producers/Potatoes/Edible', 'Prices/Local Paid to Producers/Barley/Malting Barley']
✅ Filled 'Barley' in 56 rows using 'Prices/Local Paid to Producers/Barley/For Groats' from source_df.
📍 Filled indices:
['BIAŁOSTOCKI', 'BIELSKO', 'BIŁGORAJSKI', 'BRZOZOWSKI', 'CHORZÓW', 'DOLIŃSKI', 'DROHICKI', 'DROHOBYCKI', 'GRÓDECKI', 'IWACEWICKI', 'KATOWICE', 'KOLBUSZOWSKI', 'KONECKI', 'KOSOWSKI (KOSÓW HUCULSKI)', 'KOSTOPOLSKI', 'KOSZYRSKI', 'KOZIENICKI', 'KOŁOMYJSKI', 'KRAKÓW (MIASTO)', 'LESKI', 'LUBOMELSKI', 'LWÓW (MIASTO)', 'M. ST. WARSZAWA', 'MIĘDZYCHODZKI', 'MIŃSKI', 'NIEŚWIESKI', 'NIŻAŃSKI', 'NOWOTARSKI', 'OPOCZYŃSKI', 'OSTROWSKI (OSTRÓW MAZOWIECKA)', 'OSZMIAŃSKI', 'PIŃSKI', 'POSTAWSKI', 'POZNAŃ (MIASTO)', 'PRZEMYŚLAŃSKI', 'RADZYMIŃSKI', 'ROHATYŃSKI', 'SANDOMIERSKI', 'SARNEŃSKI', 'SKIERNIEWICKI', 'STOLIŃSKI', 'STOŁPECKI', 'TURCZAŃSKI', 'WADOWICKI', 'WILNO (MIASTO)', 'WOŁOŻYŃSKI', 'WĘGROWSKI', 'ZBOROWSKI', 'ŁAŃCUCKI', 'ŁOMŻYŃSKI', 'ŁUNINIECKI', 'ŁÓDŹ (MIASTO)', 'ŚWIĘCIAŃSKI', 'ŚWIĘTOCHŁOWICKI', 'ŻYWIECKI', 'ŻÓŁKIEWSKI']
❌ Column 'Prices/Local Paid to Producers/Barley/Other Varieties' not present in source_df.

Load crops size data

In [61]:
# Load the crops size
columns_to_select = ['Wheat', 'Rye', 'Barley', 'Oats', 'Potatoes']
columns_to_select = ['Crops/Size/' + col for col in columns_to_select]
# Load the crops size
crops_size_data_table_ids = [
    data_table.data_table_id
    for data_table in adm_history_processor.processed_data_metadata.items
    if any(col in columns_to_select for col in data_table.columns.keys())
]
crops_size_dfs = [adm_history_api.load_data_table(data_table_id = crops_data_table_id, version = 'harmonized', custom_grouping=d_city_mapping, custom_grouping_method = 'sum') for crops_data_table_id in crops_size_data_table_ids]
crops_size_year_df = {extract_date_parts(metadata.date)[0]: df for df, metadata, date in crops_size_dfs}
crops_size_years = crops_size_year_df.keys()
crops_size_year_df_clean = copy.deepcopy(empty_year_df_dict)
for year, df in crops_size_year_df.items():
    print(f"Year: {year}")
    print(f"df.columns: {df.columns}")
    existing_columns = [col for col in columns_to_select if col in df.columns]
    df = df[existing_columns]
    df.columns = [col.split('/')[2].strip() for col in df.columns]
    crops_size_year_df_clean[year] = df

Year: 1924
df.columns: Index(['Crops/Size/Barley', 'Crops/Size/Oats', 'Crops/Size/Potatoes',
       'Crops/Size/Rye', 'Crops/Size/Wheat'],
      dtype='object', name='variable_name')
Year: 1926
df.columns: Index(['Crops/Size/Barley', 'Crops/Size/Oats', 'Crops/Size/Potatoes',
       'Crops/Size/Rye', 'Crops/Size/Wheat'],
      dtype='object', name='variable_name')
Year: 1928
df.columns: Index(['Crops/Size/Barley', 'Crops/Size/Oats', 'Crops/Size/Potatoes',
       'Crops/Size/Rye', 'Crops/Size/Sugar Beets', 'Crops/Size/Wheat'],
      dtype='object', name='variable_name')
Year: 1930
df.columns: Index(['Crops/Size/Barley', 'Crops/Size/Oats', 'Crops/Size/Potatoes',
       'Crops/Size/Rye', 'Crops/Size/Sugar Beets', 'Crops/Size/Wheat'],
      dtype='object', name='variable_name')
Year: 1931
df.columns: Index(['Crops/Size/Barley', 'Crops/Size/Oats', 'Crops/Size/Potatoes',
       'Crops/Size/Rye', 'Crops/Size/Sugar Beets', 'Crops/Size/Wheat'],
      dtype='object', name='variable_name')
Year: 1932
df.columns: Index(['Crops/Size/Barley', 'Crops/Size/Beans, Broad Beans, and Lentils',
       'Crops/Size/Buckwheat', 'Crops/Size/Flax/Fiber', 'Crops/Size/Flax/Seed',
       'Crops/Size/Hemp/Seed', 'Crops/Size/Hops', 'Crops/Size/Maize',
       'Crops/Size/Millet', 'Crops/Size/Mixtures for Grain/Barley',
       'Crops/Size/Mixtures for Grain/Other mixtures', 'Crops/Size/Oats',
       'Crops/Size/Peas', 'Crops/Size/Potatoes',
       'Crops/Size/Rapeseed and Turnip Rape', 'Crops/Size/Rye',
       'Crops/Size/Seed/Fiber', 'Crops/Size/Sugar Beets', 'Crops/Size/Tabacco',
       'Crops/Size/Wheat'],
      dtype='object', name='variable_name')
Year: 1934
df.columns: Index(['Crops/Size/Barley', 'Crops/Size/Millet', 'Crops/Size/Oats',
       'Crops/Size/Potatoes', 'Crops/Size/Rye', 'Crops/Size/Sugar Beets',
       'Crops/Size/Wheat'],
      dtype='object', name='variable_name')
Year: 1935
df.columns: Index(['Crops/Size/Barley', 'Crops/Size/Oats', 'Crops/Size/Potatoes',
       'Crops/Size/Rye', 'Crops/Size/Sugar Beets', 'Crops/Size/Wheat'],
      dtype='object', name='variable_name')
Year: 1936
df.columns: Index(['Crops/Size/Barley', 'Crops/Size/Buckwheat', 'Crops/Size/Oats',
       'Crops/Size/Potatoes', 'Crops/Size/Rye', 'Crops/Size/Wheat'],
      dtype='object', name='variable_name')
Year: 1938
df.columns: Index(['Crops/Size/Barley', 'Crops/Size/Buckwheat', 'Crops/Size/Maize',
       'Crops/Size/Millet', 'Crops/Size/Oats', 'Crops/Size/Potatoes',
       'Crops/Size/Rye', 'Crops/Size/Sugar Beets', 'Crops/Size/Wheat'],
      dtype='object', name='variable_name')

I load 5 main crops price index computed on the basis of data for all years by Wronski et al. (2025) on the basis of voivodship average prices for 5 main crops.

In [62]:
price_index_5_main_crops = {
    1924: 1.00,
    1925: 1.34,
    1926: 2.12,
    1927: 2.78,
    1928: 3.25,
    1929: 2.06,
    1930: 1.55,
    1931: 1.44,
    1932: 1.24,
    1933: 1.07,
    1934: 1.07,
    1935: 0.84,
    1936: 0.99,
    1937: 1.54,
    1938: 1.14
}

### Interpolate the prices

In [63]:
for crop_name in ['Wheat', 'Rye', 'Barley', 'Oats', 'Potatoes']:
    crops_prices_year_df_clean = interpolate_missing_years(year_to_df=crops_prices_year_df_clean, col_name=crop_name,
                                all_years=all_years, empty_dist_df=empty_dist_df.copy(), extrapolate_trends = False)
crops_prices_years = all_years

### Compute Crop Value of 5 main crops

In [64]:
crops_production_years = copy.deepcopy(empty_year_df_dict)

# Find years present in both datasets
common_years = sorted(set(crops_size_years) & set(crops_prices_years))

for year in common_years:
    yield_df = crops_size_year_df_clean[year]
    price_df = crops_prices_year_df_clean[year]

    # Ensure both dfs have the same columns (crops) and index
    if set(yield_df.columns) != set(price_df.columns):
        raise ValueError(f"Crop mismatch in year {year}:\nYield: {yield_df.columns}\nPrice: {price_df.columns}")
    if set(yield_df.index) != set(price_df.index):
        missing_in_price_df_index = set(yield_df.index) - set(price_df.index)
        missing_in_yield_df_index = set(price_df.index) - set(yield_df.index)
        raise ValueError(f"Index mismatch in year {year}:\nMissing in price df: {missing_in_price_df_index}.\nMissing in yield df: {missing_in_yield_df_index}.")

    # Compute total crop value for each crop
    result_df = yield_df*price_df
    # Compute the total value of the 5 main crops by summing across all crop columns
    result_df['5 Main Crops Value'] = result_df.sum(axis=1)

    crops_production_years[year] = result_df

### Interpolate

In [65]:
crops_production_years = interpolate_missing_years(year_to_df=crops_production_years, col_name='5 Main Crops Value',
                               all_years=all_years, empty_dist_df=empty_dist_df.copy(), extrapolate_trends = False)

### Add '5 Main Crops Value %' column

In [66]:
for year, df in crops_production_years.items():
    df['5 Main Crops Value Per Capita'] = df['5 Main Crops Value']/production_by_year[year]['Population']

Generate and save plots with 5 Main Crops total production value.

In [67]:
# plot_year_df_columns(
#     adm_history_plotter=adm_history_plotter,
#     adm_state_date=reference_date,
#     custom_dist_grouping=d_city_mapping,
#     plots_output_path=plots_output_path,
#     path_suffix = "/Agriculture/5_Crops_Value/",
#     year_df_dict = crops_production_years,
#     col_name = '5 Main Crops Value Per Capita',
#     title = '5 Main Crops Value Per Capita (Current Prices)',
#     export_excel = True,
#     cmap = 'Greens'
# )

## Compute crops yields per ha

In [68]:
# Load the crops area
columns_to_select = ['Wheat', 'Rye', 'Barley', 'Oats', 'Potatoes']
columns_to_select = ['Crops/Area/' + col for col in columns_to_select]
crops_area_data_table_ids = [
    data_table.data_table_id
    for data_table in adm_history_processor.processed_data_metadata.items
    if any(col in columns_to_select for col in data_table.columns.keys())
]
crops_area_dfs = [adm_history_api.load_data_table(data_table_id = crops_data_table_id, version = 'harmonized', custom_grouping=d_city_mapping, custom_grouping_method = 'sum') for crops_data_table_id in crops_area_data_table_ids]
crops_area_year_df = {extract_date_parts(metadata.date)[0]: df for df, metadata, date in crops_area_dfs}
crops_area_years = crops_area_year_df.keys()
crops_area_year_df_clean = copy.deepcopy(empty_year_df_dict)
for year, df in crops_area_year_df.items():
    print(f"df.columns: {df.columns}")
    existing_columns = [col for col in columns_to_select if col in df.columns]
    df = df[existing_columns]
    df.columns = [col.split('/')[2].strip() for col in df.columns]
    crops_area_year_df_clean[year] = df

df.columns: Index(['Crops/Area/Barley', 'Crops/Area/Oats', 'Crops/Area/Potatoes',
       'Crops/Area/Rye', 'Crops/Area/Wheat'],
      dtype='object', name='variable_name')
df.columns: Index(['Crops/Area/Barley', 'Crops/Area/Oats', 'Crops/Area/Potatoes',
       'Crops/Area/Rye', 'Crops/Area/Wheat'],
      dtype='object', name='variable_name')
df.columns: Index(['Crops/Area/Barley', 'Crops/Area/Beans, Broad Beans, and Lentils',
       'Crops/Area/Buckwheat',
       'Crops/Area/Cereal Mixtures for Grain (Barley and Oats)',
       'Crops/Area/Chicory', 'Crops/Area/Clover',
       'Crops/Area/Field Pea, Vetch, and Faba Bean', 'Crops/Area/Flax',
       'Crops/Area/Hemp', 'Crops/Area/Hops', 'Crops/Area/Lupin',
       'Crops/Area/Maize', 'Crops/Area/Millet', 'Crops/Area/Oats',
       'Crops/Area/Other Cereal Mixtures for Grain',
       'Crops/Area/Other Fodder Crops and Mixtures', 'Crops/Area/Peas',
       'Crops/Area/Potatoes', 'Crops/Area/Rye', 'Crops/Area/Serradella',
       'Crops/Area/Sugar Beets', 'Crops/Area/Wheat',
       'Crops/Area/Winter and Spring Rapeseed and Turnip Rape'],
      dtype='object', name='variable_name')
df.columns: Index(['Crops/Area/Barley', 'Crops/Area/Beans, Broad Beans, and Lentils',
       'Crops/Area/Buckwheat', 'Crops/Area/Flax', 'Crops/Area/Hemp',
       'Crops/Area/Hops', 'Crops/Area/Maize', 'Crops/Area/Millet',
       'Crops/Area/Mixtures for Grain/Barley',
       'Crops/Area/Mixtures for Grain/Other mixtures', 'Crops/Area/Oats',
       'Crops/Area/Peas', 'Crops/Area/Potatoes',
       'Crops/Area/Rapeseed and Turnip Rape', 'Crops/Area/Rye',
       'Crops/Area/Sugar Beets', 'Crops/Area/Tabacco', 'Crops/Area/Wheat'],
      dtype='object', name='variable_name')
df.columns: Index(['Crops/Area/Barley', 'Crops/Area/Buckwheat', 'Crops/Area/Millet',
       'Crops/Area/Oats', 'Crops/Area/Potatoes', 'Crops/Area/Rye',
       'Crops/Area/Sugar Beets', 'Crops/Area/Wheat'],
      dtype='object', name='variable_name')
df.columns: Index(['Crops/Area/Barley', 'Crops/Area/Buckwheat', 'Crops/Area/Oats',
       'Crops/Area/Potatoes', 'Crops/Area/Rye', 'Crops/Area/Sugar Beets',
       'Crops/Area/Wheat'],
      dtype='object', name='variable_name')
df.columns: Index(['Crops/Area/Barley', 'Crops/Area/Buckwheat', 'Crops/Area/Maize',
       'Crops/Area/Millet', 'Crops/Area/Oats', 'Crops/Area/Potatoes',
       'Crops/Area/Rye', 'Crops/Area/Sugar Beets', 'Crops/Area/Wheat'],
      dtype='object', name='variable_name')

In [69]:
for crop_name in ['Wheat', 'Rye', 'Barley', 'Oats', 'Potatoes']:
    crops_area_year_df_clean = interpolate_missing_years(year_to_df=crops_area_year_df_clean, col_name=crop_name,
                                all_years=all_years, empty_dist_df=empty_dist_df.copy(), extrapolate_trends = False)

crops_area_excel_path = r"E:\OneDrive\Studia\Studia magisterskie\Masterarbeit - Wirtschaftwissenschaft\Additional computations for the article\crops_area_interpolated_with_index.xlsx"
save_dict_of_dfs_to_excel(crops_area_year_df_clean, crops_area_excel_path)

✅ Saved 15 DataFrames to 'E:\OneDrive\Studia\Studia magisterskie\Masterarbeit - Wirtschaftwissenschaft\Additional computations for the article\crops_area_interpolated_with_index.xlsx'

In [70]:
crops_area_year_df_clean[1926]

,Wheat,Rye,Barley,Oats,Potatoes
District,,,,,
AUGUSTOWSKI,660.000000,18720.000000,2800.000000,10100.000000,7600.000000
BARANOWICKI,793.152387,11388.101558,2839.681386,5581.442724,3720.961816
BIALSKI (BIAŁA KRAKOWSKA),1968.688649,6371.375053,2834.729115,11127.995510,6727.238670
BIALSKI (BIAŁA PODLASKA),3002.915980,32841.703499,5628.871480,14759.092194,17077.001038
BIAŁOSTOCKI,1180.000000,29260.000000,4240.000000,15800.000000,11800.000000
...,...,...,...,...,...
ŚWIĘTOCHŁOWICKI,196.872486,1476.543646,98.436243,1279.671160,1574.979890
ŻNIŃSKI,2476.262989,18898.512577,4254.029131,4025.451582,6986.108018
ŻYDACZOWSKI,4041.914066,5389.218754,2326.281477,6978.844430,5331.061717
ŻYWIECKI,1022.327292,4698.243674,4843.672348,13289.276867,11639.935401
ŻÓŁKIEWSKI,6056.110976,8359.662390,3715.405507,6316.189362,5944.648811

In [71]:
# Find years present in both datasets
common_yields_per_ha_years = sorted(set(crops_size_years) & set(crops_area_years))

for year in common_yields_per_ha_years:
    size_df = crops_size_year_df_clean[year]
    area_df = crops_area_year_df_clean[year]

    # Ensure both dfs have the same columns (crops) and index
    if set(size_df.columns) != set(area_df.columns):
        raise ValueError(f"Crop mismatch in year {year}:\nYield: {size_df.columns}\Area: {area_df.columns}")
    if set(size_df.index) != set(area_df.index):
        missing_in_area_df_index = set(size_df.index) - set(area_df.index)
        missing_in_yield_df_index = set(area_df.index) - set(size_df.index)
        raise ValueError(f"Index mismatch in year {year}:\nMissing in area df: {missing_in_area_df_index}.\nMissing in yield df: {missing_in_yield_df_index}.")

    # Compute total crop yield from ha, avoiding NaNs from 0 division
    with np.errstate(divide='ignore', invalid='ignore'):  # suppress warnings
        result_df = size_df.div(area_df).fillna(0)

    # Rename columns with suffix
    result_df = result_df.rename(columns={col: f"{col}_yields_per_ha" for col in yield_df.columns})

    # Add new columns to the existing df in crops_production_years without replacing it
    crops_production_years[year] = pd.concat([crops_production_years.get(year, pd.DataFrame()), result_df], axis=1)

### Disaggregate regional 11 crop value added from Wroński et al. (2025)

Load regional data from Wronski et al. (2025)

In [72]:
region_total_crops_production = read_economic_csv_input(adm_level='Region', input_csv_path=region_total_crops_production_path)
region_agro_production_costs_per_ha = read_economic_csv_input(adm_level='Region', input_csv_path=region_agro_production_costs_path)
region_total_sown_area = read_economic_csv_input(adm_level='Region', input_csv_path=region_total_sown_area_path)

E:\git_projects\border_harmonization_toolkit\src\administrative_history\utils\helper_functions.py:308: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df = df.applymap(lambda x: x.strip() if isinstance(x, str) else x)
E:\git_projects\border_harmonization_toolkit\src\administrative_history\utils\helper_functions.py:308: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df = df.applymap(lambda x: x.strip() if isinstance(x, str) else x)
E:\git_projects\border_harmonization_toolkit\src\administrative_history\utils\helper_functions.py:308: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df = df.applymap(lambda x: x.strip() if isinstance(x, str) else x)

In [73]:
region_agro_production_costs = region_total_sown_area*region_agro_production_costs_per_ha
dist_area_data_table['Non-Forest Area'] = dist_area_data_table['District Area']-forests_data_table['Total Forest Area']

In [74]:
for year, dist_df in crops_production_years.items():
    dist_production_df = distribute_r_values_to_d(region_df=region_total_crops_production, region_value_col=str(year), dist_df=dist_df, dist_value_col = '5 Main Crops Value', new_col_name='Crops Production', d_to_r=d_to_r)
    dist_costs_df = distribute_r_values_to_d(region_df=region_agro_production_costs, region_value_col=str(year), dist_df=dist_area_data_table, dist_value_col = 'Non-Forest Area', new_col_name='Production Costs', d_to_r=d_to_r)
    production_by_year[year]['Crops Value Added'] = dist_production_df['Crops Production']-dist_costs_df['Production Costs']

### Plot prices

In [75]:
# # Plot VA constant prices
# plot_year_df_columns(
#     adm_history_plotter=adm_history_plotter,
#     adm_state_date=reference_date,
#     custom_dist_grouping=d_city_mapping,
#     plots_output_path=plots_output_path,
#     path_suffix = "/Agriculture/Prices/Wheat/",
#     year_df_dict = crops_prices_year_df_clean,
#     col_name = 'Wheat',
#     title = 'Local Wheat Producer Price (current złoty)',
#     export_excel = True,
#     cmap = 'Oranges'
# )

In [76]:
# # Plot VA constant prices
# plot_year_df_columns(
#     adm_history_plotter=adm_history_plotter,
#     adm_state_date=reference_date,
#     custom_dist_grouping=d_city_mapping,
#     plots_output_path=plots_output_path,
#     path_suffix = "/Agriculture/Prices/Oats/",
#     year_df_dict = crops_prices_year_df_clean,
#     col_name = 'Oats',
#     title = 'Local Oats Producer Price (current złoty)',
#     export_excel = True,
#     cmap = 'Oranges'
# )

In [77]:
# # Plot VA constant prices
# plot_year_df_columns(
#     adm_history_plotter=adm_history_plotter,
#     adm_state_date=reference_date,
#     custom_dist_grouping=d_city_mapping,
#     plots_output_path=plots_output_path,
#     path_suffix = "/Agriculture/Prices/Barley/",
#     year_df_dict = crops_prices_year_df_clean,
#     col_name = 'Barley',
#     title = 'Local Barley Producer Price (current złoty)',
#     export_excel = True,
#     cmap = 'Oranges'
# )

In [78]:
# # Plot VA constant prices
# plot_year_df_columns(
#     adm_history_plotter=adm_history_plotter,
#     adm_state_date=reference_date,
#     custom_dist_grouping=d_city_mapping,
#     plots_output_path=plots_output_path,
#     path_suffix = "/Agriculture/Prices/Potatoes/",
#     year_df_dict = crops_prices_year_df_clean,
#     col_name = 'Potatoes',
#     title = 'Local Potatoes Producer Price (current złoty)',
#     export_excel = True,
#     cmap = 'Oranges'
# )

In [79]:
# # Plot VA constant prices
# plot_year_df_columns(
#     adm_history_plotter=adm_history_plotter,
#     adm_state_date=reference_date,
#     custom_dist_grouping=d_city_mapping,
#     plots_output_path=plots_output_path,
#     path_suffix = "/Agriculture/Prices/Rye/",
#     year_df_dict = crops_prices_year_df_clean,
#     col_name = 'Rye',
#     title = 'Local Rye Producer Price (current złoty)',
#     export_excel = True,
#     cmap = 'Oranges'
# )

## Livestock

### Load Livestock data

In [80]:
# Define the dataset ids to be loaded
livestock_columns_to_select = ['Goats', 'Horned Cattle', 'Horses', 'Pigs', 'Sheep', 'Sheep and Goats']
livestock_columns_to_select = ['Livestock/' + col for col in livestock_columns_to_select]
livestock_data_table_ids = [
    data_table.data_table_id
    for data_table in adm_history_processor.processed_data_metadata.items
    if any(col in livestock_columns_to_select for col in data_table.columns.keys())
]

# Load and process the livestock dfs
livestock_dfs = [adm_history_api.load_data_table(data_table_id = livestock_data_table_id, version = 'harmonized', custom_grouping=d_city_mapping, custom_grouping_method = 'sum') for livestock_data_table_id in livestock_data_table_ids]
livestock_year_df_dict = {extract_date_parts(metadata.date)[0]: df for df, metadata, date in livestock_dfs}
# Add Livestock_Units column
for year, df in livestock_year_df_dict.items():
    horse_units = df['Livestock/Horses']
    cow_units = df['Livestock/Horned Cattle']
    pig_units = df['Livestock/Pigs'] / 4

    if 'Livestock/Sheep and Goats' in df.columns:
        sheep_goat_units = df['Livestock/Sheep and Goats'] / 10
        livestock_units = horse_units + cow_units + pig_units + sheep_goat_units
    else:
        df['Livestock/Sheep and Goats'] = df.get('Livestock/Goats', 0) + df.get('Livestock/Sheep', 0)
        goat_units = df.get('Livestock/Goats', 0) / 10
        sheep_units = df.get('Livestock/Sheep', 0) / 10
        livestock_units = horse_units + cow_units + pig_units + goat_units + sheep_units

    df['Livestock_Units'] = livestock_units

In [81]:
livestock_year_df_dict = interpolate_missing_years(year_to_df=livestock_year_df_dict, col_name='Livestock_Units',
                               all_years = all_years, empty_dist_df=empty_dist_df.copy(), extrapolate_trends = False)
livestock_year_df_dict = interpolate_missing_years(year_to_df=livestock_year_df_dict, col_name='Livestock/Horses',
                               all_years = all_years, empty_dist_df=empty_dist_df.copy(), extrapolate_trends = False)
livestock_year_df_dict = interpolate_missing_years(year_to_df=livestock_year_df_dict, col_name='Livestock/Horned Cattle',
                               all_years = all_years, empty_dist_df=empty_dist_df.copy(), extrapolate_trends = False)
livestock_year_df_dict = interpolate_missing_years(year_to_df=livestock_year_df_dict, col_name='Livestock/Pigs',
                               all_years = all_years, empty_dist_df=empty_dist_df.copy(), extrapolate_trends = False)
livestock_year_df_dict = interpolate_missing_years(year_to_df=livestock_year_df_dict, col_name='Livestock/Sheep and Goats',
                               all_years = all_years, empty_dist_df=empty_dist_df.copy(), extrapolate_trends = False)

In [82]:
for year, df in livestock_year_df_dict.items():
    df['Livestock_Units_per_capita'] = df['Livestock_Units']/production_by_year[year]['Population']
    df['Horses_per_capita'] = df['Livestock/Horses']/production_by_year[year]['Population']

Generate and save plots with total livestock units.

In [83]:
# plot_year_df_columns(
#     adm_history_plotter=adm_history_plotter,
#     adm_state_date=reference_date,
#     custom_dist_grouping=d_city_mapping,
#     plots_output_path=plots_output_path,
#     path_suffix = "/Agriculture/Livestock_Units/",
#     year_df_dict = livestock_year_df_dict,
#     col_name = 'Livestock_Units',
#     title = 'Livestock Units',
#     export_excel = True,
#     legend_min = 0,
#     legend_max = 250000
# )

In [84]:
# plot_year_df_columns(
#     adm_history_plotter=adm_history_plotter,
#     adm_state_date=reference_date,
#     custom_dist_grouping=d_city_mapping,
#     plots_output_path=plots_output_path,
#     path_suffix = "/Agriculture/Livestock_Units_per_capita/",
#     year_df_dict = livestock_year_df_dict,
#     col_name = 'Livestock_Units_per_capita',
#     title = 'Livestock Units (Per Capita)',
#     export_excel = True
# )

### Compute Livestock Value Added

To disaggregate the total animal production, I use the same method as Wronsky et al. (2025) and compute the number of 'livestock units' per district to disaggregate their Livestock VA estimates. I rely on the assumptions by a renowned agricultural economist Dederko who assumed the production value of animals to be roughly proportional to the formula:

1 horse = 1 cow = 4 pigs = 10 sheep = 10 goats.

I compute the number of 'livestock units' for every district as:

No. of livestock units = 1*no_horses + 1*no_cows + (1/4)*no_pigs + (1/10)*no_sheep + (1/10)*no_goats

In [85]:
region_animal_production_va = read_economic_csv_input(adm_level='Region', input_csv_path=region_animal_production_va_path)
for year, dist_df in production_by_year.items():
    animal_production_df = distribute_r_values_to_d(region_df=region_forestry_production_va, region_value_col=str(year), dist_df=livestock_year_df_dict[year], dist_value_col = 'Livestock_Units', new_col_name='Livestock VA', d_to_r=d_to_r)
    production_by_year[year]['Livestock Value Added'] = animal_production_df['Livestock VA']

E:\git_projects\border_harmonization_toolkit\src\administrative_history\utils\helper_functions.py:308: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df = df.applymap(lambda x: x.strip() if isinstance(x, str) else x)

In [86]:
# plot_convergence(
#     year_df_dict=production_by_year,
#     values_column='Livestock Value Added',
#     color_by_district=True,
#     d_to_group=d_to_r_group,
#     group_to_color=r_group_to_color,
#     plots_output_path = plots_output_path,
#     path_suffix = "/Agriculture/Livestock_Units/"
#     )

## Sea Fishing

### Sea Fishing Value Added

The values for sea fishing were provided by GUS from 1931 on. All the values are allocated to the district 'MORSKI'. The values for years 1924-1930 is the value from 1931 extrapolated by Wronski et al. (2025) based on the Pomorskie voivodship value of 5 main crops production in the given year in relation to its value of 5 main crops production in year 1931. Voivosdhip Pomorskie was the only on that had access to the sea.

Inland fishing was added by Ponikowski within his estimations of the Livestock production and it's why I don't add it here.

In [87]:
# Values published by GUS (1931-1938) and extrapolated by Wronski et al. (2025) (1924-1930).
sea_fishing_value = {
    1924: 2_747_607.0,
    1925: 4_081_133.0,
    1926: 5_014_687.0,
    1927: 8_833_781.0,
    1928: 10_921_172.0,
    1929: 7_844_862.0,
    1930: 6_542_626.0,
    1931: 2_393_700.0,
    1932: 2_559_700.0,
    1933: 4_589_400.0,
    1934: 3_991_980.0,
    1935: 3_431_700.0,
    1936: 3_986_000.0,
    1937: 5_127_300.0,
    1938: 7_181_700.0
    }

In [88]:
sea_fishing_df = empty_dist_df.copy()
sea_fishing_df['Sea Fishing'] = 0
for year in all_years:
    sea_fishing_year = sea_fishing_df.copy()
    sea_fishing_year.loc['MORSKI', 'Sea Fishing'] = sea_fishing_value[year]
    production_by_year[year]['Sea Fishing Value Added'] = sea_fishing_year['Sea Fishing']

## Horticulture

### Horticulture Value Added

I follow Wronski et al. (2025) and take 6.87% (Ponikowski's estimate for total horticulture production in 1928 in proportion to his estimate of the total crops production in 1928), and assume that horticulture amounts to additional 6.87% of crops production to every district's crops in a given year.

In [89]:
horticulture_df = empty_dist_df.copy()
horticulture_year_df_dict = {}
for year in crops_production_years.keys():
    production_by_year[year]['Horticulture Value Added'] = production_by_year[year]['Crops Value Added']*0.0687

## Remaining crops

Statistics on other types of crops apart from the 11 main crops were not systematically collected by GUS. I take Bukowski et al. (2025) regional estimates of the yearly value of the 11 crops and disaggregate them with the 5 main crops value.

In [90]:
regions_remaining_crops_production = read_economic_csv_input(adm_level='Region', input_csv_path=regions_remaining_crops_production_path)

E:\git_projects\border_harmonization_toolkit\src\administrative_history\utils\helper_functions.py:308: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df = df.applymap(lambda x: x.strip() if isinstance(x, str) else x)

In [91]:
for year, dist_df in crops_production_years.items():
    dist_va_df = distribute_r_values_to_d(region_df=regions_remaining_crops_production, region_value_col=str(year), dist_df=dist_df, dist_value_col='5 Main Crops Value', new_col_name='Remaining Crops Value Added', d_to_r=d_to_r)
    production_by_year[year]['Remaining Crops Value Added'] = dist_va_df['Remaining Crops Value Added']

In [92]:
# plot_year_df_columns(
#     adm_history_plotter=adm_history_plotter,
#     adm_state_date=reference_date,
#     custom_dist_grouping=d_city_mapping,
#     plots_output_path=plots_output_path,
#     path_suffix = "/Agriculture/Remaining_Crops/",
#     year_df_dict = production_by_year,
#     col_name = 'Remaining Crops Value Added',
#     title = 'Remaining Crops VA',
#     export_excel = True
# )

## Final agriculture production estimation

In [93]:
for year in all_years:
    print(list(production_by_year[year].columns))

['Urban_Population', 'Rural_Population', 'Population', 'Forestry Value Added', 'Crops Value Added', 'Livestock Value Added', 'Sea Fishing Value Added', 'Horticulture Value Added', 'Remaining Crops Value Added']
['Urban_Population', 'Rural_Population', 'Population', 'Forestry Value Added', 'Crops Value Added', 'Livestock Value Added', 'Sea Fishing Value Added', 'Horticulture Value Added', 'Remaining Crops Value Added']
['Urban_Population', 'Rural_Population', 'Population', 'Forestry Value Added', 'Crops Value Added', 'Livestock Value Added', 'Sea Fishing Value Added', 'Horticulture Value Added', 'Remaining Crops Value Added']
['Urban_Population', 'Rural_Population', 'Population', 'Forestry Value Added', 'Crops Value Added', 'Livestock Value Added', 'Sea Fishing Value Added', 'Horticulture Value Added', 'Remaining Crops Value Added']
['Urban_Population', 'Rural_Population', 'Population', 'Forestry Value Added', 'Crops Value Added', 'Livestock Value Added', 'Sea Fishing Value Added', 'Horticulture Value Added', 'Remaining Crops Value Added']
['Urban_Population', 'Rural_Population', 'Population', 'Forestry Value Added', 'Crops Value Added', 'Livestock Value Added', 'Sea Fishing Value Added', 'Horticulture Value Added', 'Remaining Crops Value Added']
['Urban_Population', 'Rural_Population', 'Population', 'Forestry Value Added', 'Crops Value Added', 'Livestock Value Added', 'Sea Fishing Value Added', 'Horticulture Value Added', 'Remaining Crops Value Added']
['Urban_Population', 'Population', 'Rural_Population', 'Forestry Value Added', 'Crops Value Added', 'Livestock Value Added', 'Sea Fishing Value Added', 'Horticulture Value Added', 'Remaining Crops Value Added']
['Urban_Population', 'Rural_Population', 'Population', 'Forestry Value Added', 'Crops Value Added', 'Livestock Value Added', 'Sea Fishing Value Added', 'Horticulture Value Added', 'Remaining Crops Value Added']
['Urban_Population', 'Rural_Population', 'Population', 'Forestry Value Added', 'Crops Value Added', 'Livestock Value Added', 'Sea Fishing Value Added', 'Horticulture Value Added', 'Remaining Crops Value Added']
['Urban_Population', 'Rural_Population', 'Population', 'Forestry Value Added', 'Crops Value Added', 'Livestock Value Added', 'Sea Fishing Value Added', 'Horticulture Value Added', 'Remaining Crops Value Added']
['Urban_Population', 'Rural_Population', 'Population', 'Forestry Value Added', 'Crops Value Added', 'Livestock Value Added', 'Sea Fishing Value Added', 'Horticulture Value Added', 'Remaining Crops Value Added']
['Urban_Population', 'Rural_Population', 'Population', 'Forestry Value Added', 'Crops Value Added', 'Livestock Value Added', 'Sea Fishing Value Added', 'Horticulture Value Added', 'Remaining Crops Value Added']
['Urban_Population', 'Rural_Population', 'Population', 'Forestry Value Added', 'Crops Value Added', 'Livestock Value Added', 'Sea Fishing Value Added', 'Horticulture Value Added', 'Remaining Crops Value Added']
['Urban_Population', 'Rural_Population', 'Population', 'Forestry Value Added', 'Crops Value Added', 'Livestock Value Added', 'Sea Fishing Value Added', 'Horticulture Value Added', 'Remaining Crops Value Added']

In [95]:
# Compute final aggricultural production
for year in all_years:
    production_by_year[year]['Agriculture VA'] = production_by_year[year]['Crops Value Added'] + production_by_year[year]['Livestock Value Added'] + production_by_year[year]['Forestry Value Added'] + production_by_year[year]['Sea Fishing Value Added'] + production_by_year[year]['Horticulture Value Added']
    production_by_year[year]['Agriculture VA Per Capita'] = production_by_year[year]['Agriculture VA']/production_by_year[year]['Population']

# Industry

## Load industry datasets

In [96]:
# Define the dataset ids to be loaded
industry_data_table_ids = [
    data_table.data_table_id
    for data_table in adm_history_processor.processed_data_metadata.items
    if any(col.startswith('Business Permissions/Industry/') for col in data_table.columns.keys())
]

# Load and process the industry dfs
industry_dfs = [adm_history_api.load_data_table(data_table_id = industry_data_table_id, version = 'harmonized', custom_grouping=d_city_mapping, custom_grouping_method = 'sum') for industry_data_table_id in industry_data_table_ids]
industry_permissions_year_df = {extract_date_parts(metadata.date)[0]: df for df, metadata, date in industry_dfs}
# Strip 'Business Permissions/Industry/' prefixes from the column names
for year in [1924, 1925, 1928, 1935]:
    industry_permissions_year_df[year].columns = ['/'.join(col.split('/')[2:]) for col in industry_permissions_year_df[year].columns]
# Strip numbers from the beginning of the 1935 column names
industry_permissions_year_df[1935].columns = [re.sub(r'^\d+\.\s*', '', col) for col in industry_permissions_year_df[1935].columns]

In [97]:
industry_permissions_year_df[1928].loc['BIELSKO']

Category IIIPR        1.0
Category IIIR        14.0
Category IIPR         0.0
Category IIR         13.0
Category IPR          0.0
Category IR           7.0
Category IVPR         6.0
Category IVR         72.0
Category VIIIPR      50.0
Category VIIIR      972.0
Category VIIPR       14.0
Category VIIR       155.0
Category VIPR        10.0
Category VIR         52.0
Category VPR          6.0
Category VR          73.0
Total PR             87.0
Total R            1358.0
Name: BIELSKO, dtype: float64

### Plot the 1935 industry dataset

In [98]:
industry_permissions_year_df[1935].columns

Index(['Number of workers in plants I-VII', 'Plants of All Types/Total',
       'Plants of All Types/I-III', 'Plants of All Types/IV-V',
       'Plants of All Types/VI-VII', 'Plants of All Types/VIII', 'Mining/I-V',
       'Mining/VI-VII', 'Mining/VIII', 'Mineral/I-V', 'Mineral/VI-VII',
       'Mineral/VIII', 'Mineral/brickyards (within others)',
       'Mineral/Concrete plants (within others)',
       'Metal and electrotechnical/I-V', 'Metal and electrotechnical/VI-VII',
       'Metal and electrotechnical/VIII',
       'Metal and electrotechnical/metal production (within others)',
       'Metal and electrotechnical/Backsmithing (within others)',
       'Metal and electrotechnical/Locksmithing, repairs (within others)',
       'Metal and electrotechnical/tinsmithing (within others)',
       'Metal and electrotechnical/Watchmaking and jewelry (within others)',
       'Chemical/I-V', 'Chemical/VI-VII', 'Chemical/VIII',
       'Chemical/Oil mills (within others)', 'Textile/I-V', 'Textile/VI-VII',
       'Textile/VIII', 'Paper/I-V', 'Paper/VI-VII', 'Paper/VIII',
       'Leather/I-V', 'Leather/VI-VII', 'Leather/VIII',
       'Leather/Tanning and white leather (within others)',
       'Leather/Saddlery and harness making (within others)', 'Wood/I-V',
       'Wood/VI-VII', 'Wood/VIII', 'Wood/Sawmills (within others)',
       'Wood/Carpentry (within others)', 'Wood/Wheelwrighting (within others)',
       'Food/I-V', 'Food/VI-VII', 'Food/VIII', 'Food/mills (within others)',
       'Food/Bakeries (within others)', 'Food/Dairies (within others)',
       'Food/Butchery and meat processing (within others)', 'Clothing/I-V',
       'Clothing/VI-VII', 'Clothing/VIII',
       'Clothing/Tailoring and clothing accessories (within others)',
       'Clothing/Shoemaking and boot making (within others)',
       'Clothing/furriery (within others)', 'Printing/I-V', 'Printing/VI-VII',
       'Printing/VIII', 'Printing/Printing houses (within others)',
       'Construction/I-V', 'Construction/VI-VII', 'Construction/VIII',
       'Processing of various materials/VII',
       'Processing of various materials/VIII', 'Power plants/I-V',
       'Power plants/VI-VII', 'Power plants/VIII', 'Services/V-VII',
       'Services/VIII', 'Services/Hairdressing (within others)',
       'Services/Transport (within others)',
       'Horticulture and fisheries/V-VII', 'Horticulture and fisheries/VIII',
       'Other plants/VIII'],
      dtype='object')

In [ ]:
# plot_df_columns_and_export_excel(
#     adm_history_plotter=adm_history_plotter,
#     adm_state_date=reference_date,
#     custom_dist_grouping=d_city_mapping,
#     plots_output_path=plots_output_path,
#     path_suffix = "/Industry/1935/num_workers/true_total/",
#     df = industry_permissions_year_df[1935],
#     col_title_prefix = "",
#     cmap = 'Blues',
#     export_excel = True,
#     columns_subset = ['Number of workers in plants I-VII']
# )

# plot_df_columns_and_export_excel(
#     adm_history_plotter=adm_history_plotter,
#     adm_state_date=reference_date,
#     custom_dist_grouping=d_city_mapping,
#     plots_output_path=plots_output_path,
#     path_suffix = "/Industry/1935/num_plants/",
#     df = industry_permissions_year_df[1935],
#     col_title_prefix = "Number of Plants",
#     cmap = 'OrRd',
#     export_excel = True,
#     columns_subset = [col for col in list(industry_permissions_year_df[1935].columns) if col != 'Number of workers in plants I-VII']
# )

Exporting to E:\OneDrive\Studia\Studia magisterskie\Masterarbeit - Wirtschaftwissenschaft\szacunki_powiatowe_II_RP_from_final_gdp\Industry\1935\num_workers\true_total\data.xlsx

E:\git_projects\border_harmonization_toolkit\src\administrative_history\core\plotter.py:249: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`). Consider using `matplotlib.pyplot.close()`.
  fig, ax = plt.subplots(figsize=(10, 8))

Exporting to E:\OneDrive\Studia\Studia magisterskie\Masterarbeit - Wirtschaftwissenschaft\szacunki_powiatowe_II_RP_from_final_gdp\Industry\1935\num_plants\data.xlsx

## 1924, 1925 and 1928 data preparation

### Compute number of workers per district for years 1924, 1925 and 1928.

In [101]:
# Industry size per category used in the estimations of Wronski et al. (2025)
industry_size_cat = {
    "I": 1250,
    "II": 750.5,
    "III": 350.5,
    "IV": 113.5,
    "V": 19,
    "VI": 8,
    "VII": 6,
    "VIII": 2.5
    }

big_industry_size_cat = {
    "I": 1250,
    "II": 750.5,
    "III": 350.5,
    "IV": 113.5,
    "V": 19,
    "VI": 0,
    "VII": 0,
    "VIII": 0
    }

I_VII_industry_size_cat = {
    "I": 1250,
    "II": 750.5,
    "III": 350.5,
    "IV": 113.5,
    "V": 19,
    "VI": 8,
    "VII": 6,
    "VIII": 0 # Set 0 here
}

r_pr_to_num = {"R": 1, "PR": 0.5}

In [102]:
def parse_kategoria_column(col_name: str):
    match = re.match(r"Category\s+((?:[IVXLCDM]+|V[ab]))(P?R)", col_name.strip())
    if match:
        roman, suffix = match.groups()
        return roman, suffix
    else:
        print(f"Couldn't parse the column {col_name}.")
    return None

def add_total_employment_column(df: pd.DataFrame, cat_to_size, col_name) -> pd.DataFrame:
    df = df.copy()
    total_series = pd.Series(0.0, index=df.index)

    for col in df.columns:
        parsed = parse_kategoria_column(col)
        if parsed:
            roman, suffix = parsed
            if roman in cat_to_size and suffix in r_pr_to_num:
                # Add to total weight column
                weight = cat_to_size[roman] * r_pr_to_num[suffix]
                total_series += df[col].astype(float) * weight
                
            else:
                raise KeyError(f"Missing weight for category: {roman}, {suffix}")
            
    
    df[col_name] = total_series
    return df

In [103]:
total_employment = {}
for year in [1924, 1925, 1928]:
    total_employment[year] = add_total_employment_column(industry_permissions_year_df[year], I_VII_industry_size_cat, "Total Employment I-VII")
    total_employment[year] = add_total_employment_column(total_employment[year], big_industry_size_cat, "Total Employment I-V")
    total_employment[year] = total_employment[year][["Total Employment I-VII", "Total Employment I-V"]]

Couldn't parse the column Total Employment I-VII.
Couldn't parse the column Total Employment I-VII.
Couldn't parse the column Total PR.
Couldn't parse the column Total R.
Couldn't parse the column Total PR.
Couldn't parse the column Total R.
Couldn't parse the column Total Employment I-VII.

### Impute missing 1924 Silesia information (assume same intra-regional proportions as in 1925)

In [104]:
silesia_indices = [dist for dist in all_districts if d_to_r[dist]=='ŚLĄSKIE']

In [105]:
total_employment[1924].loc[silesia_indices]

                 Total Employment I-VII  Total Employment I-V
District
PSZCZYŃSKI                          0.0                   0.0
CIESZYŃSKI                          0.0                   0.0
CHORZÓW                             0.0                   0.0
TARNOGÓRSKI                         0.0                   0.0
RYBNICKI                            0.0                   0.0
LUBLINIECKI                         0.0                   0.0
KATOWICE                            0.0                   0.0
BIELSKO                             0.0                   0.0
ŚWIĘTOCHŁOWICKI                     0.0                   0.0

In [106]:
total_employment = fill_zero_values_by_proportional_scaling(year_to_df=total_employment, col_name="Total Employment I-VII", only_fill_indices=silesia_indices)

Filled missing value for 'BIELSKO' in 1924 using 1925 with scaling factor 1.244
Filled missing value for 'CHORZÓW' in 1924 using 1925 with scaling factor 1.244
Filled missing value for 'CIESZYŃSKI' in 1924 using 1925 with scaling factor 1.244
Filled missing value for 'KATOWICE' in 1924 using 1925 with scaling factor 1.244
Filled missing value for 'LUBLINIECKI' in 1924 using 1925 with scaling factor 1.244
Filled missing value for 'PSZCZYŃSKI' in 1924 using 1925 with scaling factor 1.244
Filled missing value for 'RYBNICKI' in 1924 using 1925 with scaling factor 1.244
Filled missing value for 'TARNOGÓRSKI' in 1924 using 1925 with scaling factor 1.244
Filled missing value for 'ŚWIĘTOCHŁOWICKI' in 1924 using 1925 with scaling factor 1.244

## 1931 Census data preparation

### Load total number of employed in industry from 1931 census

In [107]:
# Load industry_permissions datasets
census_1931_occupations_df, census_1931_occupations_metadata, census_1931_occupations_date = adm_history_api.load_data_table(data_table_id = '1931_occupation_ready_clean', version = 'harmonized', custom_grouping=d_city_mapping, custom_grouping_method = 'sum')

# Store total employment estimations
total_employment[1931] = empty_dist_df.copy()
total_employment[1931]["Total Employment I-V"] = census_1931_occupations_df["Census 1931/Economically Active Population/1-2 Industrial plants: Categories I-V - all"]
total_employment[1931]["Total Employment I-VII"] = census_1931_occupations_df["Census 1931/Economically Active Population/1-2 Industrial plants: Categories I-V - all"] + census_1931_occupations_df["Census 1931/Economically Active Population/1-2 Industrial plants: Categories VI-VII - all"]

## 1935 data preparation

### Compute regional total number of workers per district per industry category for year 1935

In [108]:
# Load data table with regional workers number
regional_workers_num, regional_workers_num_metadata, _ = adm_history_api.load_data_table(data_table_id = "regions_1935_total_num_workers", version = 'harmonized', custom_grouping=warsaw_region_grouping, custom_grouping_method = 'sum')
regional_workers_num.columns = ['/'.join(col.split('/')[1:]) for col in regional_workers_num.columns]
new_col_names = []
for col in regional_workers_num.columns:
    if col.startswith('Industry'): new_col_names.append('/'.join(col.split('/')[1:]))
    else: new_col_names.append(col)
regional_workers_num.columns = new_col_names

In [109]:
# Load data table with regional workers share per industry type and size
regional_workers_share, regional_workers_share_metadata, _ = adm_history_api.load_data_table(data_table_id = "regions_1935_share_workers_by_enterprise_type_size", version = 'harmonized', custom_grouping=warsaw_region_grouping, custom_grouping_method = 'sum')
regional_workers_share.columns = ['/'.join(col.split('/')[2:]) for col in regional_workers_share.columns]

In [110]:
# The regional_workers_share dataframe must be initially cleaned - sum up columns with I-III and IV-V endings
# Sum up I-III and IV-V share categories

def sum_industry_categories(df: pd.DataFrame) -> pd.DataFrame:
    result = pd.DataFrame(index=df.index)

    # Track handled industries
    processed_industries = set()

    for col in df.columns:
        if "/I-III" in col:
            base = col.split("/")[0].strip()
            col_iv_v = f"{base}/IV-V"
            col_i_iii = col
            cols_to_sum = [df[col_i_iii]]
            if col_iv_v in df.columns:
                cols_to_sum.append(df[col_iv_v])
            result[f"{base}/I-V"] = sum(cols_to_sum)
            processed_industries.add(col_i_iii)
            processed_industries.add(col_iv_v)
        elif "/VI-VII" in col:
            result[col] = df[col]
            processed_industries.add(col)

    # Add any columns that were not matched above (e.g. if IV-V exists but I-III doesn’t)
    for col in df.columns:
        if col not in processed_industries:
            result[col] = df[col]

    return result

# Use:
regional_workers_share = sum_industry_categories(regional_workers_share)

In [111]:
# Use two above dataframes to compute number of workers by plant size in each REGION
def compute_workers_by_plant_size(share_df: pd.DataFrame, num_df: pd.DataFrame) -> pd.DataFrame:
    results = pd.DataFrame(index=share_df.index)

    # Regular industry mapping (1:1 correspondence)
    industry_list = [
        'Mining', 'Mineral', 'Chemical', 'Textile', 'Paper', 'Leather',
        'Wood', 'Food', 'Clothing and Toymaking', 'Printing',
        'Construction', 'Power plants and waterworks'
    ]

    for industry in industry_list:
        if industry not in num_df.columns:
            print(f"Warning: '{industry}' not found in worker numbers. Skipping.")
            continue

        total_workers = num_df[industry]

        col_iv = f"{industry}/I-V"
        col_vivii = f"{industry}/VI-VII"

        results[f"{industry}/I-V"] = share_df.get(col_iv, 0) * total_workers
        results[f"{industry}/VI-VII"] = share_df.get(col_vivii, 0) * total_workers

    # Special case: "Metal and electrotechnical"
    industry = "Metal and electrotechnical"
    if industry in num_df.columns:
        total_workers = num_df[industry]

        # Average shares from "Metal" and "Electrotechnical"
        metal_iv = share_df.get("Metal/I-V", 0)
        elec_iv = share_df.get("Electrotechnical/I-V", 0)
        avg_iv = (metal_iv + elec_iv) / 2

        metal_vivii = share_df.get("Metal/VI-VII", 0)
        elec_vivii = share_df.get("Electrotechnical/VI-VII", 0)
        avg_vivii = (metal_vivii + elec_vivii) / 2

        results[f"{industry}/I-V"] = avg_iv * total_workers
        results[f"{industry}/VI-VII"] = avg_vivii * total_workers
    else:
        print("Warning: 'Metal and electrotechnical' not found in worker numbers.")

    return results

workers_by_industry_type_and_size = compute_workers_by_plant_size(share_df=regional_workers_share, num_df = regional_workers_num)

In [112]:
industry_permissions_year_df[1935]

,Number of workers in plants I-VII,Plants of All Types/Total,Plants of All Types/I-III,Plants of All Types/IV-V,Plants of All Types/VI-VII,Plants of All Types/VIII,Mining/I-V,Mining/VI-VII,Mining/VIII,Mineral/I-V,...,Power plants/I-V,Power plants/VI-VII,Power plants/VIII,Services/V-VII,Services/VIII,Services/Hairdressing (within others),Services/Transport (within others),Horticulture and fisheries/V-VII,Horticulture and fisheries/VIII,Other plants/VIII
District,,,,,,,,,,,,,,,,,,,,,
AUGUSTOWSKI,421.0,398.0,1.0,6.0,18.0,373.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,1.0,39.0,18.0,18.0,4.0,5.0,2.0
BARANOWICKI,862.0,904.0,2.0,10.0,82.0,810.0,0.0,2.0,0.0,2.0,...,1.0,1.0,3.0,0.0,93.0,42.0,44.0,0.0,4.0,6.0
BIALSKI (BIAŁA KRAKOWSKA),7844.0,1224.0,7.0,71.0,119.0,1027.0,3.0,4.0,3.0,7.0,...,1.0,1.0,1.0,6.0,91.0,48.0,29.0,0.0,5.0,9.0
BIALSKI (BIAŁA PODLASKA),1123.0,951.0,0.0,12.0,61.0,878.0,0.0,0.0,0.0,3.0,...,0.0,0.0,3.0,0.0,48.0,29.0,12.0,0.0,9.0,1.0
BIAŁOSTOCKI,7084.0,2590.0,8.0,79.0,214.0,2289.0,0.0,0.0,0.0,4.0,...,1.0,2.0,4.0,2.0,182.0,146.0,3.0,1.0,4.0,23.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ŚWIĘTOCHŁOWICKI,29409.0,868.0,17.0,22.0,38.0,791.0,13.0,0.0,1.0,3.0,...,3.0,2.0,2.0,5.0,107.0,73.0,26.0,0.0,4.0,5.0
ŻNIŃSKI,391.0,495.0,1.0,7.0,22.0,465.0,0.0,0.0,0.0,0.0,...,0.0,1.0,2.0,0.0,31.0,19.0,8.0,0.0,16.0,1.0
ŻYDACZOWSKI,212.0,618.0,0.0,7.0,37.0,574.0,0.0,1.0,9.0,3.0,...,0.0,0.0,0.0,0.0,20.0,13.0,4.0,0.0,4.0,3.0
ŻYWIECKI,2594.0,700.0,3.0,19.0,51.0,627.0,4.0,16.0,5.0,0.0,...,0.0,0.0,4.0,0.0,49.0,23.0,21.0,0.0,0.0,3.0
ŻÓŁKIEWSKI,602.0,581.0,0.0,9.0,58.0,514.0,0.0,2.0,0.0,1.0,...,0.0,0.0,0.0,0.0,25.0,10.0,11.0,0.0,0.0,0.0

In [113]:
# Some initial cleaning of the workers_by_industry_type_and_size df to adjust its column names to the industry_permissions_year_df[1935] column names.
rename_map = {
    'Power plants and waterworks/I-V': 'Power plants/I-V',
    'Power plants and waterworks/VI-VII': 'Power plants/VI-VII',
    'Clothing and Toymaking/I-V': 'Clothing/I-V',
    'Clothing and Toymaking/VI-VII': 'Clothing/VI-VII'
}

workers_by_industry_type_and_size.rename(columns=rename_map, inplace=True)

In [114]:
plants_by_main_industry_type = industry_permissions_year_df[1935][['Number of workers in plants I-VII'] + list(workers_by_industry_type_and_size.columns)]

In [115]:
plants_by_main_industry_type.columns

Index(['Number of workers in plants I-VII', 'Mining/I-V', 'Mining/VI-VII',
       'Mineral/I-V', 'Mineral/VI-VII', 'Chemical/I-V', 'Chemical/VI-VII',
       'Textile/I-V', 'Textile/VI-VII', 'Paper/I-V', 'Paper/VI-VII',
       'Leather/I-V', 'Leather/VI-VII', 'Wood/I-V', 'Wood/VI-VII', 'Food/I-V',
       'Food/VI-VII', 'Clothing/I-V', 'Clothing/VI-VII', 'Printing/I-V',
       'Printing/VI-VII', 'Construction/I-V', 'Construction/VI-VII',
       'Power plants/I-V', 'Power plants/VI-VII',
       'Metal and electrotechnical/I-V', 'Metal and electrotechnical/VI-VII'],
      dtype='object')

### Estimate the total number of workers per industry category and size for each DISTRICT for year 1935

For every district we have the information about the total number of workers in the district and the regional total of workers in each industry category for plants of sizes I-V and VI-VII (technically speaking, we have both marginal distributions).
I use the data to estimate the number of workers in each category through a procedure called Iterative Proportional Fitting:
  - I start with estimates for every district industry type and size equal to the regional average number of workers in the industry type and size times the number of industrial permissions in the category.
  - I repeatedly perform the following step until the program converges:
    - I scale the district total sum of workers to fit the known total
    - I scale the regional total sum of workers for industry category-size to fit the known total for this category-size

In [116]:
def estimate_workers_by_industry(plants_by_main_industry_type, workers_by_industry_type_and_size, d_to_r, max_iter=100, tol=1e-5):
    # Identify industry columns (exclude total)
    industry_cols = [col for col in plants_by_main_industry_type.columns if col != 'Number of workers in plants I-VII']

    # Add Region info to plant data
    worker_estimations = plants_by_main_industry_type.copy()
    worker_estimations['Region'] = worker_estimations.index.map(d_to_r)

    results = []

    for region in workers_by_industry_type_and_size.index:
        region_df = worker_estimations[worker_estimations['Region'] == region]
        district_names = region_df.index

        # Get margins
        district_totals = region_df['Number of workers in plants I-VII'].values  # (n_districts,)
        industry_totals = workers_by_industry_type_and_size.loc[region, industry_cols].values  # (n_categories,)

        # Raw counts of plants
        plant_counts = region_df[industry_cols].values  # (n_districts, n_categories)

        # Create a mask of valid cells (i.e. where number of plants > 0)
        mask = plant_counts > 0

        # Avoid division by zero when calculating shares
        row_sums = plant_counts.sum(axis=1, keepdims=True)
        row_sums[row_sums == 0] = 1  # prevent division by zero

        shares = np.where(mask, plant_counts / row_sums, 0)

        # Initialize estimate
        estimate = shares * industry_totals

        for i in range(max_iter):
            prev_estimate = estimate.copy()

            # Row normalization (district totals)
            row_sums = estimate.sum(axis=1)
            row_scaling = np.divide(
                district_totals, row_sums, out=np.ones_like(district_totals), where=row_sums != 0
            )
            estimate = estimate * row_scaling[:, np.newaxis]

            # Column normalization (industry totals)
            col_sums = estimate.sum(axis=0)
            col_scaling = np.divide(
                industry_totals, col_sums, out=np.ones_like(industry_totals), where=col_sums != 0
            )
            estimate = estimate * col_scaling

            # Mask out cells that should remain zero
            estimate = np.where(mask, estimate, 0)

            # Check convergence
            if np.allclose(estimate, prev_estimate, atol=tol):
                break
        
        # Final row normalization to match district totals **exactly**
        row_sums = estimate.sum(axis=1)
        row_scaling = np.divide(
            district_totals, row_sums, out=np.ones_like(district_totals), where=row_sums != 0
        )
        estimate = estimate * row_scaling[:, np.newaxis]
        estimate = np.where(mask, estimate, 0)

        # Save result as DataFrame
        estimate_df = pd.DataFrame(estimate, index=district_names, columns=industry_cols)
        results.append(estimate_df)

    final_estimates = pd.concat(results)
    final_estimates['Estimates: Number of workers in plants I-VII'] = final_estimates[industry_cols].sum(axis=1)
    final_estimates['Number of workers in plants I-VII'] = plants_by_main_industry_type['Number of workers in plants I-VII']
    return final_estimates

In [117]:
worker_estimates = estimate_workers_by_industry(plants_by_main_industry_type, workers_by_industry_type_and_size, d_to_r, max_iter=100, tol=1e-5)
worker_estimates.loc['AUGUSTOWSKI']

Mining/I-V                                        0.000000
Mining/VI-VII                                     0.000000
Mineral/I-V                                       0.000000
Mineral/VI-VII                                    0.000000
Chemical/I-V                                      0.000000
Chemical/VI-VII                                   4.824550
Textile/I-V                                       0.000000
Textile/VI-VII                                    0.000000
Paper/I-V                                         0.000000
Paper/VI-VII                                      0.000000
Leather/I-V                                       0.000000
Leather/VI-VII                                    0.000000
Wood/I-V                                        226.639533
Wood/VI-VII                                      12.636308
Food/I-V                                        156.145003
Food/VI-VII                                      20.754605
Clothing/I-V                                      0.000000
Clothing/VI-VII                                   0.000000
Printing/I-V                                      0.000000
Printing/VI-VII                                   0.000000
Construction/I-V                                  0.000000
Construction/VI-VII                               0.000000
Power plants/I-V                                  0.000000
Power plants/VI-VII                               0.000000
Metal and electrotechnical/I-V                    0.000000
Metal and electrotechnical/VI-VII                 0.000000
Estimates: Number of workers in plants I-VII    421.000000
Number of workers in plants I-VII               421.000000
Name: AUGUSTOWSKI, dtype: float64

In [118]:
# plot_df_columns_and_export_excel(
#     adm_history_plotter=adm_history_plotter,     adm_state_date=reference_date,
#     custom_dist_grouping=d_city_mapping,
#     plots_output_path=plots_output_path,
#     path_suffix = "/Industry/1935/num_workers/estimated_by_industry_cat/total/",
#     df = worker_estimates,
#     col_title_prefix = "",
#     cmap = 'Blues',
#     export_excel = True,
#     columns_subset = [col for col in worker_estimates.columns if col != 'Number of workers in plants I-VII']
# )

Exporting to E:\OneDrive\Studia\Studia magisterskie\Masterarbeit - Wirtschaftwissenschaft\szacunki_powiatowe_II_RP_from_final_gdp\Industry\1935\num_workers\estimated_by_industry_cat\total\data.xlsx

In [119]:
worker_estimates_per_capita = worker_estimates.div(production_by_year[year]['Population'], axis=0)
worker_estimates_per_capita.rename(columns = {col: f"{col} (Per Capita)" for col in worker_estimates.columns}, inplace = True)

In [120]:
# plot_df_columns_and_export_excel(
#     adm_history_plotter=adm_history_plotter,
#     adm_state_date=reference_date,
#     custom_dist_grouping=d_city_mapping,
#     plots_output_path=plots_output_path,
#     path_suffix = "/Industry/1935/num_workers/estimated_by_industry_cat/per_capita/",
#     df = worker_estimates_per_capita,
#     col_title_prefix = "",
#     cmap = 'Blues',
#     export_excel = True,
#     columns_subset = [col for col in worker_estimates_per_capita.columns if col != 'Number of workers in plants I-VII']
# )

Exporting to E:\OneDrive\Studia\Studia magisterskie\Masterarbeit - Wirtschaftwissenschaft\szacunki_powiatowe_II_RP_from_final_gdp\Industry\1935\num_workers\estimated_by_industry_cat\per_capita\data.xlsx

In [121]:
total_employment[1935] = empty_dist_df.copy()
total_employment[1935]["Total Employment I-VII"] = worker_estimates['Number of workers in plants I-VII']

## Esimate employment for missing years between 1924 and 1936.

In [122]:
total_employment = interpolate_missing_years(year_to_df=total_employment, col_name="Total Employment I-VII",
                               all_years=all_years, empty_dist_df=empty_dist_df.copy(), extrapolate_trends = False)

## Plot employment data

In [123]:
for year in total_employment.keys():
    total_employment[year]["Total Employment I-VII (Per Capita)"] = total_employment[year]["Total Employment I-VII"]/production_by_year[year]['Population']
    total_employment[year]["Log of Total Employment I-VII"] = np.log(total_employment[year]["Total Employment I-VII"])
    total_employment[year]["Log of Total Employment I-VII (Per Capita)"] = np.log(total_employment[year]["Total Employment I-VII (Per Capita)"])

c:\Users\janek\miniconda3\Lib\site-packages\pandas\core\arraylike.py:399: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
c:\Users\janek\miniconda3\Lib\site-packages\pandas\core\arraylike.py:399: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
c:\Users\janek\miniconda3\Lib\site-packages\pandas\core\arraylike.py:399: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
c:\Users\janek\miniconda3\Lib\site-packages\pandas\core\arraylike.py:399: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

In [124]:
# # Plot total employment
# plot_year_df_columns(
#     adm_history_plotter=adm_history_plotter,
#     adm_state_date=reference_date,
#     custom_dist_grouping=d_city_mapping,
#     plots_output_path=plots_output_path,
#     path_suffix = "/Industry/num_workers/",
#     year_df_dict = total_employment,
#     col_name = "Log of Total Employment I-VII",
#     title = 'Logarithm of Total Industry Employment Estimate',
#     cmap = 'Blues',
#     legend_min=5.0,
#     legend_max=11.5,
#     export_excel = True
# )

In [ ]:
# # Plot total employment Per Capita
# plot_year_df_columns(
#     adm_history_plotter=adm_history_plotter,
#     adm_state_date=reference_date,
#     custom_dist_grouping=d_city_mapping,
#     plots_output_path=plots_output_path,
#     path_suffix = "/Industry/num_workers_per_capita/",
#     year_df_dict = total_employment,
#     col_name = "Log of Total Employment I-VII (Per Capita)",
#     title = 'Logarithm of Industry Employment Per Capita Estimate',
#     cmap = 'Blues',
#     legend_min=-7.5,
#     legend_max=-0.8,
#     export_excel = True
# )

## Average District Wage Computation

### Load average wage and number of worked hours per industry data

I estimate the average wage in every district for years 1921-1938 by assuming that the proportion of workers in different industry branches remains constant. I compute the weighted national average of wage in year n (weight is the district proportion of the number of workers in every one of the 13 categories).

In [126]:
hourly_wage_by_industry = pd.read_csv(hourly_wage_by_industry_path, sep=";", decimal=",")
hourly_wage_by_industry.set_index("Industry Sector", inplace=True)
hourly_wage_by_industry = hourly_wage_by_industry[[str(year) for year in range(1924, 1939)]]
hourly_wage_by_industry

,1924,1925,1926,1927,1928,1929,1930,1931,1932,1933,1934,1935,1936,1937,1938
Industry Sector,,,,,,,,,,,,,,,
Mining,0.786791,0.874212,0.974123,1.136476,1.248875,1.394375,1.479250,1.479250,1.370125,1.285250,1.224625,1.200375,1.176125,1.212500,1.248875
Mineral,0.534713,0.594125,0.662025,0.772362,0.848750,0.909375,0.885125,0.727500,0.679000,0.582000,0.545625,0.545625,0.569875,0.594125,0.630500
Chemical,0.832624,0.925137,1.030868,1.202679,1.321625,1.418625,1.370125,1.127625,1.054875,1.018500,0.970000,0.921500,0.921500,0.945750,0.982125
Textile,0.634016,0.704462,0.784972,0.915801,1.006375,1.054875,0.982125,0.909375,0.848750,0.800250,0.800250,0.788125,0.800250,0.836625,0.885125
Paper,0.702765,0.780850,0.870090,1.015105,1.115500,1.212500,1.164000,0.957875,0.897250,0.860875,0.824500,0.800250,0.776000,0.800250,0.824500
Leather,0.878456,0.976063,1.087613,1.268881,1.394375,1.418625,1.370125,1.127625,1.054875,0.970000,0.945750,0.897250,0.885125,0.921500,0.945750
Wood,0.473602,0.526225,0.586365,0.684092,0.751750,0.788125,0.763875,0.630500,0.594125,0.497125,0.460750,0.448625,0.448625,0.472875,0.497125
Food,0.748598,0.831775,0.926835,1.081308,1.188250,1.212500,1.164000,1.018500,0.933625,0.860875,0.836625,0.788125,0.763875,0.788125,0.812375
Clothing,0.549990,0.611100,0.680940,0.794430,0.873000,0.921500,0.860875,0.788125,0.739625,0.691125,0.642625,0.630500,0.618375,0.630500,0.666875
Construction,0.863179,0.959087,1.068698,1.246814,1.370125,1.564125,1.515625,1.442875,1.176125,0.994250,0.945750,0.921500,0.897250,0.909375,0.933625
Printing,1.077064,1.196738,1.333508,1.555759,1.709625,1.733875,1.649000,1.527750,1.442875,1.309500,1.224625,1.176125,1.164000,1.115500,1.127625
Power plants,0.847901,0.942113,1.049783,1.224746,1.345875,1.467125,1.564125,1.564125,1.406500,1.418625,1.406500,1.394375,1.418625,1.418625,1.455000
Metal and electrotechnical,0.740959,0.823287,0.917377,1.070274,1.176125,1.248875,1.224625,1.164000,1.115500,0.982125,0.909375,0.885125,0.897250,0.909375,0.921500

In [127]:
hours_per_employee = pd.read_csv(hours_per_employee_path, sep=";", decimal=",")
hours_per_employee.set_index("Industry Sector", inplace=True)
hours_per_employee = hours_per_employee[[str(year) for year in range(1924, 1939)]]
hours_per_employee

,1924,1925,1926,1927,1928,1929,1930,1931,1932,1933,1934,1935,1936,1937,1938
Industry Sector,,,,,,,,,,,,,,,
Mining,2044.874543,1985.315090,2013.306872,2138.043045,2070.140093,2136.686210,1765.593033,1787.065505,1502.804710,1546.858689,1589.723885,1559.645268,1586.688697,1782.361240,1745.081070
Mineral,2194.661176,2130.739005,2160.781179,2294.654251,2221.777422,2220.536128,2200.174233,2205.611937,2107.347494,2074.152483,2097.979912,2100.489456,2103.921055,2097.250384,2087.790869
Chemical,2129.065529,2067.053912,2096.198163,2226.069937,2155.371305,2117.057595,2151.420287,2171.765722,2015.144315,1946.163483,2018.848686,2025.048380,2059.716886,2054.340045,2057.270833
Textile,1963.776830,1906.579446,1933.461101,2053.250360,1988.040373,1951.503276,1882.559079,1946.168888,1840.311043,1795.549729,1829.800267,1856.868382,1853.103347,1851.725516,1893.824675
Paper,2009.811728,1951.273522,1978.785338,2101.382699,2034.644058,1998.994686,1993.377001,2043.220693,1941.971927,1942.899229,1999.523847,2023.751336,2092.860209,2057.727273,2081.757576
Leather,2090.804439,2029.907222,2058.527727,2186.065597,2116.637478,2127.537946,2105.371476,2090.297122,2038.512616,1971.107544,1999.281609,2018.092105,2035.235969,1971.384615,2023.650794
Wood,2104.723061,2043.420447,2072.231480,2200.618379,2130.728072,2151.658159,2104.376247,2092.965399,2043.380486,2037.001837,2063.682373,2056.880418,2094.856708,2083.907157,2072.485876
Food,2129.211978,2067.196095,2096.342350,2226.223058,2155.519563,2165.481910,2163.004440,2079.988144,1915.311307,1712.208511,1779.484588,1802.680508,1843.409981,1889.832215,1902.209857
Clothing,2177.789158,2114.358406,2144.169623,2277.013511,2204.696941,2186.673687,2096.494683,2190.957665,1979.990287,1961.313114,1962.949794,2012.363471,2000.147536,2033.142857,1927.610063
Construction,2246.199397,2180.776114,2211.523781,2348.540655,2273.952427,2300.545359,2304.560495,2306.955108,2096.906848,2023.271404,2100.958324,2093.186955,2150.815071,2183.008475,2158.129252
Printing,2208.354311,2144.033312,2174.262928,2308.971273,2235.639744,2253.920081,2191.415215,2192.401961,2119.205298,2075.321888,2130.212068,2171.053919,2189.780325,2167.192982,2142.195122
Power plants,2267.722469,2201.672300,2201.672300,2201.672300,2201.672300,2206.415064,2034.647215,1964.051808,1730.555802,1804.133005,1875.389169,1880.403002,1913.770725,1981.081198,2029.809152
Metal and electrotechnical,2129.330314,2067.310984,2096.458860,2226.346786,2155.639361,2130.981335,2052.473312,2050.599167,1895.145567,1866.889940,2005.230348,2026.843717,2069.488208,2075.633453,2042.251054

### Compute national average yearly wage per sector

In [128]:
yearly_wage_by_industry = hours_per_employee*hourly_wage_by_industry

### Estimate district industry shares

In [129]:
worker_estimates

,Mining/I-V,Mining/VI-VII,Mineral/I-V,Mineral/VI-VII,Chemical/I-V,Chemical/VI-VII,Textile/I-V,Textile/VI-VII,Paper/I-V,Paper/VI-VII,...,Printing/I-V,Printing/VI-VII,Construction/I-V,Construction/VI-VII,Power plants/I-V,Power plants/VI-VII,Metal and electrotechnical/I-V,Metal and electrotechnical/VI-VII,Estimates: Number of workers in plants I-VII,Number of workers in plants I-VII
District,,,,,,,,,,,,,,,,,,,,,
AUGUSTOWSKI,0.000000,0.000000,0.000000,0.000000,0.000000,4.824550,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,421.0,421.0
BIAŁOSTOCKI,0.000000,0.000000,204.075783,73.923537,157.020707,72.769918,3977.195872,422.222688,23.878992,6.571306,...,0.000000,30.001017,149.141095,5.024102,146.656809,8.602978,12.166120,77.274963,7084.0,7084.0
BIELSKI (BIELSK PODLASKI),0.000000,0.000000,563.588672,54.440518,385.456335,57.418868,0.000000,57.582076,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,21.118695,0.000000,0.000000,2846.0,2846.0
GRODZIEŃSKI,0.000000,0.000000,246.478087,47.617688,0.000000,8.370462,0.000000,0.000000,0.000000,5.291116,...,0.000000,28.987637,0.000000,8.090661,0.000000,0.000000,0.000000,0.000000,2806.0,2806.0
OSTROWSKI (OSTRÓW MAZOWIECKA),0.000000,0.000000,0.000000,11.993737,0.000000,4.216631,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,4.934736,0.000000,644.0,644.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
LUBLINIECKI,0.000000,0.000000,373.823972,30.397057,0.000000,0.000000,237.494845,15.948495,0.000000,14.416725,...,0.000000,0.000000,67.894519,57.948405,0.000000,0.000000,0.000000,42.370866,1626.0,1626.0
PSZCZYŃSKI,4270.954263,15.500175,348.431606,106.246150,853.709536,8.187392,0.000000,0.000000,526.272834,10.078091,...,45.059096,0.000000,47.462037,178.240267,62.445437,0.000000,2801.179598,74.048968,9995.0,9995.0
RYBNICKI,8075.864003,33.495975,1552.985937,120.539262,1383.653734,26.539510,0.000000,0.000000,0.000000,16.334113,...,0.000000,32.739091,538.470230,236.359431,303.626205,8.948032,2017.788874,120.015212,16244.0,16244.0
TARNOGÓRSKI,1610.443820,5.844633,172.439801,36.055902,160.953637,4.630816,0.000000,0.000000,99.220547,5.700201,...,0.000000,5.712566,107.378734,18.329687,0.000000,0.000000,176.039596,16.752936,2638.0,2638.0
ŚWIĘTOCHŁOWICKI,19196.233817,0.000000,271.049006,88.160126,1180.641058,16.984181,0.000000,0.000000,363.905573,0.000000,...,93.471990,20.951655,98.456724,168.066886,388.616264,11.452736,7102.154878,122.887583,29409.0,29409.0

In [130]:
# Create a list of industry types
industry_types = [column.split("/")[0] for column in set(worker_estimates.columns)-{'Estimates: Number of workers in plants I-VII', 'Number of workers in plants I-VII'} if column.split("/")[1] == "I-V"]

# Create a df with industry_types_worker_estimates
industry_types_worker_estimates = empty_dist_df.copy()

# Sum the two columns for each industry type
for ind_type in industry_types:
    col_iv = f"{ind_type}/I-V"
    col_vi = f"{ind_type}/VI-VII"
    industry_types_worker_estimates[ind_type] = worker_estimates[col_iv] + worker_estimates[col_vi]

In [131]:
industry_dist_shares_1935 = industry_types_worker_estimates.div(
    industry_types_worker_estimates.sum(axis=1), axis=0
)
industry_dist_shares_1935

,Chemical,Printing,Mineral,Mining,Textile,Wood,Construction,Paper,Food,Power plants,Clothing,Leather,Metal and electrotechnical
District,,,,,,,,,,,,,
GNIEŹNIEŃSKI,0.000000,0.050248,0.058036,0.000000,0.000000,0.120170,0.054295,0.000000,0.631861,0.000000,0.000000,0.077790,0.007600
DROHOBYCKI,0.192166,0.004994,0.013104,0.536655,0.000000,0.031897,0.021882,0.000000,0.025129,0.118271,0.003819,0.000789,0.051294
KONIŃSKI,0.006662,0.008328,0.156091,0.000000,0.000000,0.149703,0.000000,0.000000,0.638837,0.000000,0.010325,0.006783,0.023271
RAWSKI (RAWA RUSKA),0.000000,0.000000,0.063794,0.022052,0.000000,0.293924,0.000000,0.000000,0.483826,0.000000,0.136405,0.000000,0.000000
GOSTYŃSKI,0.000000,0.000000,0.192097,0.000000,0.017379,0.095841,0.078087,0.000000,0.588407,0.000000,0.007110,0.000000,0.021079
...,...,...,...,...,...,...,...,...,...,...,...,...,...
WOLSZTYŃSKI,0.000000,0.012754,0.331052,0.000000,0.000000,0.098660,0.061245,0.000000,0.496290,0.000000,0.000000,0.000000,0.000000
RADOMSZCZAŃSKI,0.000000,0.009235,0.114283,0.000000,0.000000,0.349860,0.000000,0.025518,0.190640,0.000000,0.042251,0.000000,0.268214
LUBOMELSKI,0.049395,0.000000,0.000000,0.000000,0.000000,0.045471,0.000000,0.000000,0.905134,0.000000,0.000000,0.000000,0.000000
NOWOSĄDECKI,0.010116,0.004925,0.169372,0.300029,0.000000,0.199531,0.009463,0.000000,0.189332,0.001856,0.091073,0.003658,0.020646
MYŚLENICKI,0.000000,0.015013,0.226798,0.000000,0.010380,0.119563,0.028846,0.000000,0.203653,0.000000,0.230009,0.165739,0.000000

### Compute average district hourly wage

In [132]:
average_hourly_wage_year = {}

# Ensure alignment between industry sectors and column names
hourly_wage_by_industry = hourly_wage_by_industry.loc[industry_dist_shares_1935.columns]

for year in hourly_wage_by_industry.columns:
    # Get wage vector for this year (aligned with industry sectors)
    wages = hourly_wage_by_industry[year]  # Series: index = industry sectors

    # Compute weighted average wage per district
    weighted_avg = industry_dist_shares_1935.dot(wages)

    # Store in dictionary (as a DataFrame to keep it consistent)
    average_hourly_wage_year[int(year)] = pd.DataFrame({
        'Average Wage': weighted_avg
    })

In [134]:
# # Plot district hourly wages
# plot_year_df_columns(
#     adm_history_plotter=adm_history_plotter,
#     adm_state_date=reference_date,
#     custom_dist_grouping=d_city_mapping,
#     plots_output_path=plots_output_path,
#     path_suffix = "/Industry/Wages/hourly/",
#     year_df_dict = average_hourly_wage_year,
#     col_name = 'Average Wage',
#     title = 'Average Hourly Wage',
#     cmap = 'Purples',
#     legend_min=0.45,
#     legend_max=1.5,
#     export_excel = True
# )

### Compute average district yearly wage

In [135]:
average_yearly_wage_year = {}

# Ensure alignment between industry sectors and column names
yearly_wage_by_industry = yearly_wage_by_industry.loc[industry_dist_shares_1935.columns]

for year in yearly_wage_by_industry.columns:
    # Get wage vector for this year (aligned with industry sectors)
    wages = yearly_wage_by_industry[year]  # Series: index = industry sectors

    # Compute weighted average wage per district
    weighted_avg = industry_dist_shares_1935.dot(wages)

    # Store in dictionary (as a DataFrame to keep it consistent)
    average_yearly_wage_year[int(year)] = pd.DataFrame({
        'Average Wage': weighted_avg
    })

In [136]:
total_employment[1924][total_employment[1924].index.map(d_to_r)=='ŚLĄSKIE']

,Total Employment I-VII,Total Employment I-V,Total Employment I-VII (Per Capita),Log of Total Employment I-VII,Log of Total Employment I-VII (Per Capita)
District,,,,,
BIELSKO,40340.165260,0.0,0.516330,10.605103,-0.661009
CHORZÓW,15531.932399,0.0,0.158470,9.650653,-1.842190
CIESZYŃSKI,9197.862450,0.0,0.125537,9.126726,-2.075159
KATOWICE,55348.267910,0.0,0.178847,10.921401,-1.721223
LUBLINIECKI,2876.042465,0.0,0.075498,7.964170,-2.583648
PSZCZYŃSKI,21313.129135,0.0,0.155704,9.967079,-1.859799
RYBNICKI,13342.125197,0.0,0.073497,9.498682,-2.610506
TARNOGÓRSKI,6069.295496,0.0,0.098723,8.710998,-2.315441
ŚWIĘTOCHŁOWICKI,25104.607047,0.0,0.136592,10.130807,-1.990758

In [137]:
# # Plot district yearly wages
# plot_year_df_columns(
#     adm_history_plotter=adm_history_plotter,
#     adm_state_date=reference_date,
#     custom_dist_grouping=d_city_mapping,
#     plots_output_path=plots_output_path,
#     path_suffix = "/Industry/Wages/yearly/",
#     year_df_dict = average_yearly_wage_year,
#     col_name = 'Average Wage',
#     title = 'Average Yearly Wage',
#     cmap = 'Purples',
#     legend_min=980,
#     legend_max=3020,
#     export_excel = True
# )

## Disaggregate regional industry VA to districts

### Define regional industry VA disaggregator

For disaggregation of the regional GDP I use the average_yearly_wage*num_workers value for every district for big industry.

In [138]:
industry_disaggregator = {}
for year in all_years:
    industry_disaggregator[year] = empty_dist_df.copy()
    industry_disaggregator[year]["Disaggregator"] = average_yearly_wage_year[year]["Average Wage"]*total_employment[year]["Total Employment I-VII"]

Load regional industry VA estimates

In [139]:
regional_industry_va = read_economic_csv_input(adm_level='Region', input_csv_path=regional_industry_va_path)

E:\git_projects\border_harmonization_toolkit\src\administrative_history\utils\helper_functions.py:308: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df = df.applymap(lambda x: x.strip() if isinstance(x, str) else x)

### Disaggregate regional industry VA estimates

In [140]:
for year, dist_df in industry_disaggregator.items():
    production_estimate = distribute_r_values_to_d(regional_industry_va, str(year), dist_df, "Disaggregator", "Industry VA", d_to_r)
    production_by_year[year]["Industry VA"] = production_estimate["Industry VA"]
    production_by_year[year]["Industry VA Per Capita"] = production_estimate["Industry VA"]/production_by_year[year]['Population']

# Private Services

## Load data on trade permissions

In [141]:
# Define the dataset ids to be loaded
trade_permissions_data_table_ids = [
    data_table.data_table_id
    for data_table in adm_history_processor.processed_data_metadata.items
    if any(col.startswith('Business Permissions/Trade/') for col in data_table.columns.keys())
]

trade_permissions_dfs = [adm_history_api.load_data_table(data_table_id = trade_permissions_data_table_id, version = 'harmonized', custom_grouping=d_city_mapping, custom_grouping_method = 'sum') for trade_permissions_data_table_id in trade_permissions_data_table_ids]
trade_permissions_year_df = {extract_date_parts(metadata.date)[0]: df for df, metadata, date in trade_permissions_dfs if extract_date_parts(metadata.date)[0] in [1924, 1925, 1928]}

# Strip 'Business Permissions/Trade/All Types' prefixes from the column names
for year in [1924, 1925, 1928]:
    trade_permissions_year_df[year].columns = ['/'.join(col.split('/')[3:]) for col in trade_permissions_year_df[year].columns]
    #trade_permissions_year_df[year].columns = [col.split(' ')[-1] for col in trade_permissions_year_df[year].columns]

# Strip numbers from the beginning of the 1935 column names
trade_permissions_1932 = {metadata.data_table_id: df for df, metadata, date in trade_permissions_dfs if extract_date_parts(metadata.date)[0] == 1932}
trade_permissions_1935 = {metadata.data_table_id: df for df, metadata, date in trade_permissions_dfs if extract_date_parts(metadata.date)[0] == 1935}

for key, value in trade_permissions_1932.items():
    value.columns = ['/'.join(col.split('/')[2:]) for col in value.columns]

for key, value in trade_permissions_1935.items():
    value.columns = ['/'.join(col.split('/')[2:]) for col in value.columns]

In [142]:
trade_permissions_year_df[1928].columns

Index(['Category IIIPR', 'Category IIIR', 'Category IIPR', 'Category IIR',
       'Category IPR', 'Category IR', 'Category IVPR', 'Category IVR',
       'Category VaPR', 'Category VaR', 'Category VbPR', 'Category VbR'],
      dtype='object')

## Prepare 1932 total employment data

In [143]:
# Dict mapping "cat_i" to "Category XR"
cat_to_categ = {
    'cat_1': 'I',
    'cat_2': 'II',
    'cat_3': 'III',
    'cat_4': 'IV',
    'cat_5a': 'Va',
    'cat_5b': 'Vb'
    }

trade_permissions_year_df[1932] = empty_dist_df.copy()
for cat, categ in cat_to_categ.items():
    trade_permissions_year_df[1932][f"Category {categ}R"] = trade_permissions_1932[f'1932_trade_permissions_{cat}_ready_clean'][f'All Types/Category {categ}R']

## Estimate the number of employees

### Estimate number of employees per district for 1924, 1925, 1928, and 1932

In [144]:
trade_size_cat = {
    "I": 12,
    "II": 6.5,
    "III": 3,
    "IV": 1.5,
    "Va": 1,
    "Vb": 1
    }

### Estimate n. of employees for 1935

Both correlation, as well as log correlations of estimated total employment and total number of permissions are very high. The very high correlation is very well visible on the scatterplots too.

For year 1935 we don't have the permissions by size, but we estimate simply the total number of permissions and extrapolate the employment estimate for 1925, 1928, and 1932 to 1935.

The direct estimates of employment obtainted by this method may be systematically upwardly biased, because the Great Crisis probably caused the decrease in company size. However, they seem to be fairly appropriate for the purpose of disaggregation.

In [145]:
trade_permissions_year_df[1924]

,Category IIIPR,Category IIIR,Category IIPR,Category IIR,Category IPR,Category IR,Category IVPR,Category IVR,Category VaPR,Category VaR,Category VbPR,Category VbR
District,,,,,,,,,,,,
AUGUSTOWSKI,41.000000,414.000000,5.000000,63.000000,0.0,2.000000,26.000000,57.000000,4.000000,9.000000,6.000000,13.000000
BARANOWICKI,91.899696,907.801228,8.410838,128.106265,0.0,6.252646,120.697925,376.224214,9.387138,19.038198,0.998828,1.258507
BIALSKI (BIAŁA KRAKOWSKA),32.529637,781.116074,3.000000,279.022705,0.0,9.000000,38.794455,629.443912,3.132409,2.044136,1.566205,42.882728
BIALSKI (BIAŁA PODLASKA),39.612685,640.464678,3.004305,76.316777,0.0,5.004305,87.266347,336.754990,6.004305,56.051085,13.750374,42.066075
BIAŁOSTOCKI,129.000000,2256.000000,15.000000,711.000000,2.0,60.000000,141.000000,462.000000,4.000000,6.000000,26.000000,89.000000
...,...,...,...,...,...,...,...,...,...,...,...,...
ŚWIĘTOCHŁOWICKI,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
ŻNIŃSKI,20.000630,210.298488,0.007997,102.044314,0.0,1.002990,10.994509,53.049728,0.000000,0.998192,0.009596,14.011476
ŻYDACZOWSKI,7.754272,403.222123,0.969284,29.078518,0.0,0.969284,38.771358,364.450765,0.969284,0.969284,5.815704,38.771358
ŻYWIECKI,27.758263,877.856487,2.276404,226.376243,0.0,5.729374,31.840768,327.292123,0.000000,0.000000,0.000000,4.000000
ŻÓŁKIEWSKI,6.501960,573.101299,0.928851,42.727163,0.0,2.786554,26.936690,404.050349,0.000000,0.000000,0.000000,2.786554

In [146]:
for year, df in trade_permissions_year_df.items():
    pr_columns = [col for col in df.columns if col[-2:]=='PR']
    r_columns = [col for col in df.columns if col[-2:]!='PR' and col[-1] == 'R']
    df = add_total_employment_column(trade_permissions_year_df[year], trade_size_cat, "Total Employment")
    df['Total n. Permissions'] = 1.0*df.loc[:, r_columns].sum(axis=1) + 0.5*df.loc[:, pr_columns].sum(axis=1)
    trade_permissions_year_df[year] = df

In [147]:
def correlations(df, x_col, df_2, y_col):
    log_x_col = np.log1p(df[x_col])
    log_y_col = np.log1p(df_2[y_col])
    corr_log = log_x_col.corr(log_y_col)
    corr = df[x_col].corr(df_2[y_col])
    print(f"Correlation of {x_col} and {y_col} ({year}): {corr}, Correlation of log values: {corr_log}")

def scatterplot_columns(df, x_col, df_2, y_col, title=None, xlabel=None, ylabel=None):
    plt.figure(figsize=(8,6))
    plt.scatter(df[x_col], df_2[y_col], alpha=0.7)
    plt.title(title or f'{y_col} vs {x_col}')
    plt.xlabel(xlabel or x_col)
    plt.ylabel(ylabel or y_col)
    plt.grid(True)
    plt.show()

In [148]:
for year in [1924, 1925, 1928, 1932]:
    df = trade_permissions_year_df[year]
    correlations(df, 'Total Employment', df, 'Total n. Permissions')

Correlation of Total Employment and Total n. Permissions (1924): 0.9931278972872736, Correlation of log values: 0.9951463635048577
Correlation of Total Employment and Total n. Permissions (1925): 0.9952985119026879, Correlation of log values: 0.9798596148547652
Correlation of Total Employment and Total n. Permissions (1928): 0.9948712260264836, Correlation of log values: 0.9808780350705611
Correlation of Total Employment and Total n. Permissions (1932): 0.9949037526236745, Correlation of log values: 0.9795444107587032

In [149]:
scatterplot_columns(trade_permissions_year_df[1932], 'Total Employment', trade_permissions_year_df[1932], 'Total n. Permissions', 
                    title='Permissions vs Estimated Employment')

C:\Users\janek\AppData\Local\Temp\ipykernel_22348\1289029749.py:15: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

In [150]:
trade_permissions_year_df[1935] = empty_dist_df.copy()
trade_permissions_year_df[1935]["Total n. Permissions"] = trade_permissions_1935['1935-trade_permissions_total_ready_clean']['A-K. Commercial establishments total'] + trade_permissions_1935['1935-trade_permissions_no_fixed_location_ready_clean']['A-K. Commercial establishments total']

In [151]:
# Define ad-hoc function to compute average employment to permissions ratio.
def compute_average_emp_to_permission_ratio(trade_permissions_year_df: Dict[int, pd.DataFrame], years: List[int]) -> pd.Series:
    """
    Computes the average employment-to-permission ratio per district across given years,
    ignoring divisions by zero and missing values.
    """

    proportion_list = []

    for year in years:
        df = trade_permissions_year_df[year]
        with np.errstate(divide='ignore', invalid='ignore'):
            proportion = df["Total Employment"] / df["Total n. Permissions"]
            proportion.replace([np.inf, -np.inf], np.nan, inplace=True)
            proportion_list.append(proportion)

    proportions_df = pd.concat(proportion_list, axis=1)
    return proportions_df.mean(axis=1, skipna=True)

In [152]:
# Compute average employment-to-permission ratio for year 1935
avg_ratio = compute_average_emp_to_permission_ratio(
    trade_permissions_year_df,
    years=[1925, 1928, 1932]
)

# Multiply by 1935 permissions to estimate employment
trade_permissions_year_df[1935]["Total Employment"] = (
    avg_ratio * trade_permissions_year_df[1935]["Total n. Permissions"]
).fillna(0)

## Extrapolate from 1925 missing 1924 values for Silesia

In [153]:
trade_permissions_year_df = fill_zero_values_by_proportional_scaling(year_to_df=trade_permissions_year_df, col_name="Total Employment", only_fill_indices=silesia_indices)

Filled missing value for 'BIELSKO' in 1924 using 1925 with scaling factor 1.090
Filled missing value for 'CHORZÓW' in 1924 using 1925 with scaling factor 1.090
Filled missing value for 'CIESZYŃSKI' in 1924 using 1925 with scaling factor 1.090
Filled missing value for 'KATOWICE' in 1924 using 1925 with scaling factor 1.090
Filled missing value for 'LUBLINIECKI' in 1924 using 1925 with scaling factor 1.090
Filled missing value for 'PSZCZYŃSKI' in 1924 using 1925 with scaling factor 1.090
Filled missing value for 'RYBNICKI' in 1924 using 1925 with scaling factor 1.090
Filled missing value for 'TARNOGÓRSKI' in 1924 using 1925 with scaling factor 1.090
Filled missing value for 'ŚWIĘTOCHŁOWICKI' in 1924 using 1925 with scaling factor 1.090

## Interpolate the number of employees for the missing years

In [154]:
trade_permissions_year_df = interpolate_missing_years(year_to_df=trade_permissions_year_df, col_name="Total Employment",
                               all_years = all_years, empty_dist_df=empty_dist_df.copy(), extrapolate_trends = False)
trade_permissions_year_df = interpolate_missing_years(year_to_df=trade_permissions_year_df, col_name="Total n. Permissions",
                               all_years = all_years, empty_dist_df=empty_dist_df.copy(), extrapolate_trends = False)

### Check 1932 correlation with communication and transport

In [155]:
census_1931_occupations_df

variable_name,Census 1931/Economically Active Population/00 Forestry and hunting,Census 1931/Economically Active Population/08 Horticulture and beekeeping,"Census 1931/Economically Active Population/08-00 Section B. Horticulture, fishing, forestry - all","Census 1931/Economically Active Population/08-00 Section B. Horticulture, fishing, forestry - f","Census 1931/Economically Active Population/08-00 Section B. Horticulture, fishing, forestry - m",Census 1931/Economically Active Population/09 Fishing,Census 1931/Economically Active Population/1-2 Industrial plants: Categories I-V - all,Census 1931/Economically Active Population/1-2 Industrial plants: Categories I-V - f,Census 1931/Economically Active Population/1-2 Industrial plants: Categories I-V - m,Census 1931/Economically Active Population/1-2 Industrial plants: Categories VI-VII - all,...,Census 1931/Economically Active Population/R4 Other branches of Section 4,Census 1931/Economically Active Population/R5 Other branches of Section 5,Census 1931/Economically Active Population/R7 Other branches of Section 7,Census 1931/Economically Active Population/R8 Other branches of Section I,Census 1931/Economically Active Population/Total - all,Census 1931/Economically Active Population/Total - f,Census 1931/Economically Active Population/Total - m,"Census 1931/Economically Active Population/n Section N. Persons with unspecified occupation, delinquent persons, and persons with unknown occupation",Census 1931/Economically Active Population/x Persons living without gainful employment,Census 1931/Economically Active Population/x1 Capitalists and rentiers
District,,,,,,,,,,,,,,,,,,,,,
AUGUSTOWSKI,330.000000,37.000000,450.000000,24.000000,426.000000,83.000000,360.000000,25.00000,335.000000,64.000000,...,36.000000,35.000000,39.000000,0.0,6774.000000,1928.000000,4846.000000,144.000000,433.000000,0.0
BARANOWICKI,224.000000,0.000000,407.000000,73.000000,334.000000,0.000000,173.000000,9.00000,164.000000,273.000000,...,49.000000,140.000000,120.000000,0.0,14824.000000,4438.000000,10386.000000,787.000000,1135.000000,0.0
BIALSKI (BIAŁA KRAKOWSKA),197.000000,0.000000,318.000000,22.000000,296.000000,0.000000,15501.000000,4116.00000,11385.000000,1161.000000,...,105.000000,334.000000,180.000000,0.0,42545.000000,13540.000000,29005.000000,420.000000,2270.000000,0.0
BIALSKI (BIAŁA PODLASKA),143.848389,306.395271,469.179975,35.859848,433.320127,18.936316,926.312353,89.47741,836.834943,163.878235,...,123.513905,157.472906,92.711847,0.0,13139.647938,3550.429399,9589.218539,601.298321,795.595447,0.0
BIAŁOSTOCKI,456.000000,0.000000,739.000000,75.000000,664.000000,0.000000,8002.000000,2489.00000,5513.000000,1588.000000,...,210.000000,324.000000,239.000000,134.0,54260.000000,16588.000000,37672.000000,1091.000000,3503.000000,71.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ŚWIĘTOCHŁOWICKI,0.000000,0.000000,80.000000,20.000000,60.000000,0.000000,40363.000000,2331.00000,38032.000000,778.000000,...,22.000000,388.000000,235.000000,0.0,78372.000000,17077.000000,61295.000000,274.000000,13631.000000,0.0
ŻNIŃSKI,141.000000,0.000000,280.000000,22.000000,258.000000,0.000000,823.000000,46.00000,777.000000,167.000000,...,47.000000,138.000000,26.000000,0.0,6579.000000,1998.000000,4581.000000,43.000000,841.000000,0.0
ŻYDACZOWSKI,101.000000,0.000000,149.000000,18.000000,131.000000,0.000000,121.000000,10.00000,111.000000,49.000000,...,66.000000,54.000000,45.000000,0.0,6554.000000,1862.000000,4692.000000,48.000000,848.000000,0.0
ŻYWIECKI,731.000000,0.000000,784.000000,45.000000,739.000000,0.000000,6357.000000,1094.00000,5263.000000,538.000000,...,219.000000,321.000000,54.000000,0.0,20181.000000,5246.000000,14935.000000,92.000000,1565.000000,0.0
ŻÓŁKIEWSKI,126.000000,0.000000,186.000000,21.000000,165.000000,0.000000,437.000000,83.00000,354.000000,185.000000,...,71.000000,2.000000,49.000000,0.0,8728.000000,2637.000000,6091.000000,184.000000,637.000000,0.0

In [156]:
correlations(trade_permissions_year_df[1932], 'Total Employment', census_1931_occupations_df, 'Census 1931/Economically Active Population/9 Domestic service')

Correlation of Total Employment and Census 1931/Economically Active Population/9 Domestic service (1932): 0.9665900657689507, Correlation of log values: 0.899494609867664

In [157]:
scatterplot_columns(trade_permissions_year_df[1932], 'Total Employment', census_1931_occupations_df, 'Census 1931/Economically Active Population/9 Domestic service', 
                    title='Estimated Employment in Trade vs. Census Domestic Service Employment')

C:\Users\janek\AppData\Local\Temp\ipykernel_22348\1289029749.py:15: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

## Prepare 1932 services mix value data

In [158]:
private_services_types = ['trade', 'trans_com', 'education', 'hygiene', 'lit_sci_culture', 'justice', 'health', 'religion', 'domestic_service', 'finance', 'immobility', 'other']

service_type_1932_dict = {
    'All Types': 'other',
    '1. All types of professional purchasing (total)': 'trade',
    'a. Professional purchasing (agricultural products)': 'other',
    'b. Professional purchasing (livestock)': 'other',
    'c. Professional purchasing (plant and animal products)': 'other',
    '2. Food and colonial goods (exclusively)': 'trade',
    '3. Food products along with non-food items (excluding wine and spirits)': 'trade',
    '4. Meat, fats, and meat products (exclusively)': 'trade',
    '5. Catering establishments with and without alcohol': 'trade',
    '6. Wine, spirits, and beer (possibly with food and colonial goods)': 'trade',
    '7. Tobacco monopoly products': 'trade',
    '8. Textiles': 'trade',
    '9. Textiles with clothing, haberdashery, garments, and footwear': 'trade',
    '10. Ready-made clothing and haberdashery': 'trade',
    '11. Garments, garment parts, furs, and fur products': 'trade',
    '12. Footwear': 'trade',
    '13. Footwear with leather and shoemaking accessories': 'trade',
    '14. All types of leather and leather products (excluding footwear)': 'trade',
    '15. Machinery, tools, and technical goods (excluding agricultural)': 'trade',
    '16. Building materials and fuels': 'trade',
    '17. Furniture and all wooden products': 'trade',
    '18. Iron, ironware, enameled and aluminum goods (possibly with other goods)': 'trade',
    '19. Kitchenware, porcelain, faience, glassware, window panes, and mirrors': 'trade',
    '20. Soap, candles, paints, gasoline, kerosene, mineral oils, lubricants (soap shops)': 'trade',
    '21. Musical, optical, surgical instruments, photographic equipment and accessories': 'trade',
    '22. Watchmaking, jewelry, and silver-plated products': 'trade',
    '23. Electrical equipment, radio equipment, and all lighting accessories': 'trade',
    '24. Pharmacies': 'health',
    '25. Pharmaceutical warehouses, perfumeries, and cosmetic shops': 'hygiene',
    '26. Rubber goods, oilcloth, linoleum, galoshes, tarpaulins, tires, inner tubes, etc.': 'trade',
    '27. Bookstores, stationery, and paper products (possibly with other goods)': 'lit_sci_culture',
    '28. Agricultural machinery, tools, and goods': 'trade',
    '29. Agricultural-commercial syndicates and cooperatives': 'other',
    '30. Banks, exchange offices, and other short- and long-term credit institutions': 'finance',
    '31. Forwarding, transport, and communication enterprises': 'trans_com',
    '32. Other service enterprises (reading rooms, clinics, laundries, bathhouses, garages, dance halls, etc.)': 'other',
    '33. Hotels, boarding houses, furnished rooms, lodging houses': 'immobility',
    '34. Theaters, cinemas, and other performances': 'lit_sci_culture',
    '35. Insurance companies': 'finance',
    '36. Offices: commission, trade brokerage, advertising, legal advice, agency, technical, etc.': 'justice',
    '37. Other enterprises not listed above': 'other',
    '38. Cards with no industry branch specified': 'other',
    'ZP. Industrial activities': 'other'
}

In [159]:
cat_to_categ

{'cat_1': 'I',
 'cat_2': 'II',
 'cat_3': 'III',
 'cat_4': 'IV',
 'cat_5a': 'Va',
 'cat_5b': 'Vb'}

In [160]:
trade_permissions_1932[f'1932_trade_permissions_{cat}_ready_clean'].columns

Index(['1. All types of professional purchasing (total)/Category VbR',
       '10. Ready-made clothing and haberdashery/Category VbR',
       '11. Garments, garment parts, furs, and fur products/Category VbR',
       '12. Footwear/Category VbR',
       '13. Footwear with leather and shoemaking accessories/Category VbR',
       '14. All types of leather and leather products (excluding footwear)/Category VbR',
       '15. Machinery, tools, and technical goods (excluding agricultural)/Category VbR',
       '16. Building materials and fuels/Category VbR',
       '17. Furniture and all wooden products/Category VbR',
       '18. Iron, ironware, enameled and aluminum goods (possibly with other goods)/Category VbR',
       '19. Kitchenware, porcelain, faience, glassware, window panes, and mirrors/Category VbR',
       '2. Food and colonial goods (exclusively)/Category VbR',
       '20. Soap, candles, paints, gasoline, kerosene, mineral oils, lubricants (soap shops)/Category VbR',
       '21. Musical, optical, surgical instruments, photographic equipment and accessories/Category VbR',
       '22. Watchmaking, jewelry, and silver-plated products/Category VbR',
       '23. Electrical equipment, radio equipment, and all lighting accessories/Category VbR',
       '24. Pharmacies/Category VbR',
       '25. Pharmaceutical warehouses, perfumeries, and cosmetic shops/Category VbR',
       '26. Rubber goods, oilcloth, linoleum, galoshes, tarpaulins, tires, inner tubes, etc./Category VbR',
       '27. Bookstores, stationery, and paper products (possibly with other goods)/Category VbR',
       '28. Agricultural machinery, tools, and goods/Category VbR',
       '29. Agricultural-commercial syndicates and cooperatives/Category VbR',
       '3. Food products along with non-food items (excluding wine and spirits)/Category VbR',
       '30. Banks, exchange offices, and other short- and long-term credit institutions/Category VbR',
       '31. Forwarding, transport, and communication enterprises/Category VbR',
       '32. Other service enterprises (reading rooms, clinics, laundries, bathhouses, garages, dance halls, etc.)/Category VbR',
       '33. Hotels, boarding houses, furnished rooms, lodging houses/Category VbR',
       '34. Theaters, cinemas, and other performances/Category VbR',
       '35. Insurance companies/Category VbR',
       '36. Offices: commission, trade brokerage, advertising, legal advice, agency, technical, etc./Category VbR',
       '37. Other enterprises not listed above/Category VbR',
       '38. Cards with no industry branch specified/Category VbR',
       '4. Meat, fats, and meat products (exclusively)/Category VbR',
       '5. Catering establishments with and without alcohol/Category VbR',
       '6. Wine, spirits, and beer (possibly with food and colonial goods)/Category VbR',
       '7. Tobacco monopoly products/Category VbR', '8. Textiles/Category VbR',
       '9. Textiles with clothing, haberdashery, garments, and footwear/Category VbR',
       'All Types/Category VbR', 'ZP. Industrial activities/Category VbR',
       'a. Professional purchasing (agricultural products)/Category VbR',
       'b. Professional purchasing (livestock)/Category VbR',
       'c. Professional purchasing (plant and animal products)/Category VbR'],
      dtype='object')

In [161]:
census_1931_occupations_df.columns

Index(['Census 1931/Economically Active Population/00 Forestry and hunting',
       'Census 1931/Economically Active Population/08 Horticulture and beekeeping',
       'Census 1931/Economically Active Population/08-00 Section B. Horticulture, fishing, forestry - all',
       'Census 1931/Economically Active Population/08-00 Section B. Horticulture, fishing, forestry - f',
       'Census 1931/Economically Active Population/08-00 Section B. Horticulture, fishing, forestry - m',
       'Census 1931/Economically Active Population/09 Fishing',
       'Census 1931/Economically Active Population/1-2 Industrial plants: Categories I-V - all',
       'Census 1931/Economically Active Population/1-2 Industrial plants: Categories I-V - f',
       'Census 1931/Economically Active Population/1-2 Industrial plants: Categories I-V - m',
       'Census 1931/Economically Active Population/1-2 Industrial plants: Categories VI-VII - all',
       ...
       'Census 1931/Economically Active Population/R4 Other branches of Section 4',
       'Census 1931/Economically Active Population/R5 Other branches of Section 5',
       'Census 1931/Economically Active Population/R7 Other branches of Section 7',
       'Census 1931/Economically Active Population/R8 Other branches of Section I',
       'Census 1931/Economically Active Population/Total - all',
       'Census 1931/Economically Active Population/Total - f',
       'Census 1931/Economically Active Population/Total - m',
       'Census 1931/Economically Active Population/n Section N. Persons with unspecified occupation, delinquent persons, and persons with unknown occupation',
       'Census 1931/Economically Active Population/x Persons living without gainful employment',
       'Census 1931/Economically Active Population/x1 Capitalists and rentiers'],
      dtype='object', name='variable_name', length=273)

In [162]:
private_services_1932_dist_total_type_share = empty_dist_df.copy()
# Fill in private_services_1932_dist_total_type_share with total employment indicators
for cat, categ in cat_to_categ.items():
    cat_multiplier = trade_size_cat[categ]
    for col_name in trade_permissions_1932[f'1932_trade_permissions_{cat}_ready_clean'].columns:
        categ_type = col_name.split("/")[0]#.split(" ")[1]
        if service_type_1932_dict[categ_type] in private_services_1932_dist_total_type_share.columns:
            private_services_1932_dist_total_type_share[service_type_1932_dict[categ_type]] += cat_multiplier*trade_permissions_1932[f'1932_trade_permissions_{cat}_ready_clean'][col_name]
        else:
            private_services_1932_dist_total_type_share[service_type_1932_dict[categ_type]] = cat_multiplier*trade_permissions_1932[f'1932_trade_permissions_{cat}_ready_clean'][col_name]

# Fill in missing private services shares indicators: education, religion, domestic_service

private_services_1932_dist_total_type_share['education'] = private_services_1932_dist_total_type_share['trade']
private_services_1932_dist_total_type_share['religion'] = private_services_1932_dist_total_type_share['trade']
private_services_1932_dist_total_type_share['domestic_service'] = census_1931_occupations_df['Census 1931/Economically Active Population/9 Domestic service']

# Create private services shares dict for each year based on the average industry wages
private_services_by_year = copy.deepcopy(empty_year_df_dict)
for year, df in private_services_by_year.items():
    df = private_services_1932_dist_total_type_share.mul(
        average_hourly_wage_year[year]['Average Wage'],
        axis=0
    )
    df_rename_cols_dict = {col: f"{col}_share" for col in df.columns}
    df = df.rename(columns = df_rename_cols_dict)
    df = df.div(df.sum(axis=0), axis=1)
    private_services_by_year[year] = df

## Disaggregate regional private services VA to districts

### Define regional private services VA disaggregator

In [163]:
private_services_weights = {}
for year in trade_permissions_year_df.keys():
    print(year)
    private_services_weights[year] = empty_dist_df.copy()
    private_services_weights[year]['Weight'] = trade_permissions_year_df[year]['Total Employment']*average_hourly_wage_year[year]['Average Wage']

1924
1925
1928
1932
1935
1926
1927
1929
1930
1931
1933
1934
1936
1937
1938

### Load regional private services VA estimates from Wroński et al. (2025)

In [164]:
regional_private_services_va = {}
for service_type, path in regional_private_paths.items():
    regional_private_services_va[service_type] = read_economic_csv_input(adm_level='Region', input_csv_path=path)
    regional_private_services_va[service_type] = regional_private_services_va[service_type].drop('M. ST. WARSZAWA')

E:\git_projects\border_harmonization_toolkit\src\administrative_history\utils\helper_functions.py:308: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df = df.applymap(lambda x: x.strip() if isinstance(x, str) else x)
E:\git_projects\border_harmonization_toolkit\src\administrative_history\utils\helper_functions.py:308: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df = df.applymap(lambda x: x.strip() if isinstance(x, str) else x)
E:\git_projects\border_harmonization_toolkit\src\administrative_history\utils\helper_functions.py:308: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df = df.applymap(lambda x: x.strip() if isinstance(x, str) else x)
E:\git_projects\border_harmonization_toolkit\src\administrative_history\utils\helper_functions.py:308: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df = df.applymap(lambda x: x.strip() if isinstance(x, str) else x)
E:\git_projects\border_harmonization_toolkit\src\administrative_history\utils\helper_functions.py:308: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df = df.applymap(lambda x: x.strip() if isinstance(x, str) else x)
E:\git_projects\border_harmonization_toolkit\src\administrative_history\utils\helper_functions.py:308: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df = df.applymap(lambda x: x.strip() if isinstance(x, str) else x)
E:\git_projects\border_harmonization_toolkit\src\administrative_history\utils\helper_functions.py:308: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df = df.applymap(lambda x: x.strip() if isinstance(x, str) else x)
E:\git_projects\border_harmonization_toolkit\src\administrative_history\utils\helper_functions.py:308: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df = df.applymap(lambda x: x.strip() if isinstance(x, str) else x)
E:\git_projects\border_harmonization_toolkit\src\administrative_history\utils\helper_functions.py:308: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df = df.applymap(lambda x: x.strip() if isinstance(x, str) else x)
E:\git_projects\border_harmonization_toolkit\src\administrative_history\utils\helper_functions.py:308: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df = df.applymap(lambda x: x.strip() if isinstance(x, str) else x)
E:\git_projects\border_harmonization_toolkit\src\administrative_history\utils\helper_functions.py:308: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df = df.applymap(lambda x: x.strip() if isinstance(x, str) else x)

### Disaggregate

In [165]:
private_services_columns = [f"Private Services ({service_type}) VA" for service_type in regional_private_services_va.keys()]
for year, dist_df in private_services_by_year.items():
    # Distribute each service according to its weight in the given year
    for service_type in regional_private_services_va.keys():
        production_estimate = distribute_r_values_to_d(regional_private_services_va[service_type], str(year), dist_df, f"{service_type}_share", f"Private Services ({service_type}) VA", d_to_r)
        production_by_year[year][f"Private Services ({service_type}) VA"] = production_estimate[f"Private Services ({service_type}) VA"]

    # Sum up all services and compute total Private Services VA
    production_by_year[year]["Private Services VA"] = production_by_year[year][private_services_columns].sum(axis=1)
    production_by_year[year]["Private Services VA Per Capita"] = production_by_year[year]["Private Services VA"]/production_by_year[year]['Population']

### Plot

In [166]:
# # Plot Private Services VA Per Capita
# plot_year_df_columns(
#     adm_history_plotter=adm_history_plotter,
#     adm_state_date=reference_date,
#     custom_dist_grouping=d_city_mapping,
#     plots_output_path=plots_output_path,
#     path_suffix = "/Services/Private/VA_per_capita/",
#     year_df_dict = production_by_year,
#     col_name = 'Private Services VA Per Capita',
#     title = 'Private Services VA Per Capita',
#     export_excel = True,
#     cmap = 'Blues'
# )

In [167]:
# # Plot Private Services VA Per Capita
# plot_year_df_columns(
#     adm_history_plotter=adm_history_plotter,
#     adm_state_date=reference_date,
#     custom_dist_grouping=d_city_mapping,
#     plots_output_path=plots_output_path,
#     path_suffix = "/Services/Private/VA/",
#     year_df_dict = production_by_year,
#     col_name = 'Private Services VA',
#     title = 'Private Services VA',
#     export_excel = True,
#     cmap = 'Blues'
# )

Plot employment

In [168]:
# Compute employment per capita and logarithms of employment and employment per capita
for year in trade_permissions_year_df.keys():
    trade_permissions_year_df[year]['Total Employment Per Capita'] = trade_permissions_year_df[year]['Total Employment']/production_by_year[year]['Population']
    trade_permissions_year_df[year]['Log of Total Employment Per Capita'] = np.log(trade_permissions_year_df[year]['Total Employment Per Capita'])
    trade_permissions_year_df[year]['Log of Total Employment'] = np.log(trade_permissions_year_df[year]['Total Employment'])

c:\Users\janek\miniconda3\Lib\site-packages\pandas\core\arraylike.py:399: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
c:\Users\janek\miniconda3\Lib\site-packages\pandas\core\arraylike.py:399: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
c:\Users\janek\miniconda3\Lib\site-packages\pandas\core\arraylike.py:399: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
c:\Users\janek\miniconda3\Lib\site-packages\pandas\core\arraylike.py:399: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

In [169]:
# # Plot Private Services VA Per Capita
# plot_year_df_columns(
#     adm_history_plotter=adm_history_plotter,
#     adm_state_date=reference_date,
#     custom_dist_grouping=d_city_mapping,
#     plots_output_path=plots_output_path,
#     path_suffix = "/Services/Private/Employment/",
#     year_df_dict = trade_permissions_year_df,
#     col_name = 'Log of Total Employment',
#     title = 'Logarithm of Employment in Private Services',
#     export_excel = True,
#     legend_min=5.4,
#     legend_max=11.5,
#     cmap = 'Blues'
# )

In [ ]:
# # Plot Private Services VA Per Capita
# plot_year_df_columns(
#     adm_history_plotter=adm_history_plotter,
#     adm_state_date=reference_date,
#     custom_dist_grouping=d_city_mapping,
#     plots_output_path=plots_output_path,
#     path_suffix = "/Services/Private/Employment_per_capita/",
#     year_df_dict = trade_permissions_year_df,
#     col_name = 'Log of Total Employment Per Capita',
#     title = 'Logarithm of Employment Per Capita in Private Services',
#     export_excel = True,
#     legend_min=-6.5,
#     legend_max=-1.5,
#     cmap = 'Blues'
# )

# Public Services

In [171]:
census_1931_occupations_df.columns

Index(['Census 1931/Economically Active Population/00 Forestry and hunting',
       'Census 1931/Economically Active Population/08 Horticulture and beekeeping',
       'Census 1931/Economically Active Population/08-00 Section B. Horticulture, fishing, forestry - all',
       'Census 1931/Economically Active Population/08-00 Section B. Horticulture, fishing, forestry - f',
       'Census 1931/Economically Active Population/08-00 Section B. Horticulture, fishing, forestry - m',
       'Census 1931/Economically Active Population/09 Fishing',
       'Census 1931/Economically Active Population/1-2 Industrial plants: Categories I-V - all',
       'Census 1931/Economically Active Population/1-2 Industrial plants: Categories I-V - f',
       'Census 1931/Economically Active Population/1-2 Industrial plants: Categories I-V - m',
       'Census 1931/Economically Active Population/1-2 Industrial plants: Categories VI-VII - all',
       ...
       'Census 1931/Economically Active Population/R4 Other branches of Section 4',
       'Census 1931/Economically Active Population/R5 Other branches of Section 5',
       'Census 1931/Economically Active Population/R7 Other branches of Section 7',
       'Census 1931/Economically Active Population/R8 Other branches of Section I',
       'Census 1931/Economically Active Population/Total - all',
       'Census 1931/Economically Active Population/Total - f',
       'Census 1931/Economically Active Population/Total - m',
       'Census 1931/Economically Active Population/n Section N. Persons with unspecified occupation, delinquent persons, and persons with unknown occupation',
       'Census 1931/Economically Active Population/x Persons living without gainful employment',
       'Census 1931/Economically Active Population/x1 Capitalists and rentiers'],
      dtype='object', name='variable_name', length=273)

In [172]:
census_1931_occupations_df
census_columns_rename_dict = {
    'Census 1931/Economically Active Population/5 Public service, church, social organizations and institutions': 'Public service, church, social organizations and institutions',
    'Census 1931/Economically Active Population/7 Education and culture': 'Education and culture',
    'Census 1931/Economically Active Population/8 Health care and hygiene, cleaning and social welfare': 'Health care and hygiene, cleaning and social welfare',
    'Census 1931/Economically Active Population/9 Domestic service': 'Domestic service'
}
census_1931_selected = census_1931_occupations_df[census_columns_rename_dict.keys()]

census_1931_selected.rename(columns=census_columns_rename_dict, inplace = True)
census_1931_selected.columns

C:\Users\janek\AppData\Local\Temp\ipykernel_22348\4050267300.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  census_1931_selected.rename(columns=census_columns_rename_dict, inplace = True)

Index(['Public service, church, social organizations and institutions',
       'Education and culture',
       'Health care and hygiene, cleaning and social welfare',
       'Domestic service'],
      dtype='object', name='variable_name')

In [173]:
census_1931_selected_per_capita = census_1931_selected.div(production_by_year[year]['Population'], axis=0)

### Load regional private services VA and employment estimates from Wroński et al. (2025)

In [174]:
regional_public_services_va = read_economic_csv_input(adm_level='Region', input_csv_path=regional_public_services_va_path)
regional_public_services_employment = read_economic_csv_input(adm_level='Region', input_csv_path=regional_public_services_employment_path)

E:\git_projects\border_harmonization_toolkit\src\administrative_history\utils\helper_functions.py:308: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df = df.applymap(lambda x: x.strip() if isinstance(x, str) else x)
E:\git_projects\border_harmonization_toolkit\src\administrative_history\utils\helper_functions.py:308: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df = df.applymap(lambda x: x.strip() if isinstance(x, str) else x)

### Disaggregate

In [175]:
for year in all_years:
    production_estimate = distribute_r_values_to_d(regional_public_services_va, str(year), census_1931_selected_per_capita, 'Public service, church, social organizations and institutions', "Public Services VA", d_to_r)
    production_by_year[year]["Public Services VA"] = production_estimate["Public Services VA"]
    production_by_year[year]["Public Services VA Per Capita"] = production_estimate["Public Services VA"]/production_by_year[year]['Population']

    employment_estimate = distribute_r_values_to_d(regional_public_services_employment, str(year), census_1931_selected_per_capita, 'Public service, church, social organizations and institutions', "Public Services Employment", d_to_r)
    production_by_year[year]["Public Services Employment"] = employment_estimate["Public Services Employment"]

### Plot

In [ ]:
# # Plot Public Services VA Per Capita
# plot_year_df_columns(
#     adm_history_plotter=adm_history_plotter,
#     adm_state_date=reference_date,
#     custom_dist_grouping=d_city_mapping,
#     plots_output_path=plots_output_path,
#     path_suffix = "/Services/Public/VA_per_capita/",
#     year_df_dict = production_by_year,
#     col_name = 'Public Services VA Per Capita',
#     title = 'Public Services VA Per Capita',
#     export_excel = True,
#     cmap = 'Blues'
# )

In [177]:
# # Plot Public Services VA
# plot_year_df_columns(
#     adm_history_plotter=adm_history_plotter,
#     adm_state_date=reference_date,
#     custom_dist_grouping=d_city_mapping,
#     plots_output_path=plots_output_path,
#     path_suffix = "/Services/Public/VA/",
#     year_df_dict = production_by_year,
#     col_name = 'Public Services VA',
#     title = 'Public Services VA',
#     export_excel = True,
#     cmap = 'Blues'
# )

In [ ]:
# # Plot Public Services Employment
# plot_year_df_columns(
#     adm_history_plotter=adm_history_plotter,
#     adm_state_date=reference_date,
#     custom_dist_grouping=d_city_mapping,
#     plots_output_path=plots_output_path,
#     path_suffix = "/Services/Public/Employment/",
#     year_df_dict = production_by_year,
#     col_name = 'Public Services Employment',
#     title = 'Public Services Employment',
#     export_excel = True,
#     cmap = 'Blues'
# )

# Total VA

In [179]:
price_deflator = {
    1924: 1.0,
    1925: 1.16,
    1926: 1.45,
    1927: 1.65,
    1928: 1.65,
    1929: 1.61,
    1930: 1.43,
    1931: 1.25,
    1932: 1.11,
    1933: 1.0,
    1934: 0.93,
    1935: 0.89,
    1936: 0.89,
    1937: 0.98,
    1938: 0.94
 }

In [180]:
for year in all_years:
    production_by_year[year]['VA_current_prices'] = production_by_year[year]['Agriculture VA'] + production_by_year[year]['Industry VA'] + production_by_year[year]['Private Services VA'] + production_by_year[year]['Public Services VA']
    production_by_year[year]['VA_current_prices_per_capita'] = production_by_year[year]['VA_current_prices']/production_by_year[year]['Population']
    
    production_by_year[year]['VA_constant_prices'] = production_by_year[year]['VA_current_prices']/price_deflator[year]
    production_by_year[year]['VA_constant_prices_per_capita'] = production_by_year[year]['VA_constant_prices']/production_by_year[year]['Population']

    production_by_year[year]['Agriculture_VA_constant_prices'] = production_by_year[year]['Agriculture VA']/price_deflator[year]
    production_by_year[year]['Agriculture_VA_constant_prices_per_capita'] = production_by_year[year]['Agriculture_VA_constant_prices']/production_by_year[year]['Population']

    production_by_year[year]['Industry_VA_constant_prices'] = production_by_year[year]['Industry VA']/price_deflator[year]
    production_by_year[year]['Industry_VA_constant_prices_per_capita'] = production_by_year[year]['Industry_VA_constant_prices']/production_by_year[year]['Population']

    production_by_year[year]['Private_Services_VA_constant_prices'] = production_by_year[year]['Private Services VA']/price_deflator[year]
    production_by_year[year]['Private_Services_VA_constant_prices_per_capita'] = production_by_year[year]['Private_Services_VA_constant_prices']/production_by_year[year]['Population']

    production_by_year[year]['Public_Services_VA_constant_prices'] = production_by_year[year]['Public Services VA']/price_deflator[year]
    production_by_year[year]['Public_Services_VA_constant_prices_per_capita'] = production_by_year[year]['Public_Services_VA_constant_prices']/production_by_year[year]['Population']

    production_by_year[year]['Services_VA_constant_prices'] = production_by_year[year]['Public_Services_VA_constant_prices'] + production_by_year[year]['Private_Services_VA_constant_prices']
    production_by_year[year]['Services_VA_constant_prices_per_capita'] = production_by_year[year]['Public_Services_VA_constant_prices_per_capita'] + production_by_year[year]['Private_Services_VA_constant_prices_per_capita']

    production_by_year[year]['VA_agriculture_share'] = 100*(production_by_year[year]['Agriculture VA']/production_by_year[year]['VA_current_prices'])
    production_by_year[year]['VA_industry_share'] = 100*(production_by_year[year]['Industry VA']/production_by_year[year]['VA_current_prices'])
    production_by_year[year]['VA_private_services_share'] = 100*(production_by_year[year]['Private Services VA']/production_by_year[year]['VA_current_prices'])
    production_by_year[year]['VA_public_services_share'] = 100*(production_by_year[year]['Public Services VA']/production_by_year[year]['VA_current_prices'])

## Plot outcomes

### Plot VA maps

In [181]:
# # Plot VA current prices
# plot_year_df_columns(
#     adm_history_plotter=adm_history_plotter,
#     adm_state_date=reference_date,
#     custom_dist_grouping=d_city_mapping,
#     plots_output_path=plots_output_path,
#     path_suffix = "/VA/current/",
#     year_df_dict = production_by_year,
#     col_name = 'VA_current_prices',
#     title = 'VA Current Prices',
#     export_excel = True,
#     cmap = 'Oranges'
# )

In [ ]:
# # Plot VA current prices per capita
# plot_year_df_columns(
#     adm_history_plotter=adm_history_plotter,
#     adm_state_date=reference_date,
#     custom_dist_grouping=d_city_mapping,
#     plots_output_path=plots_output_path,
#     path_suffix = "/VA/current_per_capita/",
#     year_df_dict = production_by_year,
#     col_name = 'VA_current_prices_per_capita',
#     title = 'VA Current Prices Per Capita',
#     export_excel = True,
#     cmap = 'Oranges'
# )

In [183]:
# # Plot VA constant prices
# plot_year_df_columns(
#     adm_history_plotter=adm_history_plotter,
#     adm_state_date=reference_date,
#     custom_dist_grouping=d_city_mapping,
#     plots_output_path=plots_output_path,
#     path_suffix = "/VA/constant/",
#     year_df_dict = production_by_year,
#     col_name = 'VA_constant_prices',
#     title = 'VA Constant Prices',
#     export_excel = True,
#     cmap = 'Oranges'
# )

In [184]:
# # Plot VA constant prices per capita
# plot_year_df_columns(
#     adm_history_plotter=adm_history_plotter,
#     adm_state_date=reference_date,
#     custom_dist_grouping=d_city_mapping,
#     plots_output_path=plots_output_path,
#     path_suffix = "/VA/constant_per_capita/",
#     year_df_dict = production_by_year,
#     col_name = 'VA_constant_prices_per_capita',
#     title = 'Total Value Added Per Capita (1924 złotys)',
#     export_excel = True,
#     cmap = 'Oranges'
# )

## Plot VA growth

In [185]:
va_constant_per_capita_growth=empty_dist_df.copy()
va_constant_per_capita_growth['Growth 1924-1931'] = 100*(production_by_year[1931]['VA_constant_prices_per_capita']-production_by_year[1924]['VA_constant_prices_per_capita'])/production_by_year[1924]['VA_constant_prices_per_capita']
va_constant_per_capita_growth['Growth 1931-1938'] = 100*(production_by_year[1938]['VA_constant_prices_per_capita']-production_by_year[1931]['VA_constant_prices_per_capita'])/production_by_year[1931]['VA_constant_prices_per_capita']
va_constant_per_capita_growth['Growth 1924-1938'] = 100*(production_by_year[1938]['VA_constant_prices_per_capita']-production_by_year[1924]['VA_constant_prices_per_capita'])/production_by_year[1924]['VA_constant_prices_per_capita']

In [186]:
plot_df_columns_and_export_excel(
    adm_history_plotter=adm_history_plotter,
    adm_state_date=reference_date,
    custom_dist_grouping=d_city_mapping,
    plots_output_path=plots_output_path,
    path_suffix = "/VA/constant_per_capita/Growth/",
    df = va_constant_per_capita_growth,
    col_title_prefix = '% of VA Constant Prices Per Capita',
    cmap = 'Reds',
    export_excel = True
)

Exporting to E:\OneDrive\Studia\Studia magisterskie\Masterarbeit - Wirtschaftwissenschaft\szacunki_powiatowe_II_RP_from_final_gdp\VA\constant_per_capita\Growth\data.xlsx

### Plot convergence

Value Added

In [ ]:
# # VA per capita - color by region group
# plot_convergence(
#     year_df_dict=production_by_year,
#     values_column='VA_constant_prices_per_capita',
#     color_by_district=True,
#     d_to_group=d_to_r_group,
#     group_to_color=r_group_to_color,
#     plots_output_path=plots_output_path,
#     path_suffix = "/VA/constant_per_capita/paritions_"
#     )

# # VA per capita - color by big_cities
# plot_convergence(
#     year_df_dict=production_by_year,
#     values_column='VA_constant_prices_per_capita',
#     color_by_district=True,
#     d_to_group=is_big_city,
#     group_to_color=big_cities_to_color,
#     plots_output_path=plots_output_path,
#     path_suffix = "/VA/constant_per_capita/big_cities_"
#     )

Plot saved to E:/OneDrive/Studia/Studia magisterskie/Masterarbeit - Wirtschaftwissenschaft/szacunki_powiatowe_II_RP_from_final_gdp/VA/constant_per_capita/paritions_convergence.png
Plot saved to E:/OneDrive/Studia/Studia magisterskie/Masterarbeit - Wirtschaftwissenschaft/szacunki_powiatowe_II_RP_from_final_gdp/VA/constant_per_capita/big_cities_convergence.png

In [ ]:
# # Agriculture VA per capita - color by region group
# plot_convergence(
#     year_df_dict=production_by_year,
#     values_column='Agriculture_VA_constant_prices_per_capita',
#     color_by_district=True,
#     d_to_group=d_to_r_group,
#     group_to_color=r_group_to_color,
#     plots_output_path=plots_output_path,
#     path_suffix = "/VA/disaggregation/agriculture/partitions_"
#     )

# # Agriculture VA per capita - color by big_cities
# plot_convergence(
#     year_df_dict=production_by_year,
#     values_column='Agriculture_VA_constant_prices_per_capita',
#     color_by_district=True,
#     d_to_group=is_big_city,
#     group_to_color=big_cities_to_color,
#     plots_output_path=plots_output_path,
#     path_suffix = "/VA/disaggregation/agriculture/big_cities_"
#     )

Plot saved to E:/OneDrive/Studia/Studia magisterskie/Masterarbeit - Wirtschaftwissenschaft/szacunki_powiatowe_II_RP_from_final_gdp/VA/disaggregation/agriculture/partitions_convergence.png
Plot saved to E:/OneDrive/Studia/Studia magisterskie/Masterarbeit - Wirtschaftwissenschaft/szacunki_powiatowe_II_RP_from_final_gdp/VA/disaggregation/agriculture/big_cities_convergence.png

Industry

In [191]:
# # Industry VA per capita
# plot_convergence(
#     year_df_dict=production_by_year,
#     values_column='Industry_VA_constant_prices_per_capita',
#     color_by_district=True,
#     d_to_group=d_to_r_group,
#     group_to_color=r_group_to_color,
#     plots_output_path=plots_output_path,
#     path_suffix = "/VA/disaggregation/industry/partitions_"
#     )

# # Industry VA per capita
# plot_convergence(
#     year_df_dict=production_by_year,
#     values_column='Industry_VA_constant_prices_per_capita',
#     color_by_district=True,
#     d_to_group=is_big_city,
#     group_to_color=big_cities_to_color,
#     plots_output_path=plots_output_path,
#     path_suffix = "/VA/disaggregation/industry/big_cities_"
#     )

Plot saved to E:/OneDrive/Studia/Studia magisterskie/Masterarbeit - Wirtschaftwissenschaft/szacunki_powiatowe_II_RP_from_final_gdp/VA/disaggregation/industry/partitions_convergence.png
Plot saved to E:/OneDrive/Studia/Studia magisterskie/Masterarbeit - Wirtschaftwissenschaft/szacunki_powiatowe_II_RP_from_final_gdp/VA/disaggregation/industry/big_cities_convergence.png

Private Services

In [ ]:
# # Private Services VA per capita
# plot_convergence(
#     year_df_dict=production_by_year,
#     values_column='Private_Services_VA_constant_prices_per_capita',
#     color_by_district=True,
#     d_to_group=d_to_r_group,
#     group_to_color=r_group_to_color,
#     plots_output_path=plots_output_path,
#     path_suffix = "/VA/disaggregation/private_services/partitions_"
#     )

# # Private Services VA per capita
# plot_convergence(
#     year_df_dict=production_by_year,
#     values_column='Private_Services_VA_constant_prices_per_capita',
#     color_by_district=True,
#     d_to_group=is_big_city,
#     group_to_color=big_cities_to_color,
#     plots_output_path=plots_output_path,
#     path_suffix = "/VA/disaggregation/private_services/big_cities_"
#     )

Plot saved to E:/OneDrive/Studia/Studia magisterskie/Masterarbeit - Wirtschaftwissenschaft/szacunki_powiatowe_II_RP_from_final_gdp/VA/disaggregation/private_services/partitions_convergence.png
Plot saved to E:/OneDrive/Studia/Studia magisterskie/Masterarbeit - Wirtschaftwissenschaft/szacunki_powiatowe_II_RP_from_final_gdp/VA/disaggregation/private_services/big_cities_convergence.png

Public Services

In [193]:
# # Public Services VA per capita
# plot_convergence(
#     year_df_dict=production_by_year,
#     values_column='Public_Services_VA_constant_prices_per_capita',
#     color_by_district=True,
#     d_to_group=d_to_r_group,
#     group_to_color=r_group_to_color,
#     plots_output_path=plots_output_path,
#     path_suffix = "/VA/disaggregation/public_services/partitions_"
#     )

# # Public Services VA per capita
# plot_convergence(
#     year_df_dict=production_by_year,
#     values_column='Public_Services_VA_constant_prices_per_capita',
#     color_by_district=True,
#     d_to_group=is_big_city,
#     group_to_color=big_cities_to_color,
#     plots_output_path=plots_output_path,
#     path_suffix = "/VA/disaggregation/public_services/big_cities_"
#     )

Plot saved to E:/OneDrive/Studia/Studia magisterskie/Masterarbeit - Wirtschaftwissenschaft/szacunki_powiatowe_II_RP_from_final_gdp/VA/disaggregation/public_services/partitions_convergence.png
Plot saved to E:/OneDrive/Studia/Studia magisterskie/Masterarbeit - Wirtschaftwissenschaft/szacunki_powiatowe_II_RP_from_final_gdp/VA/disaggregation/public_services/big_cities_convergence.png

### Plot VA per sector

Agriculture

In [195]:
# # Value Added
# plot_year_df_columns(
#     adm_history_plotter=adm_history_plotter,
#     adm_state_date=reference_date,
#     custom_dist_grouping=d_city_mapping,
#     plots_output_path=plots_output_path,
#     path_suffix = "/Agriculture/VA/",
#     year_df_dict = production_by_year,
#     col_name = 'Agriculture_VA_constant_prices',
#     title = 'Agriculture Value Added (1924 złotys)',
#     cmap = 'Greens',
#     export_excel = True
# )

In [196]:
# # Value Added Per Capita
# plot_year_df_columns(
#     adm_history_plotter=adm_history_plotter,
#     adm_state_date=reference_date,
#     custom_dist_grouping=d_city_mapping,
#     plots_output_path=plots_output_path,
#     path_suffix = "/Agriculture/VA_per_capita/",
#     year_df_dict = production_by_year,
#     col_name = 'Agriculture_VA_constant_prices_per_capita',
#     title = 'Agriculture Value Added Per Capita (1924 złotys)',
#     cmap = 'Greens',
#     export_excel = True
# )

Industry

In [197]:
# # Value Added
# plot_year_df_columns(
#     adm_history_plotter=adm_history_plotter,
#     adm_state_date=reference_date,
#     custom_dist_grouping=d_city_mapping,
#     plots_output_path=plots_output_path,
#     path_suffix = "/Industry/VA/",
#     year_df_dict = production_by_year,
#     col_name = 'Industry_VA_constant_prices',
#     title = 'Industry Value Added (1924 złotys)',
#     cmap = 'Purples',
#     export_excel = True
# )

In [198]:
# # Value Added Per Capita
# plot_year_df_columns(
#     adm_history_plotter=adm_history_plotter,
#     adm_state_date=reference_date,
#     custom_dist_grouping=d_city_mapping,
#     plots_output_path=plots_output_path,
#     path_suffix = "/Industry/VA_per_capita/",
#     year_df_dict = production_by_year,
#     col_name = 'Industry_VA_constant_prices_per_capita',
#     title = 'Industry Value Added Per Capita (1924 złotys)',
#     cmap = 'Purples',
#     export_excel = True
# )

Private and Public Services Together

In [ ]:
# # Value Added
# plot_year_df_columns(
#     adm_history_plotter=adm_history_plotter,
#     adm_state_date=reference_date,
#     custom_dist_grouping=d_city_mapping,
#     plots_output_path=plots_output_path,
#     path_suffix = "/Services/VA/",
#     year_df_dict = production_by_year,
#     col_name = 'Services_VA_constant_prices',
#     title = 'Services Value Added (1924 złotys)',
#     cmap = 'Blues',
#     export_excel = True
# )

In [ ]:
# # Value Added Per Capita
# plot_year_df_columns(
#     adm_history_plotter=adm_history_plotter,
#     adm_state_date=reference_date,
#     custom_dist_grouping=d_city_mapping,
#     plots_output_path=plots_output_path,
#     path_suffix = "/Services/VA_per_capita/",
#     year_df_dict = production_by_year,
#     col_name = 'Services_VA_constant_prices_per_capita',
#     title = 'Services Value Added Per Capita (1924 złotys)',
#     cmap = 'Blues',
#     export_excel = True
# )

### Plot VA shares

In [201]:
# # Plot agriculture VA share
# plot_year_df_columns(
#     adm_history_plotter=adm_history_plotter,
#     adm_state_date=reference_date,
#     custom_dist_grouping=d_city_mapping,
#     plots_output_path=plots_output_path,
#     path_suffix = "/VA/disaggregation/agriculture/",
#     year_df_dict = production_by_year,
#     col_name = 'VA_agriculture_share',
#     title = 'Agriculture Share in VA (%)',
#     export_excel = True,
#     cmap = 'Greens'
# )

In [ ]:
# # Plot industry VA share
# plot_year_df_columns(
#     adm_history_plotter=adm_history_plotter,
#     adm_state_date=reference_date,
#     custom_dist_grouping=d_city_mapping,
#     plots_output_path=plots_output_path,
#     path_suffix = "/VA/disaggregation/industry/",
#     year_df_dict = production_by_year,
#     col_name = 'VA_industry_share',
#     title = 'Industry Share in VA (%)',
#     export_excel = True
# )

In [ ]:
# # Plot private services VA share
# plot_year_df_columns(
#     adm_history_plotter=adm_history_plotter,
#     adm_state_date=reference_date,
#     custom_dist_grouping=d_city_mapping,
#     plots_output_path=plots_output_path,
#     path_suffix = "/VA/disaggregation/private_services/",
#     year_df_dict = production_by_year,
#     col_name = 'VA_private_services_share',
#     title = 'Private Services Share in VA (%)',
#     export_excel = True,
#     cmap = 'Blues'
# )

In [ ]:
# # Plot public services VA share
# plot_year_df_columns(
#     adm_history_plotter=adm_history_plotter,
#     adm_state_date=reference_date,
#     custom_dist_grouping=d_city_mapping,
#     plots_output_path=plots_output_path,
#     path_suffix = "/VA/disaggregation/public_services/",
#     year_df_dict = production_by_year,
#     col_name = 'VA_public_services_share',
#     title = 'Public Services Share in VA (%)',
#     export_excel = True,
#     cmap = 'Blues'
# )

# Analyze the Spatial Convergence

## Convergence of VA per capita

In [241]:
plot_va_growth_scatter(production_by_year, all_years=all_years, save_to_path=plots_output_path+"/Convergence_Analysis/VA_per_capita/va_growth_with_regression.png", d_to_r_group=None, r_group_to_color=None)
plot_va_growth_scatter(production_by_year, all_years=all_years, save_to_path=plots_output_path+"/Convergence_Analysis/VA_per_capita/va_growth_with_regression_r_group.png", d_to_r_group=d_to_r_group, r_group_to_color=r_group_to_color, x_label='Value Added Per Capita in 1924 (1924 złoty)')
plot_va_growth_scatter(production_by_year, all_years=all_years, save_to_path=plots_output_path+"/Convergence_Analysis/VA_per_capita/va_growth_with_regression_big_cities.png", d_to_r_group=is_big_city, r_group_to_color=big_cities_to_color)

📊 Regression summary:

                            OLS Regression Results
==============================================================================
Dep. Variable:                      y   R-squared:                       0.136
Model:                            OLS   Adj. R-squared:                  0.132
Method:                 Least Squares   F-statistic:                     38.43
Date:                Sun, 28 Dec 2025   Prob (F-statistic):           2.39e-09
Time:                        13:24:47   Log-Likelihood:                 629.76
No. Observations:                 247   AIC:                            -1256.
Df Residuals:                     245   BIC:                            -1248.
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.0366      0.002     16.028      0.000       0.032       0.041
x1         -3.033e-05   4.89e-06     -6.199      0.000      -4e-05   -2.07e-05
==============================================================================
Omnibus:                        7.487   Durbin-Watson:                   1.954
Prob(Omnibus):                  0.024   Jarque-Bera (JB):                9.049
Skew:                           0.258   Prob(JB):                       0.0108
Kurtosis:                       3.783   Cond. No.                         882.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
Plot saved to: E:/OneDrive/Studia/Studia magisterskie/Masterarbeit - Wirtschaftwissenschaft/szacunki_powiatowe_II_RP_from_final_gdp/Convergence_Analysis/VA_per_capita/va_growth_with_regression.png
📊 Regression summary:

                            OLS Regression Results
==============================================================================
Dep. Variable:                      y   R-squared:                       0.136
Model:                            OLS   Adj. R-squared:                  0.132
Method:                 Least Squares   F-statistic:                     38.43
Date:                Sun, 28 Dec 2025   Prob (F-statistic):           2.39e-09
Time:                        13:24:49   Log-Likelihood:                 629.76
No. Observations:                 247   AIC:                            -1256.
Df Residuals:                     245   BIC:                            -1248.
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.0366      0.002     16.028      0.000       0.032       0.041
x1         -3.033e-05   4.89e-06     -6.199      0.000      -4e-05   -2.07e-05
==============================================================================
Omnibus:                        7.487   Durbin-Watson:                   1.954
Prob(Omnibus):                  0.024   Jarque-Bera (JB):                9.049
Skew:                           0.258   Prob(JB):                       0.0108
Kurtosis:                       3.783   Cond. No.                         882.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
Plot saved to: E:/OneDrive/Studia/Studia magisterskie/Masterarbeit - Wirtschaftwissenschaft/szacunki_powiatowe_II_RP_from_final_gdp/Convergence_Analysis/VA_per_capita/va_growth_with_regression_r_group.png
📊 Regression summary:

                            OLS Regression Results
==============================================================================
Dep. Variable:                      y   R-squared:                       0.136
Model:                            OLS   Adj. R-squared:                  0.132
Method:                 Least Squares   F-statistic:                     38.43
Date:                Sun, 28 Dec 2025   Prob (F-statistic):           2.39e-09
Time:                        13:24:51   Log-Likelihood:                 629.76
No. Observations:                 247   AIC:                            -1256.
Df Residuals:                     245   BIC:                            -1248.
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.0366      0.002     16.028      0.000       0.032       0.041
x1         -3.033e-05   4.89e-06     -6.199      0.000      -4e-05   -2.07e-05
==============================================================================
Omnibus:                        7.487   Durbin-Watson:                   1.954
Prob(Omnibus):                  0.024   Jarque-Bera (JB):                9.049
Skew:                           0.258   Prob(JB):                       0.0108
Kurtosis:                       3.783   Cond. No.                         882.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
Plot saved to: E:/OneDrive/Studia/Studia magisterskie/Masterarbeit - Wirtschaftwissenschaft/szacunki_powiatowe_II_RP_from_final_gdp/Convergence_Analysis/VA_per_capita/va_growth_with_regression_big_cities.png

In [242]:
# Compute the regional demeaned VA in constant prices per capita and add to the production_by_year df.

for year, df in production_by_year.items():
        # Get region sums for this year
        regional_df = sum_up_regions(df, d_to_r)

        # Compute regional mean VA per capita = VA sum / Population sum
        regional_va_mean_per_capita = regional_df['VA_constant_prices_per_capita']

        # Map districts to their region means
        region_for_district = df.index.map(d_to_r)
        district_regional_mean = region_for_district.map(regional_va_mean_per_capita)

        # Subtract regional mean from district value
        df['VA_constant_prices_per_capita_demeaned'] = df['VA_constant_prices_per_capita'] - district_regional_mean

        # Regional mean
        df['VA_constant_prices_per_capita_regional_mean'] = district_regional_mean

        # Assign back to dict (optional since df is mutable)
        production_by_year[year] = df

In [243]:
plot_va_growth_scatter(production_by_year, all_years=all_years, x_col_name='VA_constant_prices_per_capita_demeaned', save_to_path=plots_output_path+"/Convergence_Analysis/VA_per_capita/va_growth_vs_VA_pc_region_demeaned.png", d_to_r_group=d_to_r_group, r_group_to_color=r_group_to_color, title = 'Growth of VA in Constant Prices Per Capita from 1924 to 1938', x_label = 'VA (CP, Per Capita) demeaned by average regional VA (CP, Per Capita)')
plot_va_growth_scatter(production_by_year, all_years=all_years, x_col_name='VA_constant_prices_per_capita_demeaned', save_to_path=plots_output_path+"/Convergence_Analysis/VA_per_capita/va_growth_vs_VA_pc_region_demeaned_is_big_city.png", d_to_r_group=is_big_city, r_group_to_color=big_cities_to_color, title = 'Growth of VA in Constant Prices Per Capita from 1924 to 1938', x_label = 'VA (CP, Per Capita) demeaned by average regional VA (CP, Per Capita)')
plot_va_growth_scatter(production_by_year, all_years=all_years, x_col_name='VA_constant_prices_per_capita_demeaned', save_to_path=plots_output_path+"/Convergence_Analysis/VA_per_capita/va_growth_vs_VA_pc_region_demeaned_example_r.png", d_to_r_group=d_to_example_r, r_group_to_color=example_r_to_color, title = 'Growth of VA in Constant Prices Per Capita from 1924 to 1938', x_label = 'VA (CP, Per Capita) demeaned by average regional VA (CP, Per Capita)')

📊 Regression summary:

                            OLS Regression Results
==============================================================================
Dep. Variable:                      y   R-squared:                       0.068
Model:                            OLS   Adj. R-squared:                  0.065
Method:                 Least Squares   F-statistic:                     17.97
Date:                Sun, 28 Dec 2025   Prob (F-statistic):           3.18e-05
Time:                        13:24:56   Log-Likelihood:                 620.50
No. Observations:                 247   AIC:                            -1237.
Df Residuals:                     245   BIC:                            -1230.
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.0235      0.001     18.330      0.000       0.021       0.026
x1         -2.922e-05   6.89e-06     -4.239      0.000   -4.28e-05   -1.56e-05
==============================================================================
Omnibus:                        4.101   Durbin-Watson:                   1.997
Prob(Omnibus):                  0.129   Jarque-Bera (JB):                3.883
Skew:                           0.227   Prob(JB):                        0.144
Kurtosis:                       3.414   Cond. No.                         190.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
Plot saved to: E:/OneDrive/Studia/Studia magisterskie/Masterarbeit - Wirtschaftwissenschaft/szacunki_powiatowe_II_RP_from_final_gdp/Convergence_Analysis/VA_per_capita/va_growth_vs_VA_pc_region_demeaned.png
📊 Regression summary:

                            OLS Regression Results
==============================================================================
Dep. Variable:                      y   R-squared:                       0.068
Model:                            OLS   Adj. R-squared:                  0.065
Method:                 Least Squares   F-statistic:                     17.97
Date:                Sun, 28 Dec 2025   Prob (F-statistic):           3.18e-05
Time:                        13:24:57   Log-Likelihood:                 620.50
No. Observations:                 247   AIC:                            -1237.
Df Residuals:                     245   BIC:                            -1230.
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.0235      0.001     18.330      0.000       0.021       0.026
x1         -2.922e-05   6.89e-06     -4.239      0.000   -4.28e-05   -1.56e-05
==============================================================================
Omnibus:                        4.101   Durbin-Watson:                   1.997
Prob(Omnibus):                  0.129   Jarque-Bera (JB):                3.883
Skew:                           0.227   Prob(JB):                        0.144
Kurtosis:                       3.414   Cond. No.                         190.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
Plot saved to: E:/OneDrive/Studia/Studia magisterskie/Masterarbeit - Wirtschaftwissenschaft/szacunki_powiatowe_II_RP_from_final_gdp/Convergence_Analysis/VA_per_capita/va_growth_vs_VA_pc_region_demeaned_is_big_city.png
📊 Regression summary:

                            OLS Regression Results
==============================================================================
Dep. Variable:                      y   R-squared:                       0.068
Model:                            OLS   Adj. R-squared:                  0.065
Method:                 Least Squares   F-statistic:                     17.97
Date:                Sun, 28 Dec 2025   Prob (F-statistic):           3.18e-05
Time:                        13:24:58   Log-Likelihood:                 620.50
No. Observations:                 247   AIC:                            -1237.
Df Residuals:                     245   BIC:                            -1230.
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.0235      0.001     18.330      0.000       0.021       0.026
x1         -2.922e-05   6.89e-06     -4.239      0.000   -4.28e-05   -1.56e-05
==============================================================================
Omnibus:                        4.101   Durbin-Watson:                   1.997
Prob(Omnibus):                  0.129   Jarque-Bera (JB):                3.883
Skew:                           0.227   Prob(JB):                        0.144
Kurtosis:                       3.414   Cond. No.                         190.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
Plot saved to: E:/OneDrive/Studia/Studia magisterskie/Masterarbeit - Wirtschaftwissenschaft/szacunki_powiatowe_II_RP_from_final_gdp/Convergence_Analysis/VA_per_capita/va_growth_vs_VA_pc_region_demeaned_example_r.png

In [244]:
plot_va_growth_scatter(production_by_year, all_years=all_years, x_col_name='VA_constant_prices_per_capita_regional_mean', save_to_path=plots_output_path+"/Convergence_Analysis/VA_per_capita/va_growth_vs_VA_pc_region_mean.png", d_to_r_group=d_to_r_group, r_group_to_color=r_group_to_color, title = 'Growth of VA in Constant Prices Per Capita from 1924 to 1938', x_label = 'VA (CP, Per Capita) demeaned by average regional VA (CP, Per Capita)')

📊 Regression summary:

                            OLS Regression Results
==============================================================================
Dep. Variable:                      y   R-squared:                       0.046
Model:                            OLS   Adj. R-squared:                  0.042
Method:                 Least Squares   F-statistic:                     11.90
Date:                Sun, 28 Dec 2025   Prob (F-statistic):           0.000659
Time:                        13:25:00   Log-Likelihood:                 617.62
No. Observations:                 247   AIC:                            -1231.
Df Residuals:                     245   BIC:                            -1224.
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.0340      0.003     11.288      0.000       0.028       0.040
x1         -2.173e-05    6.3e-06     -3.450      0.001   -3.41e-05   -9.32e-06
==============================================================================
Omnibus:                        8.861   Durbin-Watson:                   1.979
Prob(Omnibus):                  0.012   Jarque-Bera (JB):               12.240
Skew:                           0.250   Prob(JB):                      0.00220
Kurtosis:                       3.969   Cond. No.                     1.14e+03
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.14e+03. This might indicate that there are
strong multicollinearity or other numerical problems.
Plot saved to: E:/OneDrive/Studia/Studia magisterskie/Masterarbeit - Wirtschaftwissenschaft/szacunki_powiatowe_II_RP_from_final_gdp/Convergence_Analysis/VA_per_capita/va_growth_vs_VA_pc_region_mean.png

## Spatial Autocorrelation

In [206]:
spatial_autocorrelation_over_time(year_to_df=production_by_year, col_name='VA_constant_prices_per_capita', distance_matrix=distance_matrix, threshold=120000, measures=["moran", "geary"], var_name_in_title="Total Value Added Per Capita (1924 złotys)", save_to_path=plots_output_path+"/Convergence_Analysis/VA_per_capita/spatial_VA_cp_per_capita.png")

Years with 'VA_constant_prices_per_capita': [1924, 1925, 1926, 1927, 1928, 1929, 1930, 1931, 1932, 1933, 1934, 1935, 1936, 1937, 1938]
Plot saved to: E:/OneDrive/Studia/Studia magisterskie/Masterarbeit - Wirtschaftwissenschaft/szacunki_powiatowe_II_RP_from_final_gdp/Convergence_Analysis/VA_per_capita/spatial_VA_cp_per_capita.png

### Within- vs. Between-Regional variance (decomposition)

In [207]:
# Decompose the variance of VA in constant prices per capita to between-region and within-region variance.
decomp_df = variance_decomposition(production_by_year, d_to_r, 'VA_constant_prices_per_capita')
plot_cumulative_variance_decomposition(decomp_df=decomp_df, path_to_save = plots_output_path+"/Convergence_Analysis/VA_per_capita/", variable_name = 'VA_constant_prices_per_capita')

### 2-level Beta-Convergence Model

In [208]:
beta_2_level_convergence_result = estimate_multilevel_convergence(production_by_year, district_to_region=d_to_r)

         Mixed Linear Model Regression Results
=======================================================
Model:             MixedLM Dependent Variable: growth
No. Observations:  247     Method:             REML
No. Groups:        16      Scale:              0.0002
Min. group size:   8       Log-Likelihood:     659.0124
Max. group size:   28      Converged:          Yes
Mean group size:   15.4
-------------------------------------------------------
             Coef.  Std.Err.   z    P>|z| [0.025 0.975]
-------------------------------------------------------
Intercept     0.090    0.037  2.394 0.017  0.016  0.163
between_init -0.012    0.006 -1.838 0.066 -0.024  0.001
within_init  -0.026    0.003 -9.184 0.000 -0.032 -0.021
Group Var     0.000    0.003
=======================================================

c:\Users\janek\miniconda3\Lib\site-packages\statsmodels\regression\mixed_linear_model.py:2237: ConvergenceWarning: The MLE may be on the boundary of the parameter space.
  warnings.warn(msg, ConvergenceWarning)

## Contributions of Sectors to Inequality

### Theil decompositions

In [209]:
spatial_inequality_results = analyze_all_years_theil(production_by_year=production_by_year, d_to_r=d_to_r, sum_up_regions=sum_up_regions)
plot_theil_decompositions(spatial_inequality_results, save_path=plots_output_path+"/Convergence_Analysis/VA_per_capita/", sector_colors=sector_colors)

### Coefficients of Variation (districts)

In [210]:
plot_cv_over_time(production_by_year, 'VA_constant_prices_per_capita', save_path=plots_output_path+"/Convergence_Analysis/dist_total_VA_constant_per_capita", var_title='Value Added Per Capita (1924 złotys)')
plot_cv_over_time(production_by_year, 'Agriculture_VA_constant_prices_per_capita', save_path=plots_output_path+"/Convergence_Analysis/agriculture_VA_constant_per_capita")
plot_cv_over_time(production_by_year, 'Industry_VA_constant_prices_per_capita', save_path=plots_output_path+"/Convergence_Analysis/industry_VA_constant_per_capita")
plot_cv_over_time(production_by_year, 'Public_Services_VA_constant_prices_per_capita', save_path=plots_output_path+"/Convergence_Analysis/public_services_VA_constant_per_capita")
plot_cv_over_time(production_by_year, 'Private_Services_VA_constant_prices_per_capita', save_path=plots_output_path+"/Convergence_Analysis/private_services_VA_constant_per_capita")

Plot saved to E:/OneDrive/Studia/Studia magisterskie/Masterarbeit - Wirtschaftwissenschaft/szacunki_powiatowe_II_RP_from_final_gdp/Convergence_Analysis/dist_total_VA_constant_per_capita

e:\git_projects\border_harmonization_toolkit\examples\interwar_poland\district_gdp\gdp_computation_utils\plots.py:834: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.savefig(save_path)

Plot saved to E:/OneDrive/Studia/Studia magisterskie/Masterarbeit - Wirtschaftwissenschaft/szacunki_powiatowe_II_RP_from_final_gdp/Convergence_Analysis/agriculture_VA_constant_per_capita
Plot saved to E:/OneDrive/Studia/Studia magisterskie/Masterarbeit - Wirtschaftwissenschaft/szacunki_powiatowe_II_RP_from_final_gdp/Convergence_Analysis/industry_VA_constant_per_capita
Plot saved to E:/OneDrive/Studia/Studia magisterskie/Masterarbeit - Wirtschaftwissenschaft/szacunki_powiatowe_II_RP_from_final_gdp/Convergence_Analysis/public_services_VA_constant_per_capita
Plot saved to E:/OneDrive/Studia/Studia magisterskie/Masterarbeit - Wirtschaftwissenschaft/szacunki_powiatowe_II_RP_from_final_gdp/Convergence_Analysis/private_services_VA_constant_per_capita

### Coefficients of Variation (whole regions)

In [211]:
plot_cv_over_time({year:sum_up_regions(production_by_year[year], d_to_r) for year in production_by_year.keys()}, 'VA_constant_prices_per_capita', save_path=plots_output_path+"/Convergence_Analysis/region_total_VA_constant_per_capita")
plot_cv_over_time({year:sum_up_regions(production_by_year[year], d_to_r) for year in production_by_year.keys()}, 'Agriculture_VA_constant_prices_per_capita', save_path=plots_output_path+"/Convergence_Analysis/region_agriculture_VA_constant_per_capita")
plot_cv_over_time({year:sum_up_regions(production_by_year[year], d_to_r) for year in production_by_year.keys()}, 'Industry_VA_constant_prices_per_capita', save_path=plots_output_path+"/Convergence_Analysis/region_industry_VA_constant_per_capita")
plot_cv_over_time({year:sum_up_regions(production_by_year[year], d_to_r) for year in production_by_year.keys()}, 'Public_Services_VA_constant_prices_per_capita', save_path=plots_output_path+"/Convergence_Analysis/region_public_services_VA_constant_per_capita")
plot_cv_over_time({year:sum_up_regions(production_by_year[year], d_to_r) for year in production_by_year.keys()}, 'Private_Services_VA_constant_prices_per_capita', save_path=plots_output_path+"/Convergence_Analysis/region_private_services_VA_constant_per_capita")

Plot saved to E:/OneDrive/Studia/Studia magisterskie/Masterarbeit - Wirtschaftwissenschaft/szacunki_powiatowe_II_RP_from_final_gdp/Convergence_Analysis/region_total_VA_constant_per_capita

e:\git_projects\border_harmonization_toolkit\examples\interwar_poland\district_gdp\gdp_computation_utils\plots.py:834: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.savefig(save_path)

Plot saved to E:/OneDrive/Studia/Studia magisterskie/Masterarbeit - Wirtschaftwissenschaft/szacunki_powiatowe_II_RP_from_final_gdp/Convergence_Analysis/region_agriculture_VA_constant_per_capita

e:\git_projects\border_harmonization_toolkit\examples\interwar_poland\district_gdp\gdp_computation_utils\plots.py:834: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.savefig(save_path)

Plot saved to E:/OneDrive/Studia/Studia magisterskie/Masterarbeit - Wirtschaftwissenschaft/szacunki_powiatowe_II_RP_from_final_gdp/Convergence_Analysis/region_industry_VA_constant_per_capita

e:\git_projects\border_harmonization_toolkit\examples\interwar_poland\district_gdp\gdp_computation_utils\plots.py:834: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.savefig(save_path)

Plot saved to E:/OneDrive/Studia/Studia magisterskie/Masterarbeit - Wirtschaftwissenschaft/szacunki_powiatowe_II_RP_from_final_gdp/Convergence_Analysis/region_public_services_VA_constant_per_capita

e:\git_projects\border_harmonization_toolkit\examples\interwar_poland\district_gdp\gdp_computation_utils\plots.py:834: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.savefig(save_path)

Plot saved to E:/OneDrive/Studia/Studia magisterskie/Masterarbeit - Wirtschaftwissenschaft/szacunki_powiatowe_II_RP_from_final_gdp/Convergence_Analysis/region_private_services_VA_constant_per_capita

e:\git_projects\border_harmonization_toolkit\examples\interwar_poland\district_gdp\gdp_computation_utils\plots.py:834: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.savefig(save_path)

In [212]:
variables = ['VA_constant_prices_per_capita', 'Agriculture_VA_constant_prices_per_capita', 'Industry_VA_constant_prices_per_capita', 'Services_VA_constant_prices_per_capita']
var_titles = {var:var.split("_")[0] if var.split("_")[0]!="VA" else "Total" for var in variables}
var_colors = {
    'VA_constant_prices_per_capita': 'red',
    'Agriculture_VA_constant_prices_per_capita': 'green',
    'Industry_VA_constant_prices_per_capita': 'purple',
    'Services_VA_constant_prices_per_capita': 'darkblue'
}
plot_many_cvs_over_time(production_by_year, variables, save_path=plots_output_path+"/Convergence_Analysis/Sector_Comparison/VA_cp_per_capita_CV_by_sector", var_titles=var_titles, var_colors=var_colors, title = "District Value Added Per Capita by Sector")

Plot saved to E:/OneDrive/Studia/Studia magisterskie/Masterarbeit - Wirtschaftwissenschaft/szacunki_powiatowe_II_RP_from_final_gdp/Convergence_Analysis/Sector_Comparison/VA_cp_per_capita_CV_by_sector

e:\git_projects\border_harmonization_toolkit\examples\interwar_poland\district_gdp\gdp_computation_utils\plots.py:911: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.savefig(save_path)

# Convergence of single sectors

## Agriculture

### Theil Regional Decomposition

In [214]:
plot_theil_decomposition_sequence(production_by_year, 'Agriculture_VA_constant_prices_per_capita', save_path=plots_output_path+"/Convergence_Analysis/Agriculture/theil_agriculture_VA_constant_per_capita", d_to_r=d_to_r)

### CVs

In [215]:
variables = ['Pszenica', 'Żyto', 'Jęczmień', 'Owies', 'Ziemniaki']
var_titles = {
    'Wheat': 'Wheat',
    'Rye': 'Rye',
    'Barley': 'Barley',
    'Oats': 'Oats',
    'Potatoes': 'Potatoes'
}
plot_many_cvs_over_time(crops_prices_year_df_clean, variables, save_path=plots_output_path+"/Convergence_Analysis/Agriculture/crop_prices_CV", var_titles=var_titles, title="Crop Prices")

KeyError: 'Variable'

In [221]:
variables = ['Pszenica_yields_per_ha', 'Żyto_yields_per_ha', 'Jęczmień_yields_per_ha', 'Owies_yields_per_ha', 'Ziemniaki_yields_per_ha']
var_titles = {
    'Pszenica_yields_per_ha': 'Wheat',
    'Żyto_yields_per_ha': 'Rye',
    'Jęczmień_yields_per_ha': 'Barley',
    'Owies_yields_per_ha': 'Oats',
    'Ziemniaki_yields_per_ha': 'Potatoes'
}
plot_many_cvs_over_time(crops_production_years, variables, save_path=plots_output_path+"/Convergence_Analysis/Agriculture/yields_from_ha_CV", var_titles=var_titles, title="Crop Yields per Hectare")

KeyError: 'Variable'

In [216]:
livestock_translations = {
    'Konie': 'Horses',
    'Bydło rogate': 'Cows',
    'Trzoda chlewna': 'Pigs',
    'Owce i kozy': 'Sheep and Goats'
}

for year, df in livestock_year_df_dict.items():
    for col in ['Livestock/Horses', 'Livestock/Horned Cattle', 'Livestock/Pigs', 'Livestock/Sheep and Goats']:
        new_col = livestock_translations[col.split(':')[0]]+" Per Capita"
        df[new_col] = df[col]/production_by_year[year]['Population']

KeyError: 'Livestock/Horses'

In [ ]:
variables = [f"{name} Per Capita" for name in livestock_translations.values()]
plot_many_cvs_over_time(livestock_year_df_dict, variables, save_path=plots_output_path+"/Convergence_Analysis/Agriculture/Livestock_by_type_CV", var_titles=var_titles)

In [224]:
plot_cv_over_time(livestock_year_df_dict, 'Livestock_Units_per_capita', save_path=plots_output_path+"/Convergence_Analysis/Agriculture/Livestock_Units_per_capita_CV", var_title='Livestock Units (Computed According to Dederko (1937)) Per Capita')

Plot saved to E:/OneDrive/Studia/Studia magisterskie/Masterarbeit - Wirtschaftwissenschaft/szacunki_powiatowe_II_RP_corrected/Convergence_Analysis/Agriculture/Livestock_Units_per_capita_CV

e:\git_projects\border_harmonization_toolkit\examples\interwar_poland\district_gdp\gdp_computation_utils\plots.py:834: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

Theil-Index

In [225]:
plot_theil_decomposition_sequence(livestock_year_df_dict, 'Livestock_Units_per_capita', save_path=plots_output_path+"/Convergence_Analysis/Agriculture/theil_Livestock_Units_per_capita_CV", var_title='Livestock Units (Computed According to Dederko (1937)) Per Capita', d_to_r=d_to_r, pop_by_year=production_by_year)

### Spatial convergence

Value Added Per Capita

In [217]:
spatial_autocorrelation_over_time(year_to_df=production_by_year, col_name='Agriculture_VA_constant_prices_per_capita', distance_matrix=distance_matrix, threshold=120000, var_name_in_title="Agriculture Value Added Per Capita (1924 złotys)", save_to_path=plots_output_path+"/Convergence_Analysis/Agriculture/spatial_Agriculture_VA_cp_per_capita.png")

Years with 'Agriculture_VA_constant_prices_per_capita': [1924, 1925, 1926, 1927, 1928, 1929, 1930, 1931, 1932, 1933, 1934, 1935, 1936, 1937, 1938]
Plot saved to: E:/OneDrive/Studia/Studia magisterskie/Masterarbeit - Wirtschaftwissenschaft/szacunki_powiatowe_II_RP_from_final_gdp/Convergence_Analysis/Agriculture/spatial_Agriculture_VA_cp_per_capita.png

5 Main Crops Total Value Per Capita

In [218]:
spatial_autocorrelation_over_time(year_to_df=crops_production_years, col_name='5 Main Crops Value Per Capita', distance_matrix=distance_matrix, threshold=120000, var_name_in_title="5 Main Crops Production Value Per Capita (1924 złotys)", save_to_path=plots_output_path+"/Convergence_Analysis/Agriculture/spatial_5_main_crops_per_capita.png")

Years with '5 Main Crops Value Per Capita': [1924, 1925, 1926, 1927, 1928, 1929, 1930, 1931, 1932, 1933, 1934, 1935, 1936, 1937, 1938]
Plot saved to: E:/OneDrive/Studia/Studia magisterskie/Masterarbeit - Wirtschaftwissenschaft/szacunki_powiatowe_II_RP_from_final_gdp/Convergence_Analysis/Agriculture/spatial_5_main_crops_per_capita.png

Livestock Per Capita

In [219]:
spatial_autocorrelation_over_time(year_to_df=livestock_year_df_dict, col_name='Livestock_Units_per_capita', distance_matrix=distance_matrix, threshold=120000, var_name_in_title="Livestock Value Added Per Capita (1924 złotys)", save_to_path=plots_output_path+"/Convergence_Analysis/Agriculture/spatial_Livestock_VA_cp_per_capita.png")

Years with 'Livestock_Units_per_capita': [1924, 1925, 1926, 1927, 1928, 1929, 1930, 1931, 1932, 1933, 1934, 1935, 1936, 1937, 1938]
Plot saved to: E:/OneDrive/Studia/Studia magisterskie/Masterarbeit - Wirtschaftwissenschaft/szacunki_powiatowe_II_RP_from_final_gdp/Convergence_Analysis/Agriculture/spatial_Livestock_VA_cp_per_capita.png

Livestock Per Capita by Type

In [220]:
variables = [f"{name} Per Capita" for name in livestock_translations.values()]
moran_df = plot_morans_I_over_time(
    production_by_year=livestock_year_df_dict,
    weights=weights,
    variables=variables,
    threshold=120000,
    save_path=plots_output_path + "/Convergence_Analysis/Agriculture/Morans_I_livestock.png",
    title="of Livestock Per Capita"
)

KeyError: 'Variable'

Yields from hectare

In [ ]:
variables = [
    'Pszenica_yields_per_ha', 
    'Żyto_yields_per_ha', 
    'Jęczmień_yields_per_ha', 
    'Owies_yields_per_ha', 
    'Ziemniaki_yields_per_ha'
]

var_titles = {
    'Pszenica_yields_per_ha': 'Wheat',
    'Żyto_yields_per_ha': 'Rye',
    'Jęczmień_yields_per_ha': 'Barley',
    'Owies_yields_per_ha': 'Oats',
    'Ziemniaki_yields_per_ha': 'Potatoes'
}

# Assuming you have 'crops_production_years' dict {year: DataFrame}
# and 'distance_matrix' ready

moran_df = plot_morans_I_over_time(
    production_by_year=crops_production_years,
    weights=weights,
    variables=variables,
    var_titles=var_titles,
    threshold=120000,
    save_path=plots_output_path + "/Convergence_Analysis/Agriculture/Morans_I_crop_yields.png",
    title="of Crop Yields per Hectare"
)

Prices

In [ ]:
variables = ['Pszenica', 'Żyto', 'Jęczmień', 'Owies', 'Ziemniaki']
var_titles = {
    'Pszenica': 'Wheat',
    'Żyto': 'Rye',
    'Jęczmień': 'Barley',
    'Owies': 'Oats',
    'Ziemniaki': 'Potatoes'
}

# Assuming you have 'crops_production_years' dict {year: DataFrame}
# and 'distance_matrix' ready

moran_df = plot_morans_I_over_time(
    production_by_year=crops_prices_year_df_clean,
    weights=weights,
    variables=variables,
    var_titles=var_titles,
    threshold=120000,
    save_path=plots_output_path + "/Convergence_Analysis/Agriculture/Morans_I_crop_prices.png",
    title="of Crop Prices per Hectare"
)

## Industry

Industry VA Per Capita CV

In [221]:
plot_cv_over_time({year:df for year, df in production_by_year.items() if year in [1924,1925,1926,1927,1928,1935,1936,1937,1938]}, 'Industry_VA_constant_prices_per_capita', var_title="Industry Value Added Per Capita (1924 złotys)", save_path=plots_output_path+"/Convergence_Analysis/Industry/Industry_VA_per_capita_CV")

Plot saved to E:/OneDrive/Studia/Studia magisterskie/Masterarbeit - Wirtschaftwissenschaft/szacunki_powiatowe_II_RP_from_final_gdp/Convergence_Analysis/Industry/Industry_VA_per_capita_CV

e:\git_projects\border_harmonization_toolkit\examples\interwar_poland\district_gdp\gdp_computation_utils\plots.py:834: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  print(f"Plot saved to {save_path}")

Theil-index

In [222]:
plot_theil_decomposition_sequence({year:df for year, df in production_by_year.items() if year in [1924,1925,1926,1927,1928,1935,1936,1937,1938]}, 'Industry_VA_constant_prices_per_capita', var_title="Industry Value Added Per Capita (1924 złotys)", save_path=plots_output_path+"/Convergence_Analysis/Industry/Theil_Industry_VA_per_capita", d_to_r=d_to_r, pop_by_year=production_by_year)

Spatial autocorrelation

In [223]:
spatial_autocorrelation_over_time(year_to_df={year:df for year, df in production_by_year.items() if year in [1924,1925,1926,1927,1928,1935,1936,1937,1938]}, col_name='Industry_VA_constant_prices_per_capita', distance_matrix=distance_matrix, threshold=120000, var_name_in_title="Industry Value Added Per Capita (1924 złotys)", save_to_path=plots_output_path+"/Convergence_Analysis/Industry/spatial_Industry_VA_per_capita")

Years with 'Industry_VA_constant_prices_per_capita': [1924, 1925, 1926, 1927, 1928, 1935, 1936, 1937, 1938]
Plot saved to: E:/OneDrive/Studia/Studia magisterskie/Masterarbeit - Wirtschaftwissenschaft/szacunki_powiatowe_II_RP_from_final_gdp/Convergence_Analysis/Industry/spatial_Industry_VA_per_capita

### Employment

Coefficient of Variation

In [224]:
for year in total_employment.keys():
    total_employment[year]['Employment Per Capita'] = total_employment[year]['Total Employment I-VII']/production_by_year[year]['Population']

Coefficient of Variation

In [225]:
plot_cv_over_time({year:df for year, df in total_employment.items() if year in [1924,1925,1926,1927,1928,1935,1936,1937,1938]}, 'Employment Per Capita', var_title="Employment in Industry Per Capita", save_path=plots_output_path+"/Convergence_Analysis/Industry/Employment_per_capita_CV")

Plot saved to E:/OneDrive/Studia/Studia magisterskie/Masterarbeit - Wirtschaftwissenschaft/szacunki_powiatowe_II_RP_from_final_gdp/Convergence_Analysis/Industry/Employment_per_capita_CV

e:\git_projects\border_harmonization_toolkit\examples\interwar_poland\district_gdp\gdp_computation_utils\plots.py:834: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  print(f"Plot saved to {save_path}")

Theil-index

In [226]:
plot_theil_decomposition_sequence({year:df for year, df in total_employment.items() if year in [1924,1925,1926,1927,1928,1935,1936,1937,1938]}, 'Total Employment I-VII (Per Capita)', var_title="Employment in Industry", save_path=plots_output_path+"/Convergence_Analysis/Industry/Theil_Industry_Employment_per_capita", d_to_r=d_to_r, pop_by_year=production_by_year)

Spatial Autocorrelation

In [227]:
# Spatial autocorrelation of industry employment
spatial_autocorrelation_over_time(year_to_df={year:df for year, df in total_employment.items() if year in [1924,1925,1926,1927,1928,1935,1936,1937,1938]}, col_name='Employment Per Capita', distance_matrix=distance_matrix, threshold=100000, var_name_in_title="Yearly Wage in Industry", save_to_path=plots_output_path+"/Convergence_Analysis/Industry/spatial_employment")

Years with 'Employment Per Capita': [1924, 1925, 1926, 1927, 1928, 1935, 1936, 1937, 1938]
Plot saved to: E:/OneDrive/Studia/Studia magisterskie/Masterarbeit - Wirtschaftwissenschaft/szacunki_powiatowe_II_RP_from_final_gdp/Convergence_Analysis/Industry/spatial_employment

### Coefficients of Variation for Wages

In [228]:
plot_cv_over_time(average_hourly_wage_year, 'Average Wage', save_path=plots_output_path+"/Convergence_Analysis/Industry/hourly_wage_CV", var_title="Average District Hourly Wage in Industry")
plot_cv_over_time(average_yearly_wage_year, 'Average Wage', save_path=plots_output_path+"/Convergence_Analysis/Industry/yearly_wage_CV", var_title="Average District Yearly Wage in Industry")

Plot saved to E:/OneDrive/Studia/Studia magisterskie/Masterarbeit - Wirtschaftwissenschaft/szacunki_powiatowe_II_RP_from_final_gdp/Convergence_Analysis/Industry/hourly_wage_CV

e:\git_projects\border_harmonization_toolkit\examples\interwar_poland\district_gdp\gdp_computation_utils\plots.py:834: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  print(f"Plot saved to {save_path}")

Plot saved to E:/OneDrive/Studia/Studia magisterskie/Masterarbeit - Wirtschaftwissenschaft/szacunki_powiatowe_II_RP_from_final_gdp/Convergence_Analysis/Industry/yearly_wage_CV

### Theil-Index of Wages

In [229]:
plot_theil_decomposition_sequence(average_hourly_wage_year, 'Average Wage', var_title="District Average Hourly Wage", save_path=plots_output_path+"/Convergence_Analysis/Industry/Theil_Industry_Hourly_Wage", d_to_r=d_to_r, pop_by_year=production_by_year)

In [230]:
plot_theil_decomposition_sequence(average_yearly_wage_year, 'Average Wage', var_title="District Average Yearly Wage", save_path=plots_output_path+"/Convergence_Analysis/Industry/Theil_Industry_Yearly_Wage", d_to_r=d_to_r, pop_by_year=production_by_year)

### Spatial Autocorrelation of Wages

Yearly Wages

In [231]:
# Spatial autocorrelation of average YEARLY wage
spatial_autocorrelation_over_time(year_to_df=average_yearly_wage_year, col_name='Average Wage', distance_matrix=distance_matrix, threshold=100000, var_name_in_title="Yearly Wage in Industry", save_to_path=plots_output_path+"/Convergence_Analysis/Industry/spatial_yearly_wage")

Years with 'Average Wage': [1924, 1925, 1926, 1927, 1928, 1929, 1930, 1931, 1932, 1933, 1934, 1935, 1936, 1937, 1938]
Plot saved to: E:/OneDrive/Studia/Studia magisterskie/Masterarbeit - Wirtschaftwissenschaft/szacunki_powiatowe_II_RP_from_final_gdp/Convergence_Analysis/Industry/spatial_yearly_wage

Hourly Wages

In [232]:
# Spatial autocorrelation of average HOURLY wage
spatial_autocorrelation_over_time(year_to_df=average_hourly_wage_year, col_name='Average Wage', distance_matrix=distance_matrix, threshold=100000, var_name_in_title="Hourly Industry Wage", save_to_path=plots_output_path+"/Convergence_Analysis/Industry/spatial_hourly_wage")

Years with 'Average Wage': [1924, 1925, 1926, 1927, 1928, 1929, 1930, 1931, 1932, 1933, 1934, 1935, 1936, 1937, 1938]
Plot saved to: E:/OneDrive/Studia/Studia magisterskie/Masterarbeit - Wirtschaftwissenschaft/szacunki_powiatowe_II_RP_from_final_gdp/Convergence_Analysis/Industry/spatial_hourly_wage

## Services

In [233]:
plot_cv_over_time(production_by_year, 'Services_VA_constant_prices_per_capita', var_title="Services Value Added Per Capita (1924 złotys)", save_path=plots_output_path+"/Convergence_Analysis/Services/Services_VA_per_capita_CV")

Plot saved to E:/OneDrive/Studia/Studia magisterskie/Masterarbeit - Wirtschaftwissenschaft/szacunki_powiatowe_II_RP_from_final_gdp/Convergence_Analysis/Services/Services_VA_per_capita_CV

e:\git_projects\border_harmonization_toolkit\examples\interwar_poland\district_gdp\gdp_computation_utils\plots.py:834: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  print(f"Plot saved to {save_path}")

In [234]:
plot_theil_decomposition_sequence(production_by_year, 'Services_VA_constant_prices_per_capita', var_title="Services Value Added Per Capita (1924 złotys)", save_path=plots_output_path+"/Convergence_Analysis/Services/Theil_Services_VA_per_capita", d_to_r=d_to_r, pop_by_year=production_by_year)

In [235]:
spatial_autocorrelation_over_time(production_by_year, col_name='Services_VA_constant_prices_per_capita', distance_matrix=distance_matrix, threshold=120000, var_name_in_title="Services Value Added Per Capita (1924 złotys)", save_to_path=plots_output_path+"/Convergence_Analysis/Services/spatial_Services_VA_per_capita")

Years with 'Services_VA_constant_prices_per_capita': [1924, 1925, 1926, 1927, 1928, 1929, 1930, 1931, 1932, 1933, 1934, 1935, 1936, 1937, 1938]
Plot saved to: E:/OneDrive/Studia/Studia magisterskie/Masterarbeit - Wirtschaftwissenschaft/szacunki_powiatowe_II_RP_from_final_gdp/Convergence_Analysis/Services/spatial_Services_VA_per_capita

In [236]:
for year in trade_permissions_year_df.keys():
    trade_permissions_year_df[year]['Total Employment Per Capita'] = trade_permissions_year_df[year]['Total Employment']/production_by_year[year]['Population']

In [237]:
plot_cv_over_time(trade_permissions_year_df, 'Total Employment Per Capita', var_title="Employment in Private Services Per Capita", save_path=plots_output_path+"/Convergence_Analysis/Services/Employment_Private_Services_per_capita_CV")

Plot saved to E:/OneDrive/Studia/Studia magisterskie/Masterarbeit - Wirtschaftwissenschaft/szacunki_powiatowe_II_RP_from_final_gdp/Convergence_Analysis/Services/Employment_Private_Services_per_capita_CV

e:\git_projects\border_harmonization_toolkit\examples\interwar_poland\district_gdp\gdp_computation_utils\plots.py:834: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  print(f"Plot saved to {save_path}")

In [239]:
plot_theil_decomposition_sequence(trade_permissions_year_df, 'Total Employment Per Capita', var_title="Employment in Private Services Per Capita", save_path=plots_output_path+"/Convergence_Analysis/Services/Theil_Private_Services_Employment_per_capita", d_to_r=d_to_r, pop_by_year=production_by_year)

In [240]:
spatial_autocorrelation_over_time(trade_permissions_year_df, col_name='Total Employment Per Capita', distance_matrix=distance_matrix, threshold=120000, var_name_in_title="Employment in Private Services Per Capita", save_to_path=plots_output_path+"/Convergence_Analysis/Services/spatial_Private_Services_Employment_per_capita")

Years with 'Total Employment Per Capita': [1924, 1925, 1926, 1927, 1928, 1929, 1930, 1931, 1932, 1933, 1934, 1935, 1936, 1937, 1938]
Plot saved to: E:/OneDrive/Studia/Studia magisterskie/Masterarbeit - Wirtschaftwissenschaft/szacunki_powiatowe_II_RP_from_final_gdp/Convergence_Analysis/Services/spatial_Private_Services_Employment_per_capita

# Backup - additional examples of function use

## Harmonize an additional CSV file

In [ ]:
# _, data_table_metadata_dict, _ = adm_history_api.load_data_table(data_table_id = '30.06.1938-livestock_ready', version='original')

In [ ]:
# input_csv_path = adm_history_processor.adm_units_raw_data_folder + data_table_metadata_dict.data_table_id + ".csv"
# output_csv_path = adm_history_processor.processed_data_output_folder + data_table_metadata_dict.data_table_id + ".csv"
# #Harmonize single csv file
# adm_history_processor.process_csv_file(
#                     input_csv_path=input_csv_path,
#                     output_csv_path=output_csv_path,
#                     data_table_metadata_dict=data_table_metadata_dict,
#                     date_to=reference_date
#                 )